using Content.Client._FinalStand.Interface;
using Content.Client.UserInterface.Systems.Actions.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Actions.Widgets;

[GenerateTypedNameReferences]
public sealed partial class ActionsBar : UIWidget
{
    // FINALSTAND: the bar owns its own geometry so the panels that dodge it cannot drift out of
    // step with it. Columns at SlotSize, plus grid gaps, the panel content margin and its border.
    public const int Columns = 6;
    private const int GridGap = 4;
    private const int PanelMargin = 8;
    private const int PanelMarginVertical = 7;

    public const float BarWidth =
        ActionButton.SlotSize * Columns + GridGap * (Columns - 1) + PanelMargin * 2 + 2;

    public const float BarHeight = ActionButton.SlotSize + PanelMarginVertical * 2 + 2;

    public ActionsBar()
    {
        RobustXamlLoader.Load(this);
        ActionsPanel.PanelOverride = FSHudStyle.ModulePanel();
    }
}
