// SPDX-FileCopyrightText: 2024 gluesniffler <159397573+gluesniffler@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Shitmed.Medical.Surgery;

[GenerateTypedNameReferences]
public sealed partial class SurgeryWindow : DefaultWindow
{
    public event Action? OnFrameUpdate;

    /// <summary>Guidance text is advice, not the control. Hiding it never hides Perform.</summary>
    public bool GuidanceVisible => GuidanceToggle.Pressed;

    public SurgeryWindow()
    {
        RobustXamlLoader.Load(this);

        GuidanceToggle.OnToggled += args =>
        {
            GuidanceLabel.Visible = args.Pressed;
            GuidanceIcon.Visible = args.Pressed;
        };
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        OnFrameUpdate?.Invoke();
    }
}