
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Shitmed.Medical.Surgery;

[GenerateTypedNameReferences]
public sealed partial class SurgeryWindow : DefaultWindow
{
    public event Action? OnFrameUpdate;

    public bool GuidanceVisible => GuidanceToggle.Pressed;

    public SurgeryWindow()
    {
        RobustXamlLoader.Load(this);

        GuidanceToggle.OnToggled += args =>
        {
            GuidanceLabel.Visible = args.Pressed;
            GuidanceIcon.Visible = args.Pressed;
        };
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        OnFrameUpdate?.Invoke();
    }
}