using Content.Shared._FinalStand.MedicalOps.Shop;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._FinalStand.MedicalOps.UI;

[GenerateTypedNameReferences]
public sealed partial class SyringeShopWindow : DefaultWindow
{
    private static readonly Color OwnedColor = Color.FromHex("#4FBF7A");
    private static readonly Color MutedColor = Color.FromHex("#7F8891");

    public event Action<string>? OnBuyPressed;

    public SyringeShopWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(FSSyringeShopState state)
    {
        Tiers.DisposeAllChildren();

        CreditsLabel.Text = Loc.GetString("fs-syringe-shop-credits", ("credits", state.Credits));

        var ownedRank = FSSyringeShopDefs.RankOf(state.OwnedTierId);

        foreach (var tier in FSSyringeShopDefs.Tiers)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 3),
            };

            var text = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };
            text.AddChild(new Label { Text = tier.Name });
            text.AddChild(new Label
            {
                Text = tier.Description,
                StyleClasses = { "LabelSubText" },
                Modulate = MutedColor,
            });
            row.AddChild(text);

            var owned = tier.Rank <= ownedRank;

            if (owned)
            {
                row.AddChild(new Label
                {
                    Text = Loc.GetString("fs-syringe-shop-owned"),
                    Modulate = OwnedColor,
                    MinWidth = 110,
                    VerticalAlignment = VAlignment.Center,
                });
            }
            else
            {
                var id = tier.Id;
                var button = new Button
                {
                    Text = Loc.GetString("fs-syringe-shop-buy", ("price", tier.Price)),
                    MinWidth = 110,
                    Disabled = state.Credits < tier.Price,
                };
                button.OnPressed += _ => OnBuyPressed?.Invoke(id);
                row.AddChild(button);
            }

            Tiers.AddChild(row);
        }
    }
}
