using Content.Shared._FinalStand.MedicalOps.Shop;
using Content.Shared.Storage;
using Content.Shared.Weapons.Ranged.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._FinalStand.MedicalOps.UI;

[GenerateTypedNameReferences]
public sealed partial class SyringeShopWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypes = default!;

    private static readonly Color OwnedColor = Color.FromHex("#4FBF7A");
    private static readonly Color MutedColor = Color.FromHex("#7F8891");
    private static readonly Color ConfirmColor = Color.FromHex("#C9A227");

    private const string BaseGunProto = "LauncherSyringe";

    public event Action<string>? OnBuyPressed;

    private string? _pendingConfirm;

    public SyringeShopWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    private string DescribeTier(FSSyringeTierDef tier)
    {
        if (!_prototypes.TryIndex<EntityPrototype>(tier.SpawnId, out var proto))
            return tier.Description;

        var rounds = proto.TryGetComponent<StorageComponent>("Storage", out var storage)
            ? Capacity(storage)
            : 0;

        var baseRounds = _prototypes.TryIndex<EntityPrototype>(BaseGunProto, out var baseProto)
                         && baseProto.TryGetComponent<StorageComponent>("Storage", out var baseStorage)
            ? Capacity(baseStorage)
            : 0;

        var fireRate = proto.TryGetComponent<GunComponent>("Gun", out var gun)
            ? gun.FireRate
            : 0f;

        return Loc.GetString("fs-syringe-shop-stats",
            ("rounds", rounds),
            ("roundsDelta", rounds - baseRounds),
            ("fireRate", fireRate.ToString("0.0")));
    }

    private static int Capacity(StorageComponent storage)
    {
        var total = 0;
        foreach (var box in storage.Grid)
            total += (box.Width + 1) * (box.Height + 1);

        return total;
    }

    public void Populate(FSSyringeShopState state)
    {
        Tiers.DisposeAllChildren();

        CreditsLabel.Text = Loc.GetString("fs-syringe-shop-credits", ("credits", state.Credits));

        var ownedRank = FSSyringeShopDefs.RankOf(state.OwnedTierId);

        foreach (var tier in FSSyringeShopDefs.Tiers)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 3),
            };

            var text = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };
            text.AddChild(new Label { Text = tier.Name });
            text.AddChild(new Label
            {
                Text = DescribeTier(tier),
                StyleClasses = { "LabelSubText" },
                Modulate = MutedColor,
            });
            row.AddChild(text);

            var owned = tier.Rank <= ownedRank;

            if (owned)
            {
                row.AddChild(new Label
                {
                    Text = Loc.GetString("fs-syringe-shop-owned"),
                    Modulate = OwnedColor,
                    MinWidth = 110,
                    VerticalAlignment = VAlignment.Center,
                });
            }
            else
            {
                var id = tier.Id;
                var awaiting = _pendingConfirm == id;

                var button = new Button
                {
                    Text = awaiting
                        ? Loc.GetString("fs-syringe-shop-confirm")
                        : Loc.GetString("fs-syringe-shop-buy", ("price", tier.Price)),
                    MinWidth = 110,
                    Disabled = state.Credits < tier.Price,
                    Modulate = awaiting ? ConfirmColor : Color.White,
                };

                button.OnPressed += _ =>
                {
                    if (_pendingConfirm == id)
                    {
                        _pendingConfirm = null;
                        OnBuyPressed?.Invoke(id);
                        return;
                    }

                    _pendingConfirm = id;
                    Populate(state);
                };

                row.AddChild(button);
            }

            Tiers.AddChild(row);
        }
    }
}
