using Content.Client._FinalStand.Stylesheets;
using Content.Shared._FinalStand.MedicalOps;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._FinalStand.MedicalOps.UI;

[GenerateTypedNameReferences]
public sealed partial class SyringeFillerWindow : DefaultWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;

    public event Action? OnFill;
    public event Action? OnPurge;
    public event Action<bool>? OnEject;

    private FSSyringeFillerBuiState? _state;

    public SyringeFillerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Stylesheet = FSMenuStylesheet.Get(
            IoCManager.Resolve<IUserInterfaceManager>(),
            IoCManager.Resolve<IResourceCache>());

        FillButton.OnPressed += _ => OnFill?.Invoke();
        PurgeButton.OnPressed += _ => OnPurge?.Invoke();
        EjectSourceButton.OnPressed += _ => OnEject?.Invoke(true);
        EjectMagazineButton.OnPressed += _ => OnEject?.Invoke(false);
    }

    public void UpdateState(FSSyringeFillerBuiState state)
    {
        _state = state;

        SourceNameLabel.Text = state.SourceName ?? Loc.GetString("fs-syringe-filler-slot-empty");
        SourceContentsLabel.Text = state.SourceContents ?? string.Empty;
        SourceBar.Value = state.SourceMax > 0 ? state.SourceVolume / state.SourceMax : 0f;
        EjectSourceButton.Disabled = state.SourceName == null;

        MagazineNameLabel.Text = state.MagazineName ?? Loc.GetString("fs-syringe-filler-slot-empty");
        MagazineContentsLabel.Text = state.MagazineContents ?? string.Empty;
        MagazineBar.Value = state.MagazineMax > 0 ? state.MagazineVolume / state.MagazineMax : 0f;
        EjectMagazineButton.Disabled = state.MagazineName == null;

        DartsLabel.Text = state.MagazineName == null
            ? string.Empty
            : Loc.GetString("fs-syringe-filler-darts",
                ("darts", state.Darts),
                ("max", state.MaxDarts),
                ("units", (int) state.MagazineVolume),
                ("maxunits", (int) state.MagazineMax));

        StatusLabel.Text = state.Status;
        FillButton.Disabled = !state.CanFill;
        PurgeButton.Disabled = !state.CanPurge || state.Running;
        WorkBar.Visible = state.Running;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_state is not { Running: true })
            return;

        var total = (_state.FinishAt - _state.StartedAt).TotalSeconds;
        if (total <= 0)
            return;

        var done = (_timing.CurTime - _state.StartedAt).TotalSeconds;
        WorkBar.Value = Math.Clamp((float) (done / total), 0f, 1f);
    }
}
