using Content.Client._FinalStand.Stylesheets;
using Content.Shared._FinalStand.Armor.Shop;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._FinalStand.Armor.UI;

[GenerateTypedNameReferences]
public sealed partial class ArmorShopWindow : DefaultWindow
{
    public event Action<string>? OnBuyPressed;

    private readonly IPrototypeManager _protos;
    private readonly IComponentFactory _factory;

    private FSArmorShopState? _state;
    private string? _selectedTierId;

    public ArmorShopWindow()
    {
        RobustXamlLoader.Load(this);
        _protos = IoCManager.Resolve<IPrototypeManager>();
        _factory = IoCManager.Resolve<IComponentFactory>();

        Stylesheet = FSMenuStylesheet.Get(
            IoCManager.Resolve<IUserInterfaceManager>(),
            IoCManager.Resolve<IResourceCache>());

        BuyButton.OnPressed += _ =>
        {
            if (_selectedTierId != null)
                OnBuyPressed?.Invoke(_selectedTierId);
        };
    }

    public void Populate(FSArmorShopState state)
    {
        _state = state;

        TierListContainer.DisposeAllChildren();
        foreach (var tier in FSArmorShopDefs.Tiers)
            TierListContainer.AddChild(BuildTierRow(tier));

        // Show equipped tier on open, else first tier.
        var toShow = state.EquippedTierId != null
            ? FSArmorShopDefs.GetTier(state.EquippedTierId)
            : FSArmorShopDefs.Tiers.Count > 0 ? FSArmorShopDefs.Tiers[0] : null;
        if (toShow != null) SelectTier(toShow);
    }

    private Control BuildTierRow(FSArmorTierDef tier)
    {
        var state = _state;
        var isEquipped = tier.Id == state?.EquippedTierId;
        var canAfford = CanAffordTier(tier);

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 0, 0, 4),
        };

        var btn = new Button
        {
            Text = tier.Name,
            HorizontalExpand = true,
            MinWidth = 170,
        };
        btn.OnPressed += _ => SelectTier(tier);
        row.AddChild(btn);

        var statusLabel = new Label
        {
            HorizontalExpand = false,
            HorizontalAlignment = HAlignment.Right,
            Margin = new Thickness(6, 0, 0, 0),
        };
        if (isEquipped)
        {
            statusLabel.Text = "EQUIPPED";
            statusLabel.Modulate = FSUiPalette.StatePositive;
        }
        else
        {
            statusLabel.Text = $"${tier.Price:N0}";
            statusLabel.Modulate = canAfford ? FSUiPalette.Currency : FSUiPalette.StateNegative;
        }
        row.AddChild(statusLabel);
        return row;
    }

    private void SelectTier(FSArmorTierDef tier)
    {
        _selectedTierId = tier.Id;
        SelectedTierName.Text = tier.Name;

        StatsContainer.DisposeAllChildren();

        void AddRow(string label, string value, Color valueColor)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(0, 1, 0, 1),
            };
            row.AddChild(new Label { Text = label, HorizontalExpand = true, Modulate = FSUiPalette.TextMuted });
            row.AddChild(new Label { Text = value, Modulate = valueColor });
            StatsContainer.AddChild(row);
        }

        var stats = FSArmorShopDefs.GetStats(tier, _protos, _factory);

        foreach (var damageType in DisplayOrder)
        {
            if (stats.Resistances.TryGetValue(damageType, out var reduction) && reduction != 0f)
                AddRow($"{damageType}:", $"-{reduction * 100:0}%", FSUiPalette.StatePositive);
        }

        var speedPct = stats.SpeedMod * 100f;
        var speedText = speedPct >= 0f ? $"+{speedPct:0}%" : $"{speedPct:0}%";
        AddRow("Speed:", speedText, stats.SpeedMod >= 0f ? FSUiPalette.StatePositive : FSUiPalette.StateNegative);

        if (stats.StaminaReduction > 0f)
            AddRow("Stamina resist:", $"-{stats.StaminaReduction * 100:0}%", FSUiPalette.StatePositive);

        StatsContainer.AddChild(new Control { MinHeight = 6 });

        var refund = FSArmorShopDefs.GetRefund(_state?.EquippedTierId);
        if (refund > 0)
            AddRow("Refund on current:", $"${refund:N0}", FSUiPalette.Currency);

        AddRow("Net cost:", $"${FSArmorShopDefs.GetNetCost(_state?.EquippedTierId, tier):N0}", FSUiPalette.Currency);

        var isEquipped = tier.Id == _state?.EquippedTierId;
        BuyButton.Disabled = isEquipped || !CanAffordTier(tier);
    }

    private bool CanAffordTier(FSArmorTierDef tier)
    {
        return _state != null && _state.Credits >= FSArmorShopDefs.GetNetCost(_state.EquippedTierId, tier);
    }

    private static readonly string[] DisplayOrder =
        ["Blunt", "Slash", "Piercing", "Heat", "Radiation", "Caustic", "Shock", "Explosion"];
}
