using System.Numerics;
using Content.Client._FinalStand.Stylesheets;
using Content.Shared._FinalStand.Armor.Shop;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._FinalStand.Armor.UI;

[GenerateTypedNameReferences]
public sealed partial class ArmorShopWindow : DefaultWindow
{
    public event Action<string>? OnBuyPressed;

    private readonly IPrototypeManager _protos;
    private readonly IComponentFactory _factory;

    private FSArmorShopState? _state;
    private string? _selectedTierId;

    private const float BarTrackWidth = 168f;
    private const float BarHeight = 12f;

    private static readonly string[] RankNumerals = ["I", "II", "III", "IV", "V", "VI", "VII", "VIII"];

    private static readonly string[] DisplayOrder =
        ["Blunt", "Slash", "Piercing", "Heat", "Radiation", "Caustic", "Shock", "Explosion"];

    public ArmorShopWindow()
    {
        RobustXamlLoader.Load(this);
        _protos = IoCManager.Resolve<IPrototypeManager>();
        _factory = IoCManager.Resolve<IComponentFactory>();

        Stylesheet = FSMenuStylesheet.Get(
            IoCManager.Resolve<IUserInterfaceManager>(),
            IoCManager.Resolve<IResourceCache>());

        PreviewPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = FSUiPalette.BgRecess,
            BorderColor = FSUiPalette.BorderNeutral,
            BorderThickness = new Thickness(1),
        };

        BuyButton.OnPressed += _ =>
        {
            if (_selectedTierId != null)
                OnBuyPressed?.Invoke(_selectedTierId);
        };
    }

    public void Populate(FSArmorShopState state)
    {
        _state = state;
        CreditsLabel.Text = $"${state.Credits:N0}";

        TierListContainer.DisposeAllChildren();
        for (var i = 0; i < FSArmorShopDefs.Tiers.Count; i++)
            TierListContainer.AddChild(BuildTierCard(FSArmorShopDefs.Tiers[i], i));

        var toShow = FSArmorShopDefs.GetTier(_selectedTierId)
                     ?? FSArmorShopDefs.GetTier(state.EquippedTierId)
                     ?? (FSArmorShopDefs.Tiers.Count > 0 ? FSArmorShopDefs.Tiers[0] : null);

        if (toShow != null)
            SelectTier(toShow);
    }

    private Control BuildTierCard(FSArmorTierDef tier, int index)
    {
        var isEquipped = tier.Id == _state?.EquippedTierId;
        var isSelected = tier.Id == _selectedTierId;
        var canAfford = CanAffordTier(tier);

        var accent = isEquipped ? FSUiPalette.StatePositive
            : isSelected ? FSUiPalette.AccentBrand
            : FSUiPalette.BorderNeutral;

        var button = new ContainerButton
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 6),
        };
        button.OnPressed += _ => SelectTier(tier);

        var panel = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = isSelected || isEquipped ? FSUiPalette.BgElevated : FSUiPalette.BgSurface,
                BorderColor = accent,
                BorderThickness = new Thickness(isSelected || isEquipped ? 2 : 1),
            },
        };

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(10, 7),
            HorizontalExpand = true,
        };

        row.AddChild(new Label
        {
            Text = index < RankNumerals.Length ? RankNumerals[index] : (index + 1).ToString(),
            MinWidth = 26,
            Modulate = accent,
            VerticalAlignment = VAlignment.Center,
        });

        var text = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };
        text.AddChild(new Label
        {
            Text = tier.Name,
            Modulate = canAfford || isEquipped ? FSUiPalette.TextPrimary : FSUiPalette.TextMuted,
        });

        if (isEquipped)
        {
            text.AddChild(new Label { Text = "EQUIPPED", Modulate = FSUiPalette.StatePositive });
        }
        else
        {
            var net = FSArmorShopDefs.GetNetCost(_state?.EquippedTierId, tier);
            text.AddChild(new Label
            {
                Text = $"${net:N0}",
                Modulate = canAfford ? FSUiPalette.Currency : FSUiPalette.StateNegative,
            });
        }

        row.AddChild(text);
        panel.AddChild(row);
        button.AddChild(panel);
        return button;
    }

    private void SelectTier(FSArmorTierDef tier)
    {
        _selectedTierId = tier.Id;

        var index = 0;
        for (var i = 0; i < FSArmorShopDefs.Tiers.Count; i++)
        {
            if (FSArmorShopDefs.Tiers[i].Id == tier.Id)
                index = i;
        }

        SelectedTierName.Text = tier.Name;
        SelectedTierRank.Text = $"TIER {(index < RankNumerals.Length ? RankNumerals[index] : (index + 1).ToString())}";

        PreviewContainer.DisposeAllChildren();
        var preview = new EntityPrototypeView { Scale = new Vector2(2f, 2f) };
        preview.SetPrototype(tier.SpawnId);
        PreviewContainer.AddChild(preview);

        BuildStats(tier);
        BuildCost(tier);
        RefreshTierCards();
    }

    private void BuildStats(FSArmorTierDef tier)
    {
        StatsContainer.DisposeAllChildren();

        var stats = FSArmorShopDefs.GetStats(tier, _protos, _factory);

        StatsContainer.AddChild(SectionLabel("PROTECTION"));

        var any = false;
        foreach (var damageType in DisplayOrder)
        {
            if (!stats.Resistances.TryGetValue(damageType, out var reduction) || reduction == 0f)
                continue;

            any = true;
            StatsContainer.AddChild(BuildStatBar(
                damageType,
                reduction,
                $"{reduction * 100:0}%",
                FSUiPalette.StatePositive));
        }

        if (stats.StaminaReduction > 0f)
        {
            any = true;
            StatsContainer.AddChild(BuildStatBar(
                "Stamina",
                stats.StaminaReduction,
                $"{stats.StaminaReduction * 100:0}%",
                FSUiPalette.StatePositive));
        }

        if (!any)
            StatsContainer.AddChild(new Label { Text = "No protection.", Modulate = FSUiPalette.TextMuted });

        StatsContainer.AddChild(new Control { MinHeight = 10 });
        StatsContainer.AddChild(SectionLabel("MOBILITY"));

        var speedPct = stats.SpeedMod * 100f;
        StatsContainer.AddChild(BuildStatBar(
            "Speed",
            MathF.Abs(stats.SpeedMod),
            speedPct >= 0f ? $"+{speedPct:0}%" : $"{speedPct:0}%",
            stats.SpeedMod >= 0f ? FSUiPalette.StatePositive : FSUiPalette.StateNegative));
    }

    private void BuildCost(FSArmorTierDef tier)
    {
        CostContainer.DisposeAllChildren();

        var refund = FSArmorShopDefs.GetRefund(_state?.EquippedTierId);
        var net = FSArmorShopDefs.GetNetCost(_state?.EquippedTierId, tier);
        var isEquipped = tier.Id == _state?.EquippedTierId;
        var canAfford = CanAffordTier(tier);

        CostContainer.AddChild(CostRow("Price", $"${tier.Price:N0}", FSUiPalette.TextMuted));

        if (refund > 0 && !isEquipped)
            CostContainer.AddChild(CostRow("Trade-in", $"-${refund:N0}", FSUiPalette.StatePositive));

        CostContainer.AddChild(CostRow("TOTAL", $"${net:N0}",
            canAfford || isEquipped ? FSUiPalette.Currency : FSUiPalette.StateNegative));

        if (isEquipped)
        {
            BuyButton.Text = "EQUIPPED";
            BuyButton.Disabled = true;
        }
        else if (!canAfford)
        {
            var short_ = net - (_state?.Credits ?? 0);
            BuyButton.Text = $"NEED ${short_:N0} MORE";
            BuyButton.Disabled = true;
        }
        else
        {
            BuyButton.Text = $"BUY  —  ${net:N0}";
            BuyButton.Disabled = false;
        }
    }

    private void RefreshTierCards()
    {
        TierListContainer.DisposeAllChildren();
        for (var i = 0; i < FSArmorShopDefs.Tiers.Count; i++)
            TierListContainer.AddChild(BuildTierCard(FSArmorShopDefs.Tiers[i], i));
    }

    private static Label SectionLabel(string text) => new()
    {
        Text = text,
        StyleClasses = { "FSSectionHeader" },
        Margin = new Thickness(0, 0, 0, 4),
    };

    private static Control CostRow(string label, string value, Color valueColor)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 2, 0, 2),
        };
        row.AddChild(new Label { Text = label, HorizontalExpand = true, Modulate = FSUiPalette.TextMuted });
        row.AddChild(new Label { Text = value, Modulate = valueColor });
        return row;
    }

    private static Control BuildStatBar(string label, float fraction, string valueText, Color color)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 2, 0, 2),
        };

        row.AddChild(new Label
        {
            Text = label,
            MinWidth = 78,
            Modulate = FSUiPalette.TextMuted,
            VerticalAlignment = VAlignment.Center,
        });

        var track = new PanelContainer
        {
            MinSize = new Vector2(BarTrackWidth, BarHeight),
            VerticalAlignment = VAlignment.Center,
            PanelOverride = new StyleBoxFlat { BackgroundColor = FSUiPalette.BgTrack },
        };

        var filled = Math.Clamp(fraction, 0f, 1f);
        track.AddChild(new PanelContainer
        {
            MinSize = new Vector2(BarTrackWidth * filled, BarHeight),
            HorizontalAlignment = HAlignment.Left,
            PanelOverride = new StyleBoxFlat { BackgroundColor = color },
        });

        row.AddChild(track);

        row.AddChild(new Label
        {
            Text = valueText,
            MinWidth = 56,
            Align = Label.AlignMode.Right,
            Modulate = color,
            VerticalAlignment = VAlignment.Center,
        });

        return row;
    }

    private bool CanAffordTier(FSArmorTierDef tier)
    {
        return _state != null && _state.Credits >= FSArmorShopDefs.GetNetCost(_state.EquippedTierId, tier);
    }
}
