using System.Numerics;
using Content.Client._FinalStand.WaveHud;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Content.Client.UserInterface.Systems.Inventory;
using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Screens;

[GenerateTypedNameReferences]
public sealed partial class DefaultGameScreen : InGameScreen
{
    // Two hand slots plus a gap. HotbarGui centres the hands, so this clears them.
    private const float HandsHalfWidth = 78f;

    // Clears the vitals block, which is 168px wide at a 24px margin in the same corner.
    private const float AlertsClearance = 210f;

    // The bottom band is five modules with four equal gaps, and the hands must land on the screen's
    // centre line. That only works if both flanks sum to the same width, so the weapon module is
    // widened to match vitals+actions. These are that solution at 1920:
    //   vitals 240 | actions 228 | hands 148 | storage 112 | weapon 356, gaps of 197.
    private const float ActionBarAnchor = 0.2995f;

    private const int ActionColumns = 6;

    // Matches the 18px XAML margin the hotbar and inventory use to clear the XP bar, plus the 5px
    // screen margin the presets apply.
    private const float BottomBandLift = 23f;

    // Clears the vitals panel in the same corner. Its height varies with the status pills, so this
    // is its tallest form rather than a live read - alerts shifting as you bleed would be worse.
    private const float AlertsLift = BottomBandLift + VitalsTallest + 6f;

    // Vitals panel at its tallest (stamina bar + a row of status pills).
    private const float VitalsTallest = 68f;

    // Clears the bottom band so chat stacks above it rather than over the weapon module.
    private const float ChatLift = 190f;
    private const float ChatEdgeMargin = 12f;

    // The prototype's chat is 290x~150 on a 1600-wide screen; these are that at 1920.
    private const float ChatDefaultWidth = 348f;
    private const float ChatDefaultHeight = 180f;
    private const float ChatMaxWidth = 520f;
    private const float ChatMaxHeight = 380f;
    private const float ChatMinWidth = 220f;
    private const float ChatMinHeight = 90f;
    private bool _applyingChatBox;
    private const float ChatToggleWidth = 20f;

    // Footer of the storage grid, spanning its full width.
    private const float WornButtonHeight = 20f;

    private Button? _chatToggle;
    private bool _chatCollapsed;
    private float _chatWidth = ChatDefaultWidth;
    private float _chatHeight = ChatDefaultHeight;

    public DefaultGameScreen()
    {
        RobustXamlLoader.Load(this);

        AutoscaleMaxResolution = new Vector2i(1080, 770);

        SetAnchorPreset(MainViewport, LayoutPreset.Wide);
        SetAnchorPreset(ViewportContainer, LayoutPreset.Wide);
        SetAnchorAndMarginPreset(TopLeft, LayoutPreset.TopLeft, margin: 10);
        SetAnchorAndMarginPreset(Ghost, LayoutPreset.BottomWide, margin: 80);
        SetAnchorAndMarginPreset(Hotbar, LayoutPreset.BottomWide, margin: 5);
        // FINALSTAND: chat sits above the bottom band on the right, leaving the top right to the
        // wave panel. Combat reads bottom-up, so the top corners stay quiet.
        // Centre right, between the wave panel above and the weapon module below. Constrain, not
        // Begin: a zero-overflow box still lets Begin grow to DesiredSize, and the chat log's
        // desired height is the whole screen - that is what made it cover half the screen.
        SetAnchorPreset(Chat, LayoutPreset.CenterRight);
        SetGrowHorizontal(Chat, GrowDirection.Constrain);
        SetGrowVertical(Chat, GrowDirection.Constrain);
        ApplyChatBox(ChatDefaultWidth, ChatDefaultHeight);

        SetupChatToggle();

        // FINALSTAND: one question per screen region. Status effects are personal condition, so
        // they join the bottom-left survivability corner instead of sharing the top-right with
        // chat and the wave panel. Inventory moves to the bottom right so the equipment strip
        // reads left-to-right as vitals -> hands -> storage.
        SetAnchorPreset(Alerts, LayoutPreset.BottomLeft);
        SetMarginLeft(Alerts, 24f);
        SetMarginRight(Alerts, 24f);
        SetMarginTop(Alerts, -AlertsLift);
        SetMarginBottom(Alerts, -AlertsLift);
        SetGrowHorizontal(Alerts, GrowDirection.End);
        SetGrowVertical(Alerts, GrowDirection.Begin);

        // The toggle moves into the storage panel, under the pocket grid, where the prototype has a
        // labelled WORN button. The equipment grid it opens stays in this widget.
        SetAnchorPreset(Inventory, LayoutPreset.CenterBottom);
        SetMarginLeft(Inventory, HandsHalfWidth);
        SetMarginRight(Inventory, HandsHalfWidth);
        SetMarginTop(Inventory, -BottomBandLift);
        SetMarginBottom(Inventory, -BottomBandLift);
        SetGrowHorizontal(Inventory, GrowDirection.End);
        SetGrowVertical(Inventory, GrowDirection.Begin);

        AdoptWornButton();

        // Six across, wrapping upward. The XAML caps the container at 64px wide for the left-edge
        // column the separated layout still uses, which would squeeze this to one action per row.
        Actions.ActionsContainer.MaxSize = new Vector2(9999, 9999);
        Actions.ActionsContainer.Columns = ActionColumns;
        // Forward, so 1-6 is the top row and 7-12 fills in beneath it.
        Actions.ActionsContainer.ExpandBackwards = false;

        // Centred on the quarter line: that is the midpoint between the vitals block and the hands,
        // so the band reads vitals - actions - hands with even air between them at any width.
        SetAnchorLeft(Actions, ActionBarAnchor);
        SetAnchorRight(Actions, ActionBarAnchor);
        SetAnchorTop(Actions, 1f);
        SetAnchorBottom(Actions, 1f);
        SetMarginLeft(Actions, 0f);
        SetMarginRight(Actions, 0f);
        SetMarginTop(Actions, -BottomBandLift);
        SetMarginBottom(Actions, -BottomBandLift);
        SetGrowHorizontal(Actions, GrowDirection.Both);
        SetGrowVertical(Actions, GrowDirection.Begin);

        Chat.OnResized += ChatOnResized;
        Chat.OnChatResizeFinish += ChatOnResizeFinish;
    }

    private void ChatOnResizeFinish(Vector2 _)
    {
        var marginBottom = Chat.GetValue<float>(MarginBottomProperty);
        var marginLeft = Chat.GetValue<float>(MarginLeftProperty);
        OnChatResized?.Invoke(new Vector2(marginBottom, marginLeft));
    }

    // FINALSTAND: ResizableChatBox owns the drag and clamps itself, so this does not re-apply the
    // box - doing so fought the drag. It only keeps the toggle on the chat's left edge and records
    // the size so collapsing and re-opening restores what the player dragged to.
    private void ChatOnResized()
    {
        if (_applyingChatBox || _chatCollapsed)
            return;

        _chatWidth = Math.Clamp(Chat.Size.X, ChatMinWidth, ChatMaxWidth);
        _chatHeight = Math.Clamp(Chat.Size.Y, ChatMinHeight, ChatMaxHeight);
        PlaceChatToggle(Chat.GetValue<float>(MarginLeftProperty));
    }

    private void PlaceChatToggle(float chatMarginLeft)
    {
        if (_chatToggle == null)
            return;

        _chatToggle.Text = _chatCollapsed ? "◀" : "▶";
        SetMarginRight(_chatToggle, chatMarginLeft);
        SetMarginLeft(_chatToggle, chatMarginLeft - ChatToggleWidth);
    }

    public override ChatBox ChatBox => Chat;

    // Vanilla stored the box as a height/width pair of margins off the top-right anchor. Anchored
    // bottom-right instead, the height grows upward from the band rather than down from the top.
    // Sizes stored under the old layout can be most of the screen, so both axes are clamped.
    public override void SetChatSize(Vector2 size)
    {
        var height = Math.Clamp(MathF.Abs(size.X), ChatMinHeight, ChatMaxHeight);
        var width = Math.Clamp(MathF.Abs(size.Y), ChatMinWidth, ChatMaxWidth);
        ApplyChatBox(width, height);
    }

    // Anchored CenterRight, so the box is laid out around the vertical midpoint of the right edge.
    private void ApplyChatBox(float width, float height)
    {
        _applyingChatBox = true;

        _chatWidth = width;
        _chatHeight = height;

        var visibleWidth = _chatCollapsed ? 0f : width;
        SetMarginLeft(Chat, -(ChatEdgeMargin + visibleWidth));
        SetMarginRight(Chat, -ChatEdgeMargin);
        SetMarginTop(Chat, -height * 0.5f);
        SetMarginBottom(Chat, height * 0.5f);

        Chat.Visible = !_chatCollapsed;
        // Rides the chat's left edge in both states, so it is always the handle you reach for.
        PlaceChatToggle(-(ChatEdgeMargin + visibleWidth));

        _applyingChatBox = false;
    }

    // A real Button rather than a relabelled SlotControl. A slot draws a fixed-size graphic with
    // its own hit area, so stretching one to fit a word left the text outside the clickable part.
    // ToggleInventoryBar is public and is what the slot's handler called anyway.
    private void AdoptWornButton()
    {
        Inventory.InventoryButton.Visible = false;

        var worn = new Button
        {
            Text = Loc.GetString("fs-hud-worn-button"),
            HorizontalAlignment = HAlignment.Stretch,
            HorizontalExpand = true,
            MinSize = new Vector2(0, WornButtonHeight),
            ToolTip = Loc.GetString("fs-hud-worn-tooltip"),
        };

        worn.OnPressed += _ =>
            UserInterfaceManager.GetUIController<InventoryUIController>().ToggleInventoryBar();

        Hotbar.FSWornSlot.AddChild(worn);
    }

    private void SetupChatToggle()
    {
        _chatToggle = new Button
        {
            Text = "▶",
            ToolTip = Loc.GetString("fs-chat-toggle-tooltip"),
            MinSize = new Vector2(ChatToggleWidth, 34),
        };

        AddChild(_chatToggle);
        SetAnchorPreset(_chatToggle, LayoutPreset.CenterRight);
        SetGrowHorizontal(_chatToggle, GrowDirection.Constrain);
        SetGrowVertical(_chatToggle, GrowDirection.Constrain);
        SetMarginTop(_chatToggle, -17f);
        SetMarginBottom(_chatToggle, 17f);

        _chatToggle.OnPressed += _ =>
        {
            _chatCollapsed = !_chatCollapsed;
            ApplyChatBox(_chatWidth, _chatHeight);
        };

        ApplyChatBox(_chatWidth, _chatHeight);
    }
}
