using System.Numerics;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Screens;

[GenerateTypedNameReferences]
public sealed partial class DefaultGameScreen : InGameScreen
{
    // Mirrors WaveHudOverlay's panel width plus its screen margin, taken at scale 1 so the gap holds
    // on every resolution. Keep in step with panelW/margin there.
    private const float WavePanelClearance = 205f + 24f + 12f;

    public DefaultGameScreen()
    {
        RobustXamlLoader.Load(this);

        AutoscaleMaxResolution = new Vector2i(1080, 770);

        SetAnchorPreset(MainViewport, LayoutPreset.Wide);
        SetAnchorPreset(ViewportContainer, LayoutPreset.Wide);
        SetAnchorAndMarginPreset(TopLeft, LayoutPreset.TopLeft, margin: 10);
        SetAnchorAndMarginPreset(Ghost, LayoutPreset.BottomWide, margin: 80);
        SetAnchorAndMarginPreset(Hotbar, LayoutPreset.BottomWide, margin: 5);
        SetAnchorAndMarginPreset(Chat, LayoutPreset.TopRight, margin: 10);

        // FINALSTAND: one question per screen region. Status effects are personal condition, so
        // they join the bottom-left survivability corner instead of sharing the top-right with
        // chat and the wave panel. Inventory moves to the bottom right so the equipment strip
        // reads left-to-right as vitals -> hands -> storage.
        SetAnchorAndMarginPreset(Alerts, LayoutPreset.BottomLeft, margin: 5);

        // The wave panel is a screen overlay, not a control, so nothing stops a widget being drawn
        // under it. It claims 205px plus a 24px margin against the right edge, so inventory anchors
        // to a point clear of that and grows left and up into the gap beside the hotbar.
        SetAnchorPreset(Inventory, LayoutPreset.BottomRight);
        SetMarginLeft(Inventory, -WavePanelClearance);
        SetMarginRight(Inventory, -WavePanelClearance);
        SetMarginTop(Inventory, -5f);
        SetMarginBottom(Inventory, -5f);
        SetGrowHorizontal(Inventory, GrowDirection.Begin);
        SetGrowVertical(Inventory, GrowDirection.Begin);

        Chat.OnResized += ChatOnResized;
        Chat.OnChatResizeFinish += ChatOnResizeFinish;

        MainViewport.OnResized += ResizeActionContainer;
        Inventory.OnResized += ResizeActionContainer;
    }

    private void ResizeActionContainer()
    {
        float indent = Inventory.Size.Y + TopBar.Size.Y + 40;
        Actions.ActionsContainer.MaxGridHeight = MainViewport.Size.Y - indent;
    }

    private void ChatOnResizeFinish(Vector2 _)
    {
        var marginBottom = Chat.GetValue<float>(MarginBottomProperty);
        var marginLeft = Chat.GetValue<float>(MarginLeftProperty);
        OnChatResized?.Invoke(new Vector2(marginBottom, marginLeft));
    }

    private void ChatOnResized()
    {
        var marginBottom = Chat.GetValue<float>(MarginBottomProperty);
        SetMarginTop(Alerts, marginBottom);
    }

    public override ChatBox ChatBox => Chat;

    //TODO: There's probably a better way to do this... but this is also the easiest way.
    public override void SetChatSize(Vector2 size)
    {
        SetMarginBottom(Chat, size.X);
        SetMarginLeft(Chat, size.Y);
        SetMarginTop(Alerts, size.X);
    }
}
