using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Chemistry;
using Content.Shared.Chemistry.Reagent;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Linq;
using System.Numerics;
using Content.Shared.FixedPoint;
using Robust.Client.Graphics;
using static Robust.Client.UserInterface.Controls.BoxContainer;
using Robust.Client.GameObjects;

namespace Content.Client.Chemistry.UI
{
    /// <summary>
    /// Client-side UI used to control a <see cref="SharedChemMasterComponent"/>
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class ChemMasterWindow : FancyWindow
    {
        [Dependency] private IPrototypeManager _prototypeManager = default!;
        [Dependency] private IEntityManager _entityManager = default!;

        private readonly SpriteSystem _sprite;

        public event Action<BaseButton.ButtonEventArgs, ReagentButton>? OnReagentButtonPressed;
        public readonly Button[] PillTypeButtons;

        private bool _pillDosageEdited;
        private bool _pillNumberEdited;
        private bool _bottleDosageEdited;
        private bool _applyingDosageDefaults;

        private readonly RowCache _bufferRows = new();
        private readonly RowCache _inputRows = new();
        private readonly RowCache _outputRows = new();

        private ChemMasterReagentAmount _selectedAmount = ChemMasterReagentAmount.U10;


        private const string PillsRsiPath = "/Textures/Objects/Specific/Chemistry/pills.rsi";

        /// <summary>
        /// Create and initialize the chem master UI client-side. Creates the basic layout,
        /// actual data isn't filled in until the server sends data about the chem master.
        /// </summary>
        public ChemMasterWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            _sprite = _entityManager.System<SpriteSystem>();

            // Pill type selection buttons, in total there are 20 pills.
            // Pill rsi file should have states named as pill1, pill2, and so on.
            var resourcePath = new ResPath(PillsRsiPath);
            var pillTypeGroup = new ButtonGroup();
            PillTypeButtons = new Button[20];
            for (uint i = 0; i < PillTypeButtons.Length; i++)
            {
                // For every button decide which stylebase to have
                // Every row has 10 buttons
                String styleBase = StyleClass.ButtonOpenBoth;
                uint modulo = i % 10;
                if (i > 0 && modulo == 0)
                    styleBase = StyleClass.ButtonOpenRight;
                else if (i > 0 && modulo == 9)
                    styleBase = StyleClass.ButtonOpenLeft;
                else if (i == 0)
                    styleBase = StyleClass.ButtonOpenRight;

                // Generate buttons
                PillTypeButtons[i] = new Button
                {
                    Access = AccessLevel.Public,
                    StyleClasses = { styleBase },
                    MaxSize = new Vector2(42, 28),
                    Group = pillTypeGroup
                };

                // Generate buttons textures
                var specifier = new SpriteSpecifier.Rsi(resourcePath, "pill" + (i + 1));
                TextureRect pillTypeTexture = new TextureRect
                {
                    Texture = _sprite.Frame0(specifier),
                    TextureScale = new Vector2(1.75f, 1.75f),
                    Stretch = TextureRect.StretchMode.KeepCentered,
                };

                PillTypeButtons[i].AddChild(pillTypeTexture);
                Grid.AddChild(PillTypeButtons[i]);
            }

            PillDosage.InitDefaultButtons();
            PillNumber.InitDefaultButtons();
            BottleDosage.InitDefaultButtons();

            PillDosage.ValueChanged += _ => MarkEdited(ref _pillDosageEdited);
            PillNumber.ValueChanged += _ => MarkEdited(ref _pillNumberEdited);
            BottleDosage.ValueChanged += _ => MarkEdited(ref _bottleDosageEdited);

            // Ensure label length is within the character limit.
            LabelLineEdit.IsValid = s => s.Length <= SharedChemMaster.LabelMaxLength;

            BuildAmountSelector();
        }

        private ReagentButton MakeReagentButton(string text, ReagentId id, bool isBuffer)
        {
            var reagentTransferButton = new ReagentButton(text, _selectedAmount, id, isBuffer, StyleClass.ButtonSquare);
            reagentTransferButton.OnPressed += args =>
            {
                reagentTransferButton.Amount = _selectedAmount;
                OnReagentButtonPressed?.Invoke(args, reagentTransferButton);
            };
            return reagentTransferButton;
        }
        private static readonly (string Text, ChemMasterReagentAmount Amount)[] AmountOptions =
        {
            ("1", ChemMasterReagentAmount.U1),
            ("5", ChemMasterReagentAmount.U5),
            ("10", ChemMasterReagentAmount.U10),
            ("15", ChemMasterReagentAmount.U15),
            ("20", ChemMasterReagentAmount.U20),
            ("25", ChemMasterReagentAmount.U25),
            ("30", ChemMasterReagentAmount.U30),
            ("50", ChemMasterReagentAmount.U50),
            ("100", ChemMasterReagentAmount.U100),
        };

        private void BuildAmountSelector()
        {
            var group = new ButtonGroup();

            for (var i = 0; i < AmountOptions.Length; i++)
            {
                var (text, amount) = AmountOptions[i];

                var style = i == 0
                    ? StyleClass.ButtonOpenRight
                    : StyleClass.ButtonOpenBoth;

                var button = new Button
                {
                    Text = text,
                    ToggleMode = true,
                    Group = group,
                    MinWidth = 38,
                    StyleClasses = { style },
                    Pressed = amount == _selectedAmount,
                };

                var captured = amount;
                button.OnPressed += _ => _selectedAmount = captured;

                AmountSelector.AddChild(button);
            }

            var allButton = new Button
            {
                Text = Loc.GetString("chem-master-window-buffer-all-amount"),
                ToggleMode = true,
                Group = group,
                MinWidth = 46,
                StyleClasses = { StyleClass.ButtonOpenLeft },
                Pressed = _selectedAmount == ChemMasterReagentAmount.All,
            };
            allButton.OnPressed += _ => _selectedAmount = ChemMasterReagentAmount.All;
            AmountSelector.AddChild(allButton);
        }

        private List<ReagentButton> CreateReagentTransferButtons(ReagentId reagent, bool isBuffer, bool addReagentButtons)
        {
            if (!addReagentButtons)
                return new List<ReagentButton>();

            return new List<ReagentButton>
            {
                MakeReagentButton(Loc.GetString("chem-master-window-move-button"), reagent, isBuffer),
            };
        }

        /// <summary>
        /// Update the UI state when new state data is received from the server.
        /// </summary>
        /// <param name="state">State data sent by the server.</param>
        public void UpdateState(BoundUserInterfaceState state)
        {
            var castState = (ChemMasterBoundUserInterfaceState)state;

            if (castState.UpdateLabel)
                LabelLine = GenerateLabel(castState);

            // Ensure the Panel Info is updated, including UI elements for Buffer Volume, Output Container and so on
            UpdatePanelInfo(castState);


            switch (castState.DrawSource)
            {
                case ChemMasterDrawSource.Internal:
                    SetBufferText(castState.BufferCurrentVolume, "chem-master-output-buffer-draw");
                    break;
                case ChemMasterDrawSource.External:
                    SetBufferText(castState.InputContainerInfo?.CurrentVolume, "chem-master-output-beaker-draw");
                    break;
                default:
                    throw new($"Chemmaster {castState.OutputContainerInfo} draw source is not set");
            }

            InputEjectButton.Disabled = castState.InputContainerInfo is null;
            OutputEjectButton.Disabled = castState.OutputContainerInfo is null;
            CreateBottleButton.Disabled = castState.OutputContainerInfo?.Reagents == null;
            CreatePillButton.Disabled = castState.OutputContainerInfo?.Entities == null;

            // A greyed-out Create with no stated reason is the single most confusing thing in this
            // window: pills need a pill canister in the output slot, bottles need an empty bottle.
            PackagingHint.Text = castState.OutputContainerInfo switch
            {
                null => Loc.GetString("chem-master-window-hint-no-output"),
                { Entities: null, Reagents: not null } => Loc.GetString("chem-master-window-hint-bottle-only"),
                { Entities: not null, Reagents: null } => Loc.GetString("chem-master-window-hint-pills-only"),
                _ => string.Empty,
            };

            PackagingHint.Visible = PackagingHint.Text.Length > 0;

            UpdateDosageFields(castState);
        }

        //assign default values for pill and bottle fields.
        private void UpdateDosageFields(ChemMasterBoundUserInterfaceState castState)
        {
            var output = castState.OutputContainerInfo;
            var remainingCapacity = output is null ? 0 : (output.MaxVolume - output.CurrentVolume).Int();
            var holdsReagents = output?.Reagents != null;
            var pillNumberMax = holdsReagents ? 0 : remainingCapacity;
            var bottleAmountMax = holdsReagents ? remainingCapacity : 0;
            var outputVolume = castState.DrawSource switch
            {
                ChemMasterDrawSource.Internal => castState.BufferCurrentVolume?.Int() ?? 0,
                ChemMasterDrawSource.External => castState.InputContainerInfo?.CurrentVolume.Int() ?? 0,
                _ => 0,
            };

            PillTypeButtons[castState.SelectedPillType].Pressed = true;

            PillNumber.IsValid = x => x >= 0 && x <= pillNumberMax;
            PillDosage.IsValid = x => x > 0 && x <= castState.PillDosageLimit;
            BottleDosage.IsValid = x => x >= 0 && x <= bottleAmountMax;

            PillNumberLabel.Text = Loc.GetString("chem-master-window-pills-number-max", ("max", pillNumberMax));
            PillDoseLabel.Text = Loc.GetString("chem-master-window-dose-max", ("max", castState.PillDosageLimit));
            BottleDoseLabel.Text = Loc.GetString("chem-master-window-dose-max", ("max", bottleAmountMax));

            _applyingDosageDefaults = true;

            if (!_pillDosageEdited || PillDosage.Value > castState.PillDosageLimit)
                PillDosage.Value = (int) Math.Min(outputVolume, castState.PillDosageLimit);

            if (!_pillNumberEdited || PillNumber.Value > pillNumberMax)
            {
                PillNumber.Value = PillDosage.Value > 0
                    ? Math.Min(outputVolume / PillDosage.Value, pillNumberMax)
                    : 0;
            }

            if (!_bottleDosageEdited || BottleDosage.Value > bottleAmountMax)
                BottleDosage.Value = Math.Min(bottleAmountMax, outputVolume);

            _applyingDosageDefaults = false;
        }

        private void MarkEdited(ref bool flag)
        {
            if (!_applyingDosageDefaults)
                flag = true;
        }

        public void ResetDosageEdits()
        {
            _pillDosageEdited = false;
            _pillNumberEdited = false;
            _bottleDosageEdited = false;
        }
        /// <summary>
        /// Generate a product label based on reagents in the buffer or beaker.
        /// </summary>
        /// <param name="state">State data sent by the server.</param>
        private string GenerateLabel(ChemMasterBoundUserInterfaceState state)
        {
            if (
                state.BufferCurrentVolume == 0 && state.DrawSource == ChemMasterDrawSource.Internal ||
                state.InputContainerInfo?.CurrentVolume == 0 && state.DrawSource == ChemMasterDrawSource.External ||
                state.InputContainerInfo?.Reagents == null
            )
                return "";

            var reagent = (state.DrawSource switch
                {
                    ChemMasterDrawSource.Internal => state.BufferReagents,
                    ChemMasterDrawSource.External => state.InputContainerInfo.Reagents ?? [],
                    _ => throw new($"Chemmaster {state.OutputContainerInfo} draw source is not set"),
                }).MaxBy(r => r.Quantity)
                .Reagent;
            _prototypeManager.TryIndex(reagent.Prototype, out ReagentPrototype? proto);
            return proto?.LocalizedName ?? "";
        }

        /// <summary>
        /// Update the container, buffer, and packaging panels.
        /// </summary>
        /// <param name="state">State data for the dispenser.</param>
        private void UpdatePanelInfo(ChemMasterBoundUserInterfaceState state)
        {
            BufferTransferButton.Pressed = state.Mode == ChemMasterMode.Transfer;
            BufferDiscardButton.Pressed = state.Mode == ChemMasterMode.Discard;

            BuildContainerUI(InputContainerInfo, _inputRows, state.InputContainerInfo, true);
            BuildContainerUI(OutputContainerInfo, _outputRows, state.OutputContainerInfo, false);

            // This has to happen here due to people possibly
            // setting sorting before putting any chemicals
            BufferSortButton.Text = state.SortingType switch
            {
                ChemMasterSortingType.Alphabetical => Loc.GetString("chem-master-window-sort-type-alphabetical"),
                ChemMasterSortingType.Quantity => Loc.GetString("chem-master-window-sort-type-quantity"),
                ChemMasterSortingType.Latest => Loc.GetString("chem-master-window-sort-type-latest"),
                _ => Loc.GetString("chem-master-window-sort-type-none")
            };

            OutputBufferDraw.Pressed = state.DrawSource == ChemMasterDrawSource.Internal;
            OutputBeakerDraw.Pressed = state.DrawSource == ChemMasterDrawSource.External;

            if (!state.BufferReagents.Any())
            {
                _bufferRows.Reset();
                BufferInfo.Children.Clear();
                BufferInfo.Children.Add(new Label { Text = Loc.GetString("chem-master-window-buffer-empty-text") });

                return;
            }

            // This sets up the needed data for sorting later in a list
            // Its done this way to not repeat having to use same code twice (once for sorting
            // and once for displaying)
            var reagentList = new List<(ReagentId reagentId, string name, Color color, FixedPoint2 quantity)>();
            foreach (var (reagent, quantity) in state.BufferReagents)
            {
                var reagentId = reagent;
                _prototypeManager.TryIndex(reagentId.Prototype, out ReagentPrototype? proto);
                var name = proto?.LocalizedName ?? Loc.GetString("chem-master-window-unknown-reagent-text");
                var reagentColor = proto?.SubstanceColor ?? default(Color);
                reagentList.Add(new (reagentId, name, reagentColor, quantity));
            }

            // We sort here since we need sorted list to be filled first.
            // You can easily add any new params you need to it.
            switch (state.SortingType)
            {
                case ChemMasterSortingType.Alphabetical:
                    reagentList = reagentList.OrderBy(x => x.name).ToList();
                    break;

                case ChemMasterSortingType.Quantity:
                    reagentList = reagentList.OrderByDescending(x => x.quantity).ToList();
                    break;
                case ChemMasterSortingType.Latest:
                    reagentList = Enumerable.Reverse(reagentList).ToList();
                    break;

                case ChemMasterSortingType.None:
                default:
                    // This case is pointless but it is there for readability
                    break;
            }

            var header = $"{Loc.GetString("chem-master-window-buffer-label")} {state.BufferCurrentVolume}u";

            var rows = new List<RowData>(reagentList.Count);
            foreach (var reagent in reagentList)
            {
                rows.Add(new RowData(
                    reagent.reagentId.ToString(),
                    reagent.name,
                    reagent.color,
                    reagent.quantity,
                    reagent.reagentId));
            }

            SyncRows(BufferInfo, _bufferRows, header, rows, true, true);
        }

        private void SyncRows(
            Control control,
            RowCache cache,
            string header,
            List<RowData> rows,
            bool isBuffer,
            bool addReagentButtons)
        {
            var key = $"{rows.Count}|{string.Join('|', rows.Select(r => r.Key))}";

            if (key == cache.Key)
            {
                cache.Header.Text = header;

                foreach (var row in rows)
                {
                    if (cache.Quantities.TryGetValue(row.Key, out var label))
                        label.Text = $"{row.Quantity}u";
                }

                return;
            }

            cache.Key = key;
            cache.Quantities.Clear();
            control.Children.Clear();

            cache.Header = new Label { Text = header };
            control.AddChild(cache.Header);

            var rowCount = 0;
            foreach (var row in rows)
            {
                control.AddChild(BuildReagentRow(
                    row.Color,
                    rowCount++,
                    row.Name,
                    row.Reagent,
                    row.Quantity,
                    isBuffer,
                    addReagentButtons,
                    out var quantityLabel));

                cache.Quantities[row.Key] = quantityLabel;
            }
        }

        private readonly record struct RowData(
            string Key,
            string Name,
            Color Color,
            FixedPoint2 Quantity,
            ReagentId Reagent);

        private sealed class RowCache
        {
            public string? Key;
            public Label Header = new();
            public readonly Dictionary<string, Label> Quantities = new();

            public void Reset()
            {
                Key = null;
                Quantities.Clear();
            }
        }

        private void BuildContainerUI(Control control, RowCache cache, ContainerInfo? info, bool addReagentButtons)
        {
            if (info is null)
            {
                if (cache.Key == null)
                    return;

                cache.Reset();
                control.Children.Clear();
                control.Children.Add(new Label
                {
                    Text = Loc.GetString("chem-master-window-no-container-loaded-text")
                });
                return;
            }

            var rows = new List<RowData>();

            if (info.Entities != null)
            {
                foreach (var (id, quantity) in info.Entities.Select(x => (x.Id, x.Quantity)))
                    rows.Add(new RowData($"e:{id}", id, default, quantity, default));
            }

            if (info.Reagents != null)
            {
                foreach (var reagent in info.Reagents)
                {
                    _prototypeManager.TryIndex(reagent.Reagent.Prototype, out ReagentPrototype? proto);
                    var name = proto?.LocalizedName ?? Loc.GetString("chem-master-window-unknown-reagent-text");
                    var reagentColor = proto?.SubstanceColor ?? default(Color);

                    rows.Add(new RowData(
                        reagent.Reagent.ToString(),
                        name,
                        reagentColor,
                        reagent.Quantity,
                        reagent.Reagent));
                }
            }

            SyncRows(control, cache, $"{info.DisplayName}: {info.CurrentVolume}/{info.MaxVolume}", rows, false, addReagentButtons);
        }
        /// <summary>
        /// Take reagent/entity data and present rows, labels, and buttons appropriately. todo sprites?
        /// </summary>
        private Control BuildReagentRow(Color reagentColor, int rowCount, string name, ReagentId reagent, FixedPoint2 quantity, bool isBuffer, bool addReagentButtons, out Label quantityLabel)
        {
            //Colors rows and sets fallback for reagentcolor to the same as background, this will hide colorPanel for entities hopefully
            var rowColor1 = Color.FromHex("#1B1B1E");
            var rowColor2 = Color.FromHex("#202025");
            var currentRowColor = (rowCount % 2 == 1) ? rowColor1 : rowColor2;
            if (reagentColor == default(Color))
            {
                reagentColor = currentRowColor;
            }
            //this calls the separated button builder, and stores the return to render after labels
            var reagentButtonConstructors = CreateReagentTransferButtons(reagent, isBuffer, addReagentButtons);

            quantityLabel = new Label
            {
                Text = $"{quantity}u",
                StyleClasses = { StyleClass.LabelWeak }
            };

            // Create the row layout with the color panel
            var rowContainer = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                Children =
                {
                    new Label { Text = $"{name}: " },
                    quantityLabel,

                    // Padding
                    new Control { HorizontalExpand = true },
                    // Colored panels for reagents
                    new PanelContainer
                    {
                        Name = "colorPanel",
                        VerticalExpand = true,
                        MinWidth = 4,
                        PanelOverride = new StyleBoxFlat
                        {
                            BackgroundColor = reagentColor
                        },
                        Margin = new Thickness(0, 1)
                    }
                }
            };

            // Add the reagent buttons after the color panel
            foreach (var reagentTransferButton in reagentButtonConstructors)
            {
                rowContainer.AddChild(reagentTransferButton);
            }
            //Apply panencontainer to allow for striped rows
            return new PanelContainer
            {
                PanelOverride = new StyleBoxFlat(currentRowColor),
                Children = { rowContainer }
            };
        }

        public string LabelLine
        {
            get => LabelLineEdit.Text;
            set => LabelLineEdit.Text = value;
        }

        private void SetBufferText(FixedPoint2? volume, string text)
        {
            BufferCurrentVolume.Text = $" {volume ?? FixedPoint2.Zero}u";
            DrawSource.Text = Loc.GetString(text);
        }
    }

    public sealed class ReagentButton : Button
    {
        public ChemMasterReagentAmount Amount { get; set; }
        public bool IsBuffer = true;
        public ReagentId Id { get; set; }
        public ReagentButton(string text, ChemMasterReagentAmount amount, ReagentId id, bool isBuffer, string styleClass)
        {
            AddStyleClass(styleClass);
            Text = text;
            Amount = amount;
            Id = id;
            IsBuffer = isBuffer;
        }
    }
}
