using System.Linq;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._FinalStand.MedicalOps;
using Content.Shared.Chemistry;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.FixedPoint;
using Content.Shared.Storage;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client.Chemistry.UI
{
    /// <summary>
    /// Client-side UI used to control a <see cref="ReagentDispenserComponent"/>.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class ReagentDispenserWindow : FancyWindow
    {
        [Dependency] private IPrototypeManager _prototypeManager = default!;
        [Dependency] private IEntityManager _entityManager = default!;
        public event Action<ItemStorageLocation>? OnDispenseReagentButtonPressed;
        public event Action<ItemStorageLocation>? OnEjectJugButtonPressed;

        private static readonly Color ReadyColor = Color.FromHex("#4FBF7A");

        private readonly Dictionary<ItemStorageLocation, ReagentCardControl> _cards = new();
        private readonly List<ItemStorageLocation> _displayed = new();
        private List<ReagentInventoryItem> _inventory = new();

        private FSFieldKitPrototype? _target;
        private Dictionary<string, FixedPoint2> _targetIngredients = new();
        private bool _showFieldKit = true;
        private string _filter = string.Empty;
        private string? _recipeKey;
        private int _dispenseAmount;

        /// <summary>
        /// Create and initialize the dispenser UI client-side. Creates the basic layout,
        /// actual data isn't filled in until the server sends data about the dispenser.
        /// </summary>
        public ReagentDispenserWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            FilterEdit.OnTextChanged += args =>
            {
                _filter = args.Text.Trim();
                ClearTarget(false);
                ApplyFilter();
            };

            TargetChipButton.OnPressed += _ => ClearTarget(true);

            FieldKitTabButton.OnPressed += _ => SetRecipeTab(true);
            CanMakeTabButton.OnPressed += _ => SetRecipeTab(false);
        }

        private void SetRecipeTab(bool fieldKit)
        {
            if (_showFieldKit == fieldKit)
            {
                FieldKitTabButton.Pressed = _showFieldKit;
                CanMakeTabButton.Pressed = !_showFieldKit;
                return;
            }

            _showFieldKit = fieldKit;
            _recipeKey = null;
            RefreshRecipes();
        }

        private void ClearTarget(bool refresh)
        {
            if (_target == null)
                return;

            _target = null;
            _targetIngredients = new Dictionary<string, FixedPoint2>();
            TargetChipButton.Visible = false;
            _recipeKey = null;

            if (!refresh)
                return;

            ApplyFilter();
            RefreshRecipes();
        }

        private void SetTarget(FSFieldKitPrototype kit)
        {
            if (_target?.ID == kit.ID)
            {
                ClearTarget(true);
                return;
            }

            _target = kit;
            _targetIngredients = kit.ResolveIngredients(_prototypeManager);
            _filter = string.Empty;
            FilterEdit.Text = string.Empty;
            TargetChipButton.Text = Loc.GetString("reagent-dispenser-window-target-clear",
                ("recipe", Loc.GetString(kit.Name)));
            TargetChipButton.Visible = true;
            _recipeKey = null;

            ApplyFilter();
            RefreshRecipes();
        }

        /// <summary>
        /// Update the button grid of reagents which can be dispensed.
        /// </summary>
        /// <param name="inventory">Reagents which can be dispensed by this dispenser</param>
        public void UpdateReagentsList(List<ReagentInventoryItem> inventory)
        {
            if (ReagentList == null)
                return;

            //Sort inventory by reagentLabel
            inventory.Sort((x, y) => x.ReagentLabel.CompareTo(y.ReagentLabel));
            _inventory = inventory;

            var seen = new HashSet<ItemStorageLocation>();

            foreach (var item in inventory)
            {
                seen.Add(item.StorageLocation);

                if (_cards.TryGetValue(item.StorageLocation, out var existing))
                {
                    existing.Update(item);
                    continue;
                }

                var card = new ReagentCardControl(item);
                card.OnPressed += loc => OnDispenseReagentButtonPressed?.Invoke(loc);
                card.OnEjectButtonPressed += loc => OnEjectJugButtonPressed?.Invoke(loc);
                _cards[item.StorageLocation] = card;
            }

            foreach (var stale in _cards.Keys.Where(key => !seen.Contains(key)).ToArray())
            {
                _cards[stale].Dispose();
                _cards.Remove(stale);
            }

            ApplyFilter();
        }

        private bool Matches(ReagentCardControl card)
        {
            if (_target != null)
                return card.ReagentId != null && _targetIngredients.ContainsKey(card.ReagentId);

            return _filter.Length == 0
                   || card.ReagentLabel.Contains(_filter, StringComparison.OrdinalIgnoreCase);
        }

        private void ApplyFilter()
        {
            var wanted = new List<ItemStorageLocation>();

            foreach (var item in _inventory)
            {
                if (!_cards.TryGetValue(item.StorageLocation, out var card))
                    continue;

                card.SetDispenseAmount(_dispenseAmount);

                if (Matches(card))
                    wanted.Add(item.StorageLocation);
            }

            NoMatchLabel.Visible = wanted.Count == 0 && _inventory.Count > 0;

            if (wanted.SequenceEqual(_displayed))
                return;

            _displayed.Clear();
            _displayed.AddRange(wanted);

            ReagentList.Children.Clear();
            foreach (var location in wanted)
                ReagentList.AddChild(_cards[location]);
        }

        /// <summary>
        /// Update the UI state when new state data is received from the server.
        /// </summary>
        /// <param name="state">State data sent by the server.</param>
        public void UpdateState(BoundUserInterfaceState state)
        {
            var castState = (ReagentDispenserBoundUserInterfaceState) state;

            _dispenseAmount = (int) castState.SelectedDispenseAmount;

            UpdateContainerInfo(castState);
            UpdateReagentsList(castState.Inventory);

            _entityManager.TryGetEntity(castState.OutputContainerEntity, out var outputContainerEnt);
            View.SetEntity(outputContainerEnt);

            // Disable the Clear & Eject button if no beaker
            ClearButton.Disabled = castState.OutputContainer is null;
            EjectButton.Disabled = castState.OutputContainer is null;

            AmountGrid.Selected = _dispenseAmount.ToString();
        }

        private Dictionary<string, FixedPoint2> _held = new();

        private void RefreshRecipes()
        {
            var key = (_showFieldKit ? "K|" : "C|")
                      + (_target?.ID ?? string.Empty) + "|"
                      + string.Join('|', _held.OrderBy(x => x.Key).Select(x => $"{x.Key}:{x.Value}"));

            if (key == _recipeKey)
                return;

            _recipeKey = key;

            FieldKitTabButton.Pressed = _showFieldKit;
            CanMakeTabButton.Pressed = !_showFieldKit;

            if (_showFieldKit)
                PopulateFieldKit();
            else
                FSRecipeHints.Populate(RecipeInfo, _prototypeManager, _held);
        }

        private void PopulateFieldKit()
        {
            RecipeInfo.Children.Clear();

            var sourceable = new HashSet<string>();
            foreach (var card in _cards.Values)
            {
                if (card.ReagentId != null)
                    sourceable.Add(card.ReagentId);
            }

            var kits = _prototypeManager.EnumeratePrototypes<FSFieldKitPrototype>()
                .OrderBy(kit => kit.Priority)
                .ToArray();

            foreach (var kit in kits)
                RecipeInfo.AddChild(BuildFieldKitRow(kit, sourceable));
        }

        private Control BuildFieldKitRow(FSFieldKitPrototype kit, IReadOnlySet<string> sourceable)
        {
            var ingredients = kit.ResolveIngredients(_prototypeManager);

            var complete = true;
            var missingSupply = false;
            var parts = new List<string>();

            foreach (var (id, need) in ingredients)
            {
                var have = _held.GetValueOrDefault(id, FixedPoint2.Zero);
                if (have < need)
                    complete = false;

                if (!sourceable.Contains(id))
                    missingSupply = true;

                var reagentName = _prototypeManager.TryIndex(id, out ReagentPrototype? proto)
                    ? proto.LocalizedName
                    : id;

                parts.Add($"{reagentName} " + Loc.GetString("reagent-dispenser-window-field-kit-progress",
                    ("have", have), ("need", need)));
            }

            var targeted = _target?.ID == kit.ID;

            var heading = new BoxContainer { Orientation = LayoutOrientation.Horizontal, HorizontalExpand = true };
            heading.AddChild(new Label
            {
                Text = Loc.GetString(kit.Name),
                Modulate = complete ? ReadyColor : Color.White,
            });
            heading.AddChild(new Control { HorizontalExpand = true });
            heading.AddChild(new Label
            {
                Text = missingSupply
                    ? Loc.GetString("reagent-dispenser-window-field-kit-missing")
                    : string.Join(" · ", parts),
                StyleClasses = { StyleClass.LabelSubText },
                Modulate = complete ? ReadyColor : Color.White,
            });

            var body = new BoxContainer { Orientation = LayoutOrientation.Vertical, HorizontalExpand = true };
            body.AddChild(heading);
            body.AddChild(new Label
            {
                Text = Loc.GetString(kit.Purpose),
                StyleClasses = { StyleClass.LabelSubText },
            });

            if (targeted)
            {
                body.AddChild(new Label
                {
                    Text = Loc.GetString(kit.Delivery),
                    StyleClasses = { StyleClass.LabelSubText },
                    Modulate = ReadyColor,
                });
            }

            var button = new Button
            {
                StyleClasses = { StyleClass.ButtonSquare },
                HorizontalExpand = true,
                Pressed = targeted,
                ToggleMode = true,
                Modulate = missingSupply ? new Color(1f, 1f, 1f, 0.55f) : Color.White,
            };
            button.AddChild(body);
            button.OnPressed += _ => SetTarget(kit);

            return button;
        }

        public void UpdateContainerInfo(ReagentDispenserBoundUserInterfaceState state)
        {
            ContainerInfo.Children.Clear();
            _held = new Dictionary<string, FixedPoint2>();

            if (state.OutputContainer is null)
            {
                ContainerInfoName.Text = "";
                ContainerInfoFill.Text = "";
                ContainerFillBar.Value = 0f;
                ContainerInfo.Children.Add(new Label { Text = Loc.GetString("reagent-dispenser-window-no-container-loaded-text") });
                RefreshRecipes();
                return;
            }

            // Set Name of the container and its fill status (Ex: 44/100u)
            ContainerInfoName.Text = state.OutputContainer.DisplayName;
            ContainerInfoFill.Text = Loc.GetString("reagent-dispenser-window-fill-label",
                ("current", state.OutputContainer.CurrentVolume),
                ("max", state.OutputContainer.MaxVolume));
            ContainerFillBar.Value = state.OutputContainer.MaxVolume <= 0
                ? 0f
                : Math.Clamp(state.OutputContainer.CurrentVolume.Float() / state.OutputContainer.MaxVolume.Float(), 0f, 1f);

            foreach (var (reagent, quantity) in state.OutputContainer.Reagents!)
            {
                _held[reagent.Prototype] = quantity;

                // Try get to the prototype for the given reagent. This gives us its name.
                var found = _prototypeManager.TryIndex(reagent.Prototype, out ReagentPrototype? p);
                var localizedName = found
                    ? p!.LocalizedName
                    : Loc.GetString("reagent-dispenser-window-reagent-name-not-found-text");

                var swatch = new PanelContainer
                {
                    VerticalExpand = true,
                    MinWidth = 4,
                    Margin = new Thickness(0, 1, 4, 1),
                    PanelOverride = new StyleBoxFlat { BackgroundColor = found ? p!.SubstanceColor : Color.White },
                };

                var nameLabel = new Label { Text = $"{localizedName}: " };
                var quantityLabel = new Label
                {
                    Text = Loc.GetString("reagent-dispenser-window-quantity-label-text", ("quantity", quantity)),
                    StyleClasses = { StyleClass.LabelWeak },
                };

                ContainerInfo.Children.Add(new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    Children =
                    {
                        swatch,
                        nameLabel,
                        quantityLabel,
                    }
                });
            }

            RefreshRecipes();
        }
    }
}
