using System.Linq;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._FinalStand.MedicalOps;
using Content.Shared.Chemistry;
using Content.Shared.Chemistry.Reaction;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.FixedPoint;
using Content.Shared.Storage;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client.Chemistry.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class ReagentDispenserWindow : FancyWindow
    {
        [Dependency] private IPrototypeManager _prototypeManager = default!;
        [Dependency] private IEntityManager _entityManager = default!;
        public event Action<ItemStorageLocation>? OnDispenseReagentButtonPressed;
        public event Action<ItemStorageLocation>? OnEjectJugButtonPressed;

        private static readonly Color ReadyColor = Color.FromHex("#4FBF7A");
        private static readonly Color BlockedColor = Color.FromHex("#C9A227");

        private readonly Dictionary<ItemStorageLocation, ReagentCardControl> _cards = new();
        private readonly List<ItemStorageLocation> _displayed = new();
        private List<ReagentInventoryItem> _inventory = new();

        private FSFieldKitPrototype? _target;
        private Dictionary<string, FixedPoint2> _targetIngredients = new();
        private RecipeTab _tab = RecipeTab.FieldKit;
        private string _filter = string.Empty;
        private string? _recipeKey;
        private int _dispenseAmount;

        public ReagentDispenserWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            FilterEdit.OnTextChanged += args =>
            {
                _filter = args.Text.Trim();
                ClearTarget(false);
                ApplyFilter();
            };

            TargetChipButton.OnPressed += _ => ClearTarget(true);

            FieldKitTabButton.OnPressed += _ => SetRecipeTab(RecipeTab.FieldKit);
            BasicsTabButton.OnPressed += _ => SetRecipeTab(RecipeTab.Basics);
            CanMakeTabButton.OnPressed += _ => SetRecipeTab(RecipeTab.CanMake);
        }

        private enum RecipeTab : byte
        {
            FieldKit,
            Basics,
            CanMake,
        }

        private void SetRecipeTab(RecipeTab tab)
        {
            if (_tab == tab)
            {
                SyncTabButtons();
                return;
            }

            _tab = tab;
            _recipeKey = null;
            RefreshRecipes();
        }

        private void SyncTabButtons()
        {
            FieldKitTabButton.Pressed = _tab == RecipeTab.FieldKit;
            BasicsTabButton.Pressed = _tab == RecipeTab.Basics;
            CanMakeTabButton.Pressed = _tab == RecipeTab.CanMake;
        }

        private void ClearTarget(bool refresh)
        {
            if (_target == null)
                return;

            _target = null;
            _targetIngredients = new Dictionary<string, FixedPoint2>();
            TargetChipButton.Visible = false;
            _recipeKey = null;

            if (!refresh)
                return;

            ApplyFilter();
            RefreshRecipes();
        }

        private HashSet<string> Sourceable(FSFieldKitPrototype? kit = null)
        {
            var sourceable = new HashSet<string>();
            foreach (var card in _cards.Values)
            {
                if (card.ReagentId != null)
                    sourceable.Add(card.ReagentId);
            }

            if (kit != null)
            {
                foreach (var carried in kit.Carried)
                    sourceable.Add(carried);
            }

            return sourceable;
        }

        private void SetTarget(FSFieldKitPrototype kit)
        {
            if (_target?.ID == kit.ID)
            {
                ClearTarget(true);
                return;
            }

            _target = kit;
            _targetIngredients = FSFieldKitResolver
                .Plan(_prototypeManager, kit.ResolveIngredients(_prototypeManager), Sourceable(kit))
                .Base;
            _filter = string.Empty;
            FilterEdit.Text = string.Empty;
            TargetChipButton.Text = Loc.GetString("reagent-dispenser-window-target-clear",
                ("recipe", Loc.GetString(kit.Name)));
            TargetChipButton.Visible = true;
            _recipeKey = null;

            ApplyFilter();
            RefreshRecipes();
        }

        public void UpdateReagentsList(List<ReagentInventoryItem> inventory)
        {
            if (ReagentList == null)
                return;

            inventory.Sort((x, y) => x.ReagentLabel.CompareTo(y.ReagentLabel));
            _inventory = inventory;

            var seen = new HashSet<ItemStorageLocation>();

            foreach (var item in inventory)
            {
                seen.Add(item.StorageLocation);

                if (_cards.TryGetValue(item.StorageLocation, out var existing))
                {
                    existing.Update(item);
                    continue;
                }

                var card = new ReagentCardControl(item);
                card.OnPressed += loc => OnDispenseReagentButtonPressed?.Invoke(loc);
                card.OnEjectButtonPressed += loc => OnEjectJugButtonPressed?.Invoke(loc);
                _cards[item.StorageLocation] = card;
            }

            foreach (var stale in _cards.Keys.Where(key => !seen.Contains(key)).ToArray())
            {
                _cards[stale].Dispose();
                _cards.Remove(stale);
            }

            ApplyFilter();
        }

        private bool Matches(ReagentCardControl card)
        {
            if (_target != null)
                return card.ReagentId != null && _targetIngredients.ContainsKey(card.ReagentId);

            return _filter.Length == 0
                   || card.ReagentLabel.Contains(_filter, StringComparison.OrdinalIgnoreCase);
        }

        private void ApplyFilter()
        {
            var wanted = new List<ItemStorageLocation>();

            foreach (var item in _inventory)
            {
                if (!_cards.TryGetValue(item.StorageLocation, out var card))
                    continue;

                card.SetDispenseAmount(_dispenseAmount);

                if (Matches(card))
                    wanted.Add(item.StorageLocation);
            }

            NoMatchLabel.Visible = wanted.Count == 0 && _inventory.Count > 0;

            if (wanted.SequenceEqual(_displayed))
                return;

            _displayed.Clear();
            _displayed.AddRange(wanted);

            ReagentList.Children.Clear();
            foreach (var location in wanted)
                ReagentList.AddChild(_cards[location]);
        }

        public void UpdateState(BoundUserInterfaceState state)
        {
            var castState = (ReagentDispenserBoundUserInterfaceState) state;

            _dispenseAmount = (int) castState.SelectedDispenseAmount;

            UpdateContainerInfo(castState);
            UpdateReagentsList(castState.Inventory);
            RefreshRecipes();

            _entityManager.TryGetEntity(castState.OutputContainerEntity, out var outputContainerEnt);
            View.SetEntity(outputContainerEnt);

            ClearButton.Disabled = castState.OutputContainer is null;
            EjectButton.Disabled = castState.OutputContainer is null;

            AmountGrid.Selected = _dispenseAmount.ToString();
        }

        private Dictionary<string, FixedPoint2> _held = new();

        private void RefreshRecipes()
        {
            var key = _tab + "|"
                      + (_target?.ID ?? string.Empty) + "|"
                      + string.Join(',', Sourceable().OrderBy(x => x)) + "|"
                      + string.Join('|', _held.OrderBy(x => x.Key).Select(x => $"{x.Key}:{x.Value}"));

            if (key == _recipeKey)
                return;

            _recipeKey = key;

            SyncTabButtons();

            if (_tab == RecipeTab.FieldKit)
                PopulateFieldKit();
            else if (_tab == RecipeTab.Basics)
                PopulateBasics();
            else
                FSRecipeHints.Populate(RecipeInfo, _prototypeManager, _held);
        }

        private void PopulateFieldKit()
        {
            RecipeInfo.Children.Clear();

            var kits = _prototypeManager.EnumeratePrototypes<FSFieldKitPrototype>()
                .Select(kit => (Kit: kit, Plan: FSFieldKitResolver.Plan(
                    _prototypeManager, kit.ResolveIngredients(_prototypeManager), Sourceable(kit))))
                .OrderBy(entry => entry.Plan.Unobtainable.Count > 0)
                .ThenBy(entry => entry.Kit.Priority);

            foreach (var (kit, plan) in kits)
                RecipeInfo.AddChild(BuildFieldKitRow(kit, plan));
        }

        private void PopulateBasics()
        {
            RecipeInfo.Children.Clear();

            var groups = _prototypeManager.EnumeratePrototypes<FSChemGuidePrototype>()
                .OrderBy(guide => guide.Priority);

            var any = false;
            foreach (var guide in groups)
            {
                RecipeInfo.AddChild(new Label
                {
                    Text = Loc.GetString(guide.Category),
                    StyleClasses = { StyleClass.LabelSubText },
                    Margin = new Thickness(0, any ? 6 : 0, 0, 2),
                });

                foreach (var id in guide.Reactions)
                {
                    if (!_prototypeManager.TryIndex(id, out ReactionPrototype? reaction))
                        continue;

                    any = true;
                    RecipeInfo.AddChild(BuildGuideRow(reaction));
                }
            }

            if (!any)
                RecipeInfo.AddChild(Sub(Loc.GetString("reagent-dispenser-window-guide-empty")));
        }

        private Control BuildGuideRow(ReactionPrototype reaction)
        {
            var parts = reaction.Reactants
                .OrderBy(kv => kv.Key)
                .Select(kv => ReagentName(kv.Key) + " " + kv.Value.Amount + "u");

            var ready = reaction.Reactants.All(kv =>
                _held.GetValueOrDefault(kv.Key, FixedPoint2.Zero) >= kv.Value.Amount);

            var row = new BoxContainer { Orientation = LayoutOrientation.Vertical, HorizontalExpand = true };
            row.AddChild(new Label
            {
                Text = FSFieldKitResolver.NameOf(reaction, _prototypeManager),
                Modulate = ready ? ReadyColor : Color.White,
            });
            row.AddChild(Sub(Loc.GetString("reagent-dispenser-window-guide-line",
                ("reagents", string.Join(" + ", parts))), ready ? ReadyColor : null));

            if (reaction.MinimumTemperature > 0f)
            {
                row.AddChild(Sub(Loc.GetString("reagent-dispenser-window-guide-heat",
                    ("temp", (int) reaction.MinimumTemperature)), BlockedColor));
            }

            return row;
        }

        private const int RecipeTextWidth = 250;

        private static RichTextLabel Sub(string text, Color? modulate = null)
        {
            var label = new RichTextLabel { MaxWidth = RecipeTextWidth };
            label.SetMessage(text, modulate ?? Color.FromHex("#9BA3AE"));
            return label;
        }

        private string ReagentName(string id)
        {
            return _prototypeManager.TryIndex(id, out ReagentPrototype? proto) ? proto.LocalizedName : id;
        }

        private const string BiomassReagent = "FSBiomass";

        private Control BuildFieldKitRow(FSFieldKitPrototype kit, FSFieldKitPlan plan)
        {
            var direct = kit.ResolveIngredients(_prototypeManager);

            var complete = direct.All(kv => _held.GetValueOrDefault(kv.Key, FixedPoint2.Zero) >= kv.Value);
            var blocked = plan.Unobtainable.Count > 0;

            var needsBiomass = !complete
                               && direct.TryGetValue(BiomassReagent, out var biomassNeed)
                               && _held.GetValueOrDefault(BiomassReagent, FixedPoint2.Zero) < biomassNeed;
            var targeted = _target?.ID == kit.ID;

            var body = new BoxContainer { Orientation = LayoutOrientation.Vertical, HorizontalExpand = true };

            var header = new BoxContainer { Orientation = LayoutOrientation.Horizontal, HorizontalExpand = true };
            header.AddChild(new Label
            {
                Text = Loc.GetString(kit.Name),
                Modulate = complete ? ReadyColor : Color.White,
            });
            header.AddChild(new Control { HorizontalExpand = true });
            header.AddChild(new Label
            {
                Text = StatusText(),
                StyleClasses = { StyleClass.LabelSubText },
                Modulate = complete ? ReadyColor : blocked ? BlockedColor : Color.White,
            });
            body.AddChild(header);

            if (needsBiomass && !blocked)
                body.AddChild(Sub(Loc.GetString("reagent-dispenser-window-field-kit-harvest"), BlockedColor));

            string StatusText()
            {
                if (complete)
                    return Loc.GetString("reagent-dispenser-window-field-kit-ready");

                if (blocked)
                {
                    return Loc.GetString(kit.Research
                        ? "reagent-dispenser-window-field-kit-research"
                        : "reagent-dispenser-window-field-kit-needs",
                        ("reagents", string.Join(", ", plan.Unobtainable.Select(ReagentName))));
                }

                var have = direct.Count(kv => _held.GetValueOrDefault(kv.Key, FixedPoint2.Zero) >= kv.Value);
                return Loc.GetString("reagent-dispenser-window-field-kit-progress",
                    ("have", have), ("need", direct.Count));
            }

            if (targeted)
            {
                body.AddChild(Sub(Loc.GetString(kit.Purpose)));

                body.AddChild(Sub(string.Join(" · ", direct
                    .Select(kv => ReagentName(kv.Key) + " " + Loc.GetString(
                        "reagent-dispenser-window-field-kit-progress",
                        ("have", _held.GetValueOrDefault(kv.Key, FixedPoint2.Zero)), ("need", kv.Value))))));

                if (plan.Base.Count > 0)
                {
                    body.AddChild(Sub(Loc.GetString("reagent-dispenser-window-field-kit-base",
                        ("reagents", string.Join(" · ", plan.Base
                            .OrderBy(kv => kv.Key)
                            .Select(kv => $"{ReagentName(kv.Key)} {kv.Value}u"))))));
                }

                if (plan.Steps.Count > 0)
                {
                    var steps = plan.Steps
                        .Select((reaction, i) => $"{i + 1}. {FSFieldKitResolver.NameOf(reaction, _prototypeManager)}");

                    body.AddChild(Sub(Loc.GetString("reagent-dispenser-window-field-kit-steps",
                        ("steps", string.Join("  ", steps)))));
                }

                if (blocked)
                {
                    body.AddChild(Sub(Loc.GetString(kit.Research
                        ? "reagent-dispenser-window-field-kit-blocked-research"
                        : "reagent-dispenser-window-field-kit-blocked",
                        ("reagents", string.Join(", ", plan.Unobtainable.Select(ReagentName)))),
                        BlockedColor));
                }

                body.AddChild(Sub(Loc.GetString(kit.Delivery), ReadyColor));
            }

            var button = new Button
            {
                StyleClasses = { StyleClass.ButtonSquare },
                HorizontalExpand = true,
                Pressed = targeted,
                ToggleMode = true,
                Modulate = blocked ? new Color(1f, 1f, 1f, 0.55f) : Color.White,
            };
            button.AddChild(body);
            button.OnPressed += _ => SetTarget(kit);

            return button;
        }

        public void UpdateContainerInfo(ReagentDispenserBoundUserInterfaceState state)
        {
            ContainerInfo.Children.Clear();
            _held = new Dictionary<string, FixedPoint2>();

            if (state.OutputContainer is null)
            {
                ContainerInfoName.Text = "";
                ContainerInfoFill.Text = "";
                ContainerFillBar.Value = 0f;
                ContainerInfo.Children.Add(new Label { Text = Loc.GetString("reagent-dispenser-window-no-container-loaded-text") });
                RefreshRecipes();
                return;
            }

            ContainerInfoName.Text = state.OutputContainer.DisplayName;
            ContainerInfoFill.Text = Loc.GetString("reagent-dispenser-window-fill-label",
                ("current", state.OutputContainer.CurrentVolume),
                ("max", state.OutputContainer.MaxVolume));
            ContainerFillBar.Value = state.OutputContainer.MaxVolume <= 0
                ? 0f
                : Math.Clamp(state.OutputContainer.CurrentVolume.Float() / state.OutputContainer.MaxVolume.Float(), 0f, 1f);

            foreach (var (reagent, quantity) in state.OutputContainer.Reagents!)
            {
                _held[reagent.Prototype] = quantity;

                var found = _prototypeManager.TryIndex(reagent.Prototype, out ReagentPrototype? p);
                var localizedName = found
                    ? p!.LocalizedName
                    : Loc.GetString("reagent-dispenser-window-reagent-name-not-found-text");

                var swatch = new PanelContainer
                {
                    VerticalExpand = true,
                    MinWidth = 4,
                    Margin = new Thickness(0, 1, 4, 1),
                    PanelOverride = new StyleBoxFlat { BackgroundColor = found ? p!.SubstanceColor : Color.White },
                };

                var nameLabel = new Label { Text = $"{localizedName}: " };
                var quantityLabel = new Label
                {
                    Text = Loc.GetString("reagent-dispenser-window-quantity-label-text", ("quantity", quantity)),
                    StyleClasses = { StyleClass.LabelWeak },
                };

                ContainerInfo.Children.Add(new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    Children =
                    {
                        swatch,
                        nameLabel,
                        quantityLabel,
                    }
                });
            }

            RefreshRecipes();
        }
    }
}
