using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Client._FinalStand.Stylesheets;
using Content.Shared._FinalStand.Research.Components;
using Content.Shared._FinalStand.Research.Prototypes;
using Content.Shared.Research.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._FinalStand.Research.UI;

// HOI4-national-focus-style layout: tier flows top-down (row = tier), siblings spread
// horizontally, parent->child edges are orthogonal "elbow" connectors, and each node is an
// icon tile with a name plate underneath instead of a circle. Column position within a row is
// chosen by a single-pass barycenter of each node's prerequisite X positions (already-placed
// parent tiers), falling back to discipline grouping for roots — enough to keep branches visually
// coherent without a full graph-layout solver. Mouse wheel zooms (intercepted here so the parent
// ScrollContainer doesn't also scroll on the same gesture).
[GenerateTypedNameReferences]
public sealed partial class FSResearchNodeGraphControl : BoxContainer
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPrototypeManager _prototype = default!;
    [Dependency] private IResourceCache _resourceCache = default!;

    private readonly FSResearchClientSystem _fsResearch;
    private readonly SpriteSystem _sprite;
    private readonly FontResource _fontResource;
    private readonly Texture _discTexture;
    private readonly Texture _ringTexture;
    private readonly Texture _glowTexture;
    private readonly Texture _plateBgTexture;
    private readonly Texture _plateRingTexture;
    private readonly Texture _plateGlowTexture;
    private readonly Texture _exclusiveMarkerTexture;
    private readonly Texture _blueprintTexture;
    private Font _font;

    private EntityUid? _console;
    private FSResearchNodeView? _hoveredTech;
    private string _filter = "";
    private string? _disciplineFilter;
    private float _zoom = DefaultZoom;
    private int _pendingLockFrames;

    // What the current layout was built for; a mismatch is what forces a real relayout.
    private string? _layoutDiscipline;
    private float _layoutZoom = -1f;

    private ScrollContainer? _scrollContainer;
    private bool _leftDown;
    private bool _dragging;
    private Vector2 _dragStartCursor;
    private float _dragStartVScroll;
    private float _dragStartHScroll;
    private const float DragThreshold = 4f;

    private List<FSResearchNodeView> _nodes = new();
    private Dictionary<string, Vector2> _positions = new();

    // Built with the layout, not per frame.
    private Dictionary<string, FSResearchNodeView> _nodeById = new();
    private Dictionary<string, List<FSResearchNodeView>> _childrenByParent = new();
    private List<List<FSResearchNodeView>> _exclusiveGroups = new();

    public event Action<FSResearchNodeView>? OnNodeSelected;

    private const float MinZoom = 0.15f;
    private const float MaxZoom = 2f;
    // Reset View / initial open lands here, not zoom 1 - the tree is wide enough now (six weapon
    // branches with generous gutters) that zoom 1 only ever shows a fragment of the nearest one.
    private const float DefaultZoom = 0.4f;
    private const float BaseFontSize = 16f;
    private const int PlateMaxChars = 20;

    private float IconSize => 96 * UIScale * _zoom;
    private float IconBorderThickness => 6 * UIScale * _zoom;
    // wide enough for PlateMaxChars at this font before the plate itself has to grow past it
    private float PlateWidth => 300 * UIScale * _zoom;
    private float MinPlateWidth => IconSize;
    // Single line only (see TruncateForPlate) - a plate sized for 2 lines but showing 1 looked
    // tall and unbalanced, which was the actual "boxes look uneven" complaint, not a padding
    // issue. Sized from the font's real metrics, not a guessed constant, so it always exactly
    // fits one line + real breathing room (not just enough to avoid clipping).
    private float PlateHeight => _font.GetLineHeight(1) + 17 * UIScale * _zoom;
    private float PlateGap => 7 * UIScale * _zoom;
    private float NodeHeight => IconSize + PlateGap + PlateHeight;
    private float ColumnSpacing => PlateWidth + 48 * UIScale * _zoom;
    private float RowSpacing => NodeHeight + 92 * UIScale * _zoom;
    // Floored, not just ColumnSpacing / 2 - the font has a hard minimum size (see Rebuild's
    // VectorFont clamp to 8px) so a plate's rendered text width stops shrinking once zoomed out
    // past that floor, while ColumnSpacing/Padding kept shrinking with zoom regardless. Past that
    // point a wide plate's left half could extend beyond x=0, which is also the ScrollContainer's
    // scroll-left limit - there's no further left to drag to, so it just looked permanently cut
    // off. The floor guarantees enough margin at every zoom level for the widest realistic plate.
    // PanMargin is a separate, generous, zoom-independent allowance on top of the clip-prevention
    // floor above - the floor only guarantees content isn't cut off, it doesn't leave any room to
    // actually drag a branch away from the edge toward the center of your view. This is that room,
    // on every side (it feeds MinHeight's existing Padding*2 top+bottom margin, and MinWidth below
    // adds a matching trailing Padding so left/right are symmetric too).
    private const float PanMargin = 500f;
    private float Padding => Math.Max(ColumnSpacing / 2f, 180 * UIScale) + PanMargin * UIScale;
    // extra gap between branch/discipline lanes AND between disconnected sub-trees within the same
    // branch (e.g. the L6-SAW+Minigun cluster vs. the Hydra+RPG-7 cluster vs. the X-Ray+Tesla
    // cluster, all technically "Ordnance" but with zero edges between them) - this is what actually
    // reads as "separate branches" instead of one undifferentiated grid (see HOI4-style swim lanes)
    private float GroupGutter => ColumnSpacing * 2.5f;

    public Color LockedNodeColor { get; set; } = FSUiPalette.BorderNeutral;
    public Color AvailableNodeColor { get; set; } = FSUiPalette.TextPrimary;
    public Color UnlockedNodeColor { get; set; } = FSUiPalette.StatePending;
    public Color HoverGlowColor { get; set; } = FSUiPalette.TextPrimary;
    public Color PlateBackgroundColor { get; set; } = FSUiPalette.BgSurface;

    public FSResearchNodeGraphControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _fsResearch = _entityManager.System<FSResearchClientSystem>();
        _sprite = _entityManager.System<SpriteSystem>();

        _fontResource = _resourceCache.GetResource<FontResource>("/EngineFonts/NotoSans/NotoSansMono-Regular.ttf");
        _font = new VectorFont(_fontResource, (int)Math.Round(BaseFontSize));

        _discTexture = _resourceCache.GetResource<TextureResource>("/Textures/_FinalStand/Interface/Research/node_disc.png").Texture;
        _ringTexture = _resourceCache.GetResource<TextureResource>("/Textures/_FinalStand/Interface/Research/node_ring.png").Texture;
        _glowTexture = _resourceCache.GetResource<TextureResource>("/Textures/_FinalStand/Interface/Research/node_glow.png").Texture;
        _plateBgTexture = _resourceCache.GetResource<TextureResource>("/Textures/_FinalStand/Interface/Research/plate_bg.png").Texture;
        _plateRingTexture = _resourceCache.GetResource<TextureResource>("/Textures/_FinalStand/Interface/Research/plate_ring.png").Texture;
        _plateGlowTexture = _resourceCache.GetResource<TextureResource>("/Textures/_FinalStand/Interface/Research/plate_glow.png").Texture;
        _exclusiveMarkerTexture = _resourceCache.GetResource<TextureResource>("/Textures/_FinalStand/Interface/Research/exclusive_marker.png").Texture;
        _blueprintTexture = _resourceCache.GetResource<TextureResource>("/Textures/_FinalStand/Interface/Research/blueprint_bg.png").Texture;
    }

    public void SetConsole(EntityUid? console)
    {
        // SetConsole is also called on every BUI state refresh (UpdatePanels), not just the
        // initial open - only snap the view to content when the console actually changes, or
        // every points/unlock update would yank the player's scroll position back to the start.
        var isNewConsole = _console != console;
        _console = console;
        if (isNewConsole)
            _zoom = DefaultZoom;

        // Positions depend only on the page and the zoom; points and progress move nothing.
        if (isNewConsole || !LayoutIsCurrent())
            Rebuild();
        else
            RefreshNodeStates();

        if (isNewConsole)
            LockToFirstNode();
    }

    // A prototype reload can change which nodes exist without touching zoom or the filter.
    public void InvalidateLayout()
    {
        _layoutZoom = -1f;
    }

    private bool LayoutIsCurrent()
    {
        return _nodes.Count > 0
               && _layoutDiscipline == _disciplineFilter
               && MathHelper.CloseToPercent(_layoutZoom, _zoom);
    }

    public FSResearchNodeView? GetNode(string id) => _nodes.FirstOrDefault(n => n.Id == id);

    public void SetFilter(string filter)
    {
        _filter = filter.Trim();
    }

    public void SetDisciplineFilter(string? discipline)
    {
        if (_disciplineFilter == discipline)
            return;
        _disciplineFilter = discipline;
        _zoom = DefaultZoom;
        Rebuild();
        LockToFirstNode();
    }

    public void SetScrollContainer(ScrollContainer scrollContainer)
    {
        _scrollContainer = scrollContainer;
    }

    public void ResetView()
    {
        _zoom = DefaultZoom;
        Rebuild();
        LockToFirstNode();
    }

    // Centers the view on the first node of the first branch (the node with the smallest Y then
    // smallest X - by construction that's always wherever layout started, i.e. the top-left-most
    // real node, not just an arbitrary corner offset). Deferred a few frames rather than applied
    // immediately: ScrollContainer clamps HScroll/VScroll against its OWN internal MaxValue, which
    // is only refreshed during its next Arrange pass. Setting scroll synchronously right after
    // Rebuild changes this control's MinWidth/MinHeight gets silently clamped back to 0 against the
    // scrollbar's still-stale range, which is why the view looked like it was landing nowhere.
    private void LockToFirstNode()
    {
        _pendingLockFrames = 3;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_pendingLockFrames <= 0)
            return;

        _pendingLockFrames--;
        if (_pendingLockFrames > 0 || _scrollContainer == null || _positions.Count == 0)
            return;

        var first = _positions.Values
            .OrderBy(p => p.Y)
            .ThenBy(p => p.X)
            .First();

        var viewport = _scrollContainer.Size;
        var targetX = Math.Max(0f, first.X / UIScale - viewport.X / 2f);
        var targetY = Math.Max(0f, first.Y / UIScale - viewport.Y / 2f);
        _scrollContainer.HScroll = targetX;
        _scrollContainer.VScroll = targetY;
    }

    private void Rebuild()
    {
        _font = new VectorFont(_fontResource, Math.Clamp((int)Math.Round(BaseFontSize * _zoom), 8, 30));

        _nodes = new List<FSResearchNodeView>();
        _positions = new Dictionary<string, Vector2>();
        _nodeById = new Dictionary<string, FSResearchNodeView>();
        _childrenByParent = new Dictionary<string, List<FSResearchNodeView>>();
        _exclusiveGroups = new List<List<FSResearchNodeView>>();

        if (_console is not { } console ||
            !_entityManager.TryGetComponent<TechnologyDatabaseComponent>(console, out var database))
        {
            MinWidth = 0;
            MinHeight = 0;
            _layoutZoom = -1f;
            return;
        }

        var rows = _prototype.EnumeratePrototypes<FSTechBranchPrototype>().Select(b => b.ID).ToList();
        var nodes = new List<FSResearchNodeView>();

        foreach (var fsTech in _prototype.EnumeratePrototypes<FSTechNodePrototype>())
        {
            if (fsTech.Hidden)
                continue;

            var view = new FSResearchNodeView
            {
                Id = fsTech.ID,
                Name = fsTech.Name,
                Icon = fsTech.Icon,
                GroupId = fsTech.Branch.Id,
                Tier = fsTech.Tier,
                Cost = fsTech.Cost,
                Prerequisites = fsTech.Prerequisites,
                PrerequisiteGroups = fsTech.PrerequisiteGroups,
                State = FSResearchNodeState.Locked,
                FsNode = fsTech,
            };
            view.BuildPrerequisiteIndex();
            nodes.Add(view);
        }

        // Discipline tabs are separate pages, not a dimming filter - only one page's worth of
        // nodes is laid out/rendered at a time, so a page gets the whole canvas instead of
        // sharing space with everything else.
        if (_disciplineFilter != null)
            nodes = nodes.Where(n => n.GroupId == _disciplineFilter).ToList();

        if (rows.Count == 0 || nodes.Count == 0)
        {
            MinWidth = 0;
            MinHeight = 0;
            _layoutZoom = -1f;
            return;
        }

        _nodes = nodes;

        // "strays" - nodes with no edge at all (not a prerequisite for anything, and have none
        // themselves) - get grouped in their own block to the right instead of scattered inline
        var nodeIds = nodes.Select(t => t.Id).ToHashSet();
        var edgeNodeIds = new HashSet<string>();
        foreach (var node in nodes)
        {
            foreach (var prereqId in node.AllPrerequisiteIds)
            {
                if (!nodeIds.Contains(prereqId))
                    continue;
                edgeNodeIds.Add(node.Id);
                edgeNodeIds.Add(prereqId);
            }
        }

        var connected = nodes.Where(t => edgeNodeIds.Contains(t.Id)).ToList();
        var strays = nodes.Where(t => !edgeNodeIds.Contains(t.Id))
            .OrderBy(t => rows.IndexOf(t.GroupId))
            .ThenBy(t => t.Id, StringComparer.Ordinal)
            .ToList();

        // Tier -> row is global (a Tier 2 node lines up with every other branch's Tier 2 row,
        // since tier is a meaningful cross-branch concept - wave-gating in particular), but X is
        // NOT: each branch/discipline gets its own horizontal lane, sized to its own widest tier,
        // with a fixed gutter between lanes (HOI4-style swim lanes). Mixing every group into one
        // shared set of tier-wide columns was what made unrelated branches visually crisscross -
        // a node's column index had no consistent meaning from one tier to the next.
        var allTiers = connected.Select(n => n.Tier).Distinct().OrderBy(t => t).ToList();
        var yByTier = new Dictionary<int, float>();
        for (var i = 0; i < allTiers.Count; i++)
            yByTier[allTiers[i]] = Padding + i * RowSpacing;
        var rowCount = Math.Max(allTiers.Count, 1);

        var groupsPresent = rows.Where(g => connected.Any(n => n.GroupId == g)).ToList();
        var groupCursorX = Padding;
        var xByNode = new Dictionary<string, float>();

        foreach (var group in groupsPresent)
        {
            var groupNodes = connected.Where(n => n.GroupId == group).ToList();

            // A branch/discipline can itself contain multiple disconnected sub-trees (e.g.
            // Ordnance's L6-SAW+Minigun cluster vs. Hydra+RPG-7 cluster vs. X-Ray+Tesla cluster -
            // three real weapon families with zero edges between them, all under the same
            // "Ordnance" GroupId). Laying the whole group out as one shared column grid is what
            // made unrelated weapon trees visually bleed into each other. Each connected component
            // gets its own lane with the same gutter used between branches.
            var components = GroupIntoComponents(groupNodes)
                .OrderBy(c => c.Min(n => n.Tier))
                .ThenBy(c => c.Select(n => n.Id).OrderBy(id => id, StringComparer.Ordinal).First())
                .ToList();

            foreach (var component in components)
            {
                var placedX = new Dictionary<string, float>();
                var componentEndX = groupCursorX;
                var nextFreeX = groupCursorX;

                var tierGroups = component.GroupBy(t => t.Tier).OrderBy(g => g.Key).ToList();

                // Pass 1 (top-down): place each node at the barycenter of its already-placed
                // parents, then resolve left-to-right collisions so nothing sits closer than one
                // column width. Real gaps between unrelated parent families (different barycenters,
                // e.g. two different weapon sub-trees off a shared trunk) are preserved instead of
                // being compressed to a uniform slot width - that compression was what made every
                // branch look like one continuous web regardless of how unrelated the nodes
                // actually were, and made mutually-exclusive siblings land arbitrarily far apart.
                foreach (var tierGroup in tierGroups)
                {
                    var idealX = new Dictionary<string, float>();
                    var roots = new List<FSResearchNodeView>();
                    foreach (var node in tierGroup)
                    {
                        var parentXs = node.AllPrerequisiteIds.Where(placedX.ContainsKey).Select(id => placedX[id]).ToList();
                        if (parentXs.Count > 0)
                            idealX[node.Id] = parentXs.Average();
                        else
                            roots.Add(node);
                    }

                    // nodes with no placed parent in this component (roots) get fresh sequential
                    // slots to seed the rest of the tree from
                    foreach (var node in roots.OrderBy(n => n.Id, StringComparer.Ordinal))
                    {
                        idealX[node.Id] = nextFreeX;
                        nextFreeX += ColumnSpacing;
                    }

                    var ordered = tierGroup.OrderBy(n => idealX[n.Id]).ThenBy(n => n.Id, StringComparer.Ordinal).ToList();
                    float? prevX = null;
                    foreach (var node in ordered)
                    {
                        var x = idealX[node.Id];
                        if (prevX is { } p && x < p + ColumnSpacing)
                            x = p + ColumnSpacing;
                        placedX[node.Id] = x;
                        prevX = x;
                    }

                    if (prevX is { } lastX)
                        componentEndX = Math.Max(componentEndX, lastX + ColumnSpacing);
                }

                // Pass 2 (bottom-up): re-center each parent over the actual midpoint of its own
                // children, then re-resolve collisions - this is what gives the tree its classic
                // "parent sits cleanly centered above its fan-out" look instead of wherever pass 1's
                // barycenter-of-ITS-OWN-parent happened to place it.
                var childrenOf = new Dictionary<string, List<string>>();
                foreach (var node in component)
                {
                    foreach (var parentId in node.AllPrerequisiteIds)
                    {
                        if (!placedX.ContainsKey(parentId))
                            continue;
                        if (!childrenOf.TryGetValue(parentId, out var list))
                            childrenOf[parentId] = list = new List<string>();
                        list.Add(node.Id);
                    }
                }

                for (var ti = tierGroups.Count - 1; ti >= 0; ti--)
                {
                    var ordered = tierGroups[ti].OrderBy(n => placedX[n.Id]).ToList();
                    foreach (var node in ordered)
                    {
                        if (childrenOf.TryGetValue(node.Id, out var kids) && kids.Count > 0)
                            placedX[node.Id] = kids.Select(k => placedX[k]).Average();
                    }

                    float? prevX = null;
                    foreach (var node in ordered)
                    {
                        var x = placedX[node.Id];
                        if (prevX is { } p && x < p + ColumnSpacing)
                            x = p + ColumnSpacing;
                        placedX[node.Id] = x;
                        prevX = x;
                    }
                }

                // safety clamp - recentering a root over its own children could in principle pull
                // it left of this component's own lane boundary (e.g. a multi-root component whose
                // first root ends up with a lighter subtree than expected); never spill into
                // whatever component/branch was laid out just before this one
                foreach (var id in placedX.Keys.ToList())
                    placedX[id] = Math.Max(placedX[id], groupCursorX);

                // recompute the right edge from final positions - pass 2's recentering can shift
                // the rightmost node from wherever pass 1 left it
                componentEndX = Math.Max(componentEndX, placedX.Values.Max() + ColumnSpacing);

                foreach (var (id, x) in placedX)
                    xByNode[id] = x;

                groupCursorX = componentEndX + GroupGutter;
            }
        }

        foreach (var node in connected)
            _positions[node.Id] = new Vector2(xByNode[node.Id], yByTier[node.Tier]);

        var strayStartX = groupCursorX;
        var strayMaxCol = 0;
        for (var i = 0; i < strays.Count; i++)
        {
            var col = i / rowCount;
            var row = i % rowCount;
            strayMaxCol = Math.Max(strayMaxCol, col);
            _positions[strays[i].Id] = new Vector2(strayStartX + col * ColumnSpacing, Padding + row * RowSpacing);
        }

        var rightEdgeX = strays.Count > 0 ? strayStartX + strayMaxCol * ColumnSpacing : groupCursorX - GroupGutter;

        // trailing +Padding (not just +PlateWidth) mirrors the leading Padding baked into
        // groupCursorX's starting point, so there's equal drag room on the right as on the left
        MinWidth = (rightEdgeX + PlateWidth + Padding) / UIScale;
        MinHeight = (Padding * 2 + (rowCount - 1) * RowSpacing + NodeHeight) / UIScale;

        _layoutDiscipline = _disciplineFilter;
        _layoutZoom = _zoom;

        BuildDrawIndexes();
        RefreshNodeStates();
    }

    // None of these move a node, so they update in place instead of forcing a relayout.
    private void RefreshNodeStates()
    {
        if (_nodes.Count == 0 ||
            _console is not { } console ||
            !_entityManager.TryGetComponent<TechnologyDatabaseComponent>(console, out var database))
            return;

        _entityManager.TryGetComponent<FSTechDatabaseComponent>(console, out var fsDatabase);

        var unlockedFs = new HashSet<string>();
        var unlockedFsList = new List<string>();
        if (fsDatabase != null)
        {
            foreach (var node in fsDatabase.UnlockedNodes)
            {
                unlockedFs.Add(node.Id);
                unlockedFsList.Add(node.Id);
            }
        }

        var vanillaUnlocked = new HashSet<string>();
        foreach (var tech in database.UnlockedTechnologies)
            vanillaUnlocked.Add(tech.Id);

        bool IsUnlocked(string id) => vanillaUnlocked.Contains(id) || unlockedFs.Contains(id);

        foreach (var node in _nodes)
        {
            if (node.FsNode is not { } fsTech)
                continue;

            var prereqsMet = fsTech.Prerequisites.All(IsUnlocked) && fsTech.PrerequisiteGroups.All(g => g.Any(IsUnlocked));

            node.State = IsUnlocked(fsTech.ID) ? FSResearchNodeState.Unlocked
                : _fsResearch.IsExclusivelyBlocked(fsTech, unlockedFsList) ? FSResearchNodeState.ExclusivelyBlocked
                : !prereqsMet ? FSResearchNodeState.Locked
                : FSResearchNodeState.Available;

            node.IsActiveResearch = fsDatabase?.ActiveResearch is { } active && active.Id == fsTech.ID;
            node.IsMyPersonalPick = _fsResearch.MyPersonalPickId is { } mine && mine.Id == fsTech.ID;
            node.Progress = fsDatabase?.NodeProgress.GetValueOrDefault(fsTech.ID) ?? 0;
            node.ContributorSlots = fsDatabase?.PersonalContributorSlots.GetValueOrDefault(fsTech.ID) ?? new List<int>();
            node.PersonalContributorCount = node.ContributorSlots.Count;
        }
    }

    // Resolved once here so the frame loop only does dictionary lookups.
    private void BuildDrawIndexes()
    {
        foreach (var node in _nodes)
            _nodeById[node.Id] = node;

        foreach (var node in _nodes)
        {
            foreach (var prereqId in node.AllPrerequisiteIds)
            {
                if (!_nodeById.ContainsKey(prereqId))
                    continue;

                if (!_childrenByParent.TryGetValue(prereqId, out var children))
                    _childrenByParent[prereqId] = children = new List<FSResearchNodeView>();

                children.Add(node);
            }
        }

        var byGroup = new Dictionary<string, List<FSResearchNodeView>>();
        foreach (var node in _nodes)
        {
            if (node.FsNode?.ExclusiveGroup is not { } group)
                continue;

            if (!byGroup.TryGetValue(group, out var members))
                byGroup[group] = members = new List<FSResearchNodeView>();

            members.Add(node);
        }

        foreach (var members in byGroup.Values)
        {
            if (members.Count < 2)
                continue;

            members.Sort((a, b) => _positions[a.Id].X.CompareTo(_positions[b.Id].X));
            _exclusiveGroups.Add(members);
        }
    }

    // Splits a set of nodes into connected components (undirected - a prerequisite edge connects
    // regardless of direction) via BFS. Used to find genuinely disconnected sub-trees within a
    // single branch/discipline so they can each get their own lane instead of being packed into
    // one shared column grid.
    private static List<List<FSResearchNodeView>> GroupIntoComponents(List<FSResearchNodeView> nodes)
    {
        var byId = nodes.ToDictionary(n => n.Id);
        var childrenOf = new Dictionary<string, List<string>>();
        foreach (var node in nodes)
        {
            foreach (var prereqId in node.AllPrerequisiteIds)
            {
                if (!byId.ContainsKey(prereqId))
                    continue;
                if (!childrenOf.TryGetValue(prereqId, out var list))
                    childrenOf[prereqId] = list = new List<string>();
                list.Add(node.Id);
            }
        }

        var visited = new HashSet<string>();
        var components = new List<List<FSResearchNodeView>>();

        foreach (var start in nodes)
        {
            if (!visited.Add(start.Id))
                continue;

            var component = new List<FSResearchNodeView> { start };
            var queue = new Queue<string>();
            queue.Enqueue(start.Id);

            while (queue.Count > 0)
            {
                var currentId = queue.Dequeue();
                var neighborIds = byId[currentId].AllPrerequisiteIds
                    .Concat(childrenOf.TryGetValue(currentId, out var kids) ? kids : Enumerable.Empty<string>());

                foreach (var neighborId in neighborIds)
                {
                    if (!byId.TryGetValue(neighborId, out var neighbor) || !visited.Add(neighborId))
                        continue;
                    component.Add(neighbor);
                    queue.Enqueue(neighborId);
                }
            }

            components.Add(component);
        }

        return components;
    }

    private Vector2 CurrentCursor()
        => (UserInterfaceManager.MousePositionScaled.Position * UIScale) - GlobalPixelPosition;

    // Logical screen-space position, independent of this control's own position. Dragging must use
    // this (not CurrentCursor) - scrolling moves this control, which would move GlobalPixelPosition
    // mid-drag and feed back into the delta calculation, causing the jitter/shake bug. Left unscaled
    // (no *UIScale) since ScrollContainer's HScroll/VScroll are logical units, same as this.
    private Vector2 ScreenCursor()
        => UserInterfaceManager.MousePositionScaled.Position;

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        if (args.Handled || args.Function != EngineKeyFunctions.UIClick)
            return;

        _leftDown = true;
        _dragging = false;
        _dragStartCursor = ScreenCursor();
        _dragStartVScroll = _scrollContainer?.VScroll ?? 0f;
        _dragStartHScroll = _scrollContainer?.HScroll ?? 0f;
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);

        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        // _leftDown/_dragging must always clear even if a subscriber throws (e.g. a selected
        // tech with bad recipe data crashing the description lookup) - otherwise the drag state
        // gets stuck and every click after looks like a drag until one more click clears it.
        try
        {
            if (!_dragging && _hoveredTech != null)
            {
                OnNodeSelected?.Invoke(_hoveredTech);
                UserInterfaceManager.ClickSound();
            }
        }
        finally
        {
            _leftDown = false;
            _dragging = false;
        }
    }

    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);

        if (!_leftDown || _scrollContainer == null)
            return;

        var cursor = ScreenCursor();
        var delta = cursor - _dragStartCursor;
        if (!_dragging && delta.LengthSquared() < DragThreshold * DragThreshold)
            return;

        _dragging = true;
        _scrollContainer.HScroll = _dragStartHScroll - delta.X;
        _scrollContainer.VScroll = _dragStartVScroll - delta.Y;
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        base.MouseWheel(args);

        // Multiplicative step (not flat +0.1) - a flat step feels coarse and jumpy at the low end
        // of the range (0.1 is a huge relative jump at zoom 0.15) and barely noticeable at the
        // high end. ~8% per notch reads as smooth across the whole 0.15-2.0 range.
        var newZoom = Math.Clamp(_zoom * MathF.Pow(1.08f, args.Delta.Y), MinZoom, MaxZoom);
        if (Math.Abs(newZoom - _zoom) > 0.0001f)
        {
            // Zoom to cursor. The layout isn't a pure affine transform of zoom (Padding/PanMargin
            // mix in a flat, non-zoom-scaled component, and the font has a hard minimum size) -
            // there is no single formula for "where does an arbitrary point end up after Rebuild".
            // What IS exactly trackable is a real node's position, verified against the working
            // drag-to-pan code: dragging maps 1:1 in logical units between ScreenCursor() deltas
            // and HScroll/VScroll deltas, and CurrentCursor() = ScreenCursor()*UIScale offset by
            // this control's pixel position, which is itself -HScroll*UIScale. Combining those:
            // shifting HScroll by (nodeNewPos - nodeOldPos)/UIScale keeps that SAME node under the
            // cursor. A single nearest-node snap (tried first) jumped discretely at the boundary
            // between two nodes' territory; scaling the raw cursor point by the zoom ratio (tried
            // second) assumed a uniform scale from the origin that doesn't actually hold, landing
            // wherever. Blending the few nearest nodes' individual (verified-correct) deltas by
            // inverse distance keeps it accurate AND smooth as the cursor moves between them.
            var cursorContent = CurrentCursor();
            var nearest = _positions
                .OrderBy(kv => (kv.Value - cursorContent).LengthSquared())
                .Take(3)
                .ToList();

            var oldHScroll = _scrollContainer?.HScroll ?? 0f;
            var oldVScroll = _scrollContainer?.VScroll ?? 0f;

            _zoom = newZoom;
            Rebuild();

            if (_scrollContainer != null && nearest.Count > 0)
            {
                var weightedDelta = Vector2.Zero;
                var totalWeight = 0f;
                foreach (var (id, oldPos) in nearest)
                {
                    if (!_positions.TryGetValue(id, out var newPos))
                        continue;
                    var weight = 1f / MathF.Max((oldPos - cursorContent).Length(), 1f);
                    weightedDelta += (newPos - oldPos) * weight;
                    totalWeight += weight;
                }

                if (totalWeight > 0f)
                {
                    var delta = weightedDelta / totalWeight / UIScale;
                    _scrollContainer.HScroll = Math.Max(0f, oldHScroll + delta.X);
                    _scrollContainer.VScroll = Math.Max(0f, oldVScroll + delta.Y);
                }
            }
        }

        args.Handle();
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        _hoveredTech = null;
        if (_console is not { } console ||
            !_entityManager.TryGetComponent<TechnologyDatabaseComponent>(console, out _) ||
            _nodes.Count == 0)
            return;

        var origin = Position;
        var cursor = CurrentCursor();

        DrawBlueprintBackground(handle, origin);

        // anchors dip a few px INTO the icon ring / plate box (rather than stopping exactly
        // flush with the edge) so the connector always visibly touches the node - the node
        // itself is drawn on top and covers the overlap, no gap no matter the rounding
        var edgeOverlap = 6 * UIScale * _zoom;

        Vector2 GetCenter(FSResearchNodeView node) => origin + _positions[node.Id];
        Vector2 GetTopAnchor(FSResearchNodeView node) => GetCenter(node) - new Vector2(0, IconSize / 2 - edgeOverlap);
        Vector2 GetBottomAnchor(FSResearchNodeView node) => GetCenter(node) + new Vector2(0, IconSize / 2 + PlateGap + PlateHeight - edgeOverlap);

        // Connectors are grouped by parent so a multi-child fan-out shares one trunk (a single
        // drop from the parent, one horizontal bus, then a short stub into each child) instead
        // of every edge drawing its own independent elbow. Independent per-edge routing put
        // multiple horizontal segments at the same midY when siblings share a row, which could
        // visually pass through/along an unrelated node and read as a connection that isn't real.
        Color EdgeStateColor(FSResearchNodeView node) => node.State == FSResearchNodeState.Unlocked
            ? UnlockedNodeColor
            : LockedNodeColor;

        // AND-of-all (Prerequisites) reads as a solid line - every parent is mandatory. AND-of-OR
        // (PrerequisiteGroups) reads as dashed for the specific edges in that group - only one of
        // them is actually needed, same convention HOI4 uses (dotted = "either of these").
        bool IsOrEdge(FSResearchNodeView child, string parentId) => child.OrPrerequisiteIds.Contains(parentId);

        void DrawEdgeLine(Vector2 from, Vector2 to, Color color, FSResearchNodeView child, string parentId)
        {
            if (IsOrEdge(child, parentId))
                DrawDashedLine(handle, from, to, color);
            else
                handle.DrawLine(from, to, color);
        }

        foreach (var (parentId, allChildren) in _childrenByParent)
        {
            var parent = _nodeById[parentId];
            var parentCenter = GetCenter(parent);
            var parentBottom = GetBottomAnchor(parent);
            var trunkColor = EdgeStateColor(parent);

            // Tech tier doesn't strictly guarantee a prerequisite sits in a strictly-lower row
            // (two techs can share a tier while one still requires the other) - a normal
            // drop-then-bus elbow assumes the child is below the parent, and for a same-row
            // (or "above") child that puts the horizontal segment mid-row, cutting right through
            // the icons and reading as a wrong/crossed connection. Route those laterally instead:
            // a straight line between the two icons' facing edges at icon-center height.
            var children = new List<FSResearchNodeView>();
            foreach (var child in allChildren)
            {
                var childCenter = GetCenter(child);
                if (childCenter.Y > parentCenter.Y + 1f)
                {
                    children.Add(child);
                    continue;
                }

                var iconR = IconSize / 2;
                var dir = childCenter.X >= parentCenter.X ? 1f : -1f;
                var from = parentCenter + new Vector2(dir * iconR, 0);
                var to = childCenter - new Vector2(dir * iconR, 0);
                DrawEdgeLine(from, to, EdgeStateColor(child), child, parentId);
            }

            if (children.Count == 0)
                continue;

            if (children.Count == 1)
            {
                var childTop = GetTopAnchor(children[0]);
                var childColor = EdgeStateColor(children[0]);
                if (Math.Abs(parentBottom.X - childTop.X) < 0.5f)
                {
                    DrawEdgeLine(parentBottom, childTop, childColor, children[0], parentId);
                    continue;
                }

                // Anchored to the child's row so multiple long edges converging on one node bend at a consistent height.
                var soloMidY = childTop.Y - RowSpacing * 0.4f;
                handle.DrawLine(parentBottom, new Vector2(parentBottom.X, soloMidY), trunkColor);
                handle.DrawLine(new Vector2(parentBottom.X, soloMidY), new Vector2(childTop.X, soloMidY), trunkColor);
                DrawEdgeLine(new Vector2(childTop.X, soloMidY), childTop, childColor, children[0], parentId);
                continue;
            }

            var childTops = children.Select(GetTopAnchor).ToList();
            var busY = (parentBottom.Y + childTops[0].Y) / 2f;
            var minX = Math.Min(parentBottom.X, childTops.Min(c => c.X));
            var maxX = Math.Max(parentBottom.X, childTops.Max(c => c.X));

            handle.DrawLine(parentBottom, new Vector2(parentBottom.X, busY), trunkColor);
            handle.DrawLine(new Vector2(minX, busY), new Vector2(maxX, busY), trunkColor);

            for (var i = 0; i < children.Count; i++)
                DrawEdgeLine(new Vector2(childTops[i].X, busY), childTops[i], EdgeStateColor(children[i]), children[i], parentId);
        }

        foreach (var node in _nodes)
        {
            var center = GetCenter(node);
            var iconRadius = IconSize / 2;

            // Discipline is a hard page filter now (see Rebuild) - _nodes only ever contains the
            // current page's nodes, so opacity only needs to reflect the search box.
            var matchesSearch = _filter.Length == 0 ||
                                 node.Name.Contains(_filter, StringComparison.OrdinalIgnoreCase);
            var opacity = matchesSearch ? 1f : 0.25f;
            if (node.State == FSResearchNodeState.ExclusivelyBlocked)
                opacity *= 0.4f;

            var stateColor = node.State switch
            {
                FSResearchNodeState.Unlocked => UnlockedNodeColor,
                FSResearchNodeState.Available => AvailableNodeColor,
                _ => LockedNodeColor,
            };
            var color = Fade(stateColor, opacity);

            var line = TruncateForPlate(node.Name);
            var lineDims = handle.GetDimensions(_font, line, 1);
            // floor at MinPlateWidth, but never shrink below what the (already-truncated) text needs
            var actualPlateWidth = Math.Max(lineDims.X + 48 * UIScale * _zoom, MinPlateWidth);
            var plateBox = UIBox2.FromDimensions(
                new Vector2(center.X - actualPlateWidth / 2, center.Y + iconRadius + PlateGap),
                new Vector2(actualPlateWidth, PlateHeight));

            var hoveredIcon = (cursor - center).LengthSquared() <= iconRadius * iconRadius;
            var hoveredPlate = plateBox.Contains(cursor);
            var hovered = hoveredIcon || hoveredPlate;
            if (hovered)
                _hoveredTech = node;

            if (hovered)
            {
                // glow radius = icon radius + an outward pad, same idea as the plate's glow -
                // it needs to actually clear the icon's own edge, or the opaque ring/disc drawn
                // right after this covers almost all of it and the glow reads as invisible
                var glowPad = 16 * UIScale * _zoom;
                var glowSize = (iconRadius + glowPad) * 2f;
                var glowBox = UIBox2.FromDimensions(center - new Vector2(glowSize / 2, glowSize / 2), new Vector2(glowSize, glowSize));
                handle.DrawTextureRect(_glowTexture, glowBox, HoverGlowColor.WithAlpha(0.45f));

                // plate_glow.png bakes the same blur margin (16px) around the same 128x40/13px-
                // radius core shape as plate_bg/plate_ring, at a 160x72/29px-cap canvas - a single
                // soft-gradient draw instead of the old stepped-ring approximation, matching how
                // the icon's own glow above is one pre-blurred texture draw, not layered rings.
                var plateGlowMargin = 22 * UIScale * _zoom;
                var plateGlowBox = new UIBox2(
                    plateBox.Left - plateGlowMargin, plateBox.Top - plateGlowMargin,
                    plateBox.Right + plateGlowMargin, plateBox.Bottom + plateGlowMargin);
                DrawHSlicedRect(handle, _plateGlowTexture, plateGlowBox, HoverGlowColor.WithAlpha(0.65f),
                    texW: 172f, texH: 84f, capPx: 42f);
            }

            if (node.ContributorSlots.Count > 0)
                DrawContributorRings(handle, center, iconRadius, node.ContributorSlots, opacity);

            var innerRadius = iconRadius - IconBorderThickness;
            var discBox = UIBox2.FromDimensions(center - new Vector2(innerRadius, innerRadius), new Vector2(innerRadius * 2, innerRadius * 2));
            handle.DrawTextureRect(_discTexture, discBox, Fade(PlateBackgroundColor, opacity));

            var artSize = innerRadius * 2 * 0.82f;
            var artBox = UIBox2.FromDimensions(center - new Vector2(artSize / 2, artSize / 2), new Vector2(artSize, artSize));
            handle.DrawTextureRect(_sprite.Frame0(node.Icon), artBox, Color.White.WithAlpha(opacity));

            var ringBox = UIBox2.FromDimensions(center - new Vector2(iconRadius, iconRadius), new Vector2(iconRadius * 2, iconRadius * 2));
            handle.DrawTextureRect(_ringTexture, ringBox, color);

            if (node.State == FSResearchNodeState.ExclusivelyBlocked)
                DrawBlockedX(handle, center, iconRadius);

            DrawHSlicedRect(handle, _plateBgTexture, plateBox, Fade(PlateBackgroundColor, opacity));

            if (node.Progress > 0 && node.Cost > 0)
            {
                var barFrac = Math.Clamp((float)node.Progress / node.Cost, 0f, 1f);
                if (barFrac > 0f)
                {
                    var fillColor = node.IsMyPersonalPick ? FSUiPalette.AccentBrand
                        : node.IsActiveResearch ? FSUiPalette.StatePositive
                        : FSUiPalette.StateResearch;
                    var fillBox = new UIBox2(
                        plateBox.Left, plateBox.Top,
                        plateBox.Left + plateBox.Width * barFrac, plateBox.Bottom);
                    DrawHSlicedRect(handle, _plateBgTexture, fillBox, Fade(fillColor, opacity));
                }
            }

            var otherContributors = node.PersonalContributorCount - (node.IsMyPersonalPick ? 1 : 0);
            if (otherContributors > 0)
                DrawContributorBadge(handle, center, iconRadius, otherContributors, opacity);

            DrawHSlicedRect(handle, _plateRingTexture, plateBox, color);

            var linePos = new Vector2(plateBox.Center.X - lineDims.X / 2, plateBox.Center.Y - lineDims.Y / 2);
            handle.DrawString(_font, linePos, line, color);
        }

        // Mutually exclusive marker - same visual language as HOI4's "pick one, lock the other"
        // indicator between two sibling choices. Drawn last so it sits on top of connector lines.
        foreach (var ordered in _exclusiveGroups)
        {
            // one marker between each adjacent pair - handles the common 2-choice case cleanly,
            // and still reads fine for a rare 3+-way exclusive group
            for (var i = 0; i < ordered.Count - 1; i++)
            {
                var centerA = GetCenter(ordered[i]);
                var centerB = GetCenter(ordered[i + 1]);

                // a line connecting the two choices themselves, same as your reference diagram -
                // drawn first so the marker (opaque) sits on top and visually breaks it in the
                // middle, reading as "line runs into the marker from both sides" rather than two
                // disconnected halves
                var delta = centerB - centerA;
                var dist = delta.Length();
                if (dist > 0.01f)
                {
                    var dirNorm = delta / dist;
                    var iconR = IconSize / 2;
                    handle.DrawLine(centerA + dirNorm * iconR, centerB - dirNorm * iconR, LockedNodeColor);
                }

                var mid = (centerA + centerB) / 2f;
                var markerWidth = 56 * UIScale * _zoom;
                var markerHeight = markerWidth / 3f;
                var markerBox = UIBox2.FromDimensions(
                    mid - new Vector2(markerWidth / 2, markerHeight / 2), new Vector2(markerWidth, markerHeight));
                handle.DrawTextureRect(_exclusiveMarkerTexture, markerBox, Color.White);
            }
        }
    }

    private static Color Fade(Color color, float opacity) => new(color.R, color.G, color.B, color.A * opacity);

    private void DrawContributorBadge(DrawingHandleScreen handle, Vector2 center, float iconRadius, int count, float opacity)
    {
        var badgeRadius = Math.Max(6f, iconRadius * 0.24f);
        var badgeCenter = center + new Vector2(iconRadius * 0.72f, -iconRadius * 0.72f);

        handle.DrawCircle(badgeCenter, badgeRadius + 1.5f, Fade(FSUiPalette.BgDeep, opacity));
        handle.DrawCircle(badgeCenter, badgeRadius, Fade(FSUiPalette.StateResearch, opacity));

        var text = count > 9 ? "9+" : count.ToString();
        var dims = handle.GetDimensions(_font, text, 1);
        var textPos = badgeCenter - new Vector2(dims.X / 2, dims.Y / 2);
        handle.DrawString(_font, textPos, text, Fade(FSUiPalette.TextPrimary, opacity));
    }

    private static readonly Color[] ContributorSlotPalette =
    {
        Color.FromHex("#F87171"),
        Color.FromHex("#60A5FA"),
        Color.FromHex("#4ADE80"),
        Color.FromHex("#FBBF24"),
        Color.FromHex("#C084FC"),
        Color.FromHex("#2DD4BF"),
        Color.FromHex("#F472B6"),
        Color.FromHex("#A3E635"),
    };

    // Tootsie-pop layering: draws outermost-in so each smaller circle overpaints the previous one's center, leaving only a thin ring per contributor.
    private void DrawContributorRings(DrawingHandleScreen handle, Vector2 center, float iconRadius, List<int> slots, float opacity)
    {
        var thickness = Math.Max(2.5f, iconRadius * 0.09f);
        var gap = thickness * 0.5f;

        for (var i = slots.Count - 1; i >= 0; i--)
        {
            var outerR = iconRadius + (i + 1) * (thickness + gap);
            var color = ContributorSlotPalette[((slots[i] % ContributorSlotPalette.Length) + ContributorSlotPalette.Length) % ContributorSlotPalette.Length];
            handle.DrawCircle(center, outerR, Fade(color, opacity));
            handle.DrawCircle(center, outerR - thickness, Fade(FSUiPalette.BgDeep, opacity));
        }
    }

    private void DrawBlockedX(DrawingHandleScreen handle, Vector2 center, float iconRadius)
    {
        var inset = iconRadius * 0.32f;
        var a = center + new Vector2(-iconRadius + inset, -iconRadius + inset);
        var b = center + new Vector2(iconRadius - inset, iconRadius - inset);
        var c = center + new Vector2(-iconRadius + inset, iconRadius - inset);
        var d = center + new Vector2(iconRadius - inset, -iconRadius + inset);

        var thickness = Math.Max(1f, 2f * UIScale * _zoom);
        DrawThickLine(handle, a, b, FSUiPalette.StateNegative, thickness);
        DrawThickLine(handle, c, d, FSUiPalette.StateNegative, thickness);
    }

    private static void DrawThickLine(DrawingHandleScreen handle, Vector2 from, Vector2 to, Color color, float thickness)
    {
        var delta = to - from;
        var length = delta.Length();
        if (length < 0.01f)
            return;

        var normal = new Vector2(-delta.Y, delta.X) / length;
        var steps = Math.Max(1, (int)MathF.Ceiling(thickness));
        if (steps == 1)
        {
            handle.DrawLine(from, to, color);
            return;
        }

        for (var i = 0; i < steps; i++)
        {
            var offset = normal * (thickness * (i / (float)(steps - 1) - 0.5f));
            handle.DrawLine(from + offset, to + offset, color);
        }
    }

    // Dotted = OR-group prerequisite edges ("either of these"); solid DrawLine is used for mandatory AND edges.
    private void DrawDashedLine(DrawingHandleScreen handle, Vector2 from, Vector2 to, Color color)
    {
        var dashLength = 8f * UIScale * _zoom;
        var gapLength = 6f * UIScale * _zoom;
        var delta = to - from;
        var length = delta.Length();
        if (length < 0.01f)
            return;

        var dir = delta / length;
        var traveled = 0f;
        var drawing = true;
        while (traveled < length)
        {
            var segLength = Math.Min(drawing ? dashLength : gapLength, length - traveled);
            if (drawing)
                handle.DrawLine(from + dir * traveled, from + dir * (traveled + segLength), color);
            traveled += segLength;
            drawing = !drawing;
        }
    }

    // Blueprint-grid canvas backdrop, tiled to cover the whole scrollable tree (not just the
    // visible viewport). Tile size is fixed on screen (UIScale only, no _zoom) - it's a backdrop,
    // not part of the content, so it reads as a constant wallpaper texture instead of its own
    // grid squares growing/shrinking alongside the nodes as you zoom. DrawTextureRect always
    // stretches src->dest with no native repeat mode, so tiling is just a manual grid of draw calls.
    private void DrawBlueprintBackground(DrawingHandleScreen handle, Vector2 origin)
    {
        var tileW = 480f * UIScale;
        var tileH = tileW * ((float)_blueprintTexture.Height / _blueprintTexture.Width);
        var canvasW = Size.X * UIScale;
        var canvasH = Size.Y * UIScale;
        var cols = (int)Math.Ceiling(canvasW / tileW) + 1;
        var rows = (int)Math.Ceiling(canvasH / tileH) + 1;

        var tint = Color.White.WithAlpha(0.5f);
        for (var ty = 0; ty < rows; ty++)
        for (var tx = 0; tx < cols; tx++)
        {
            var tileBox = UIBox2.FromDimensions(origin + new Vector2(tx * tileW, ty * tileH), new Vector2(tileW, tileH));
            handle.DrawTextureRect(_blueprintTexture, tileBox, tint);
        }
    }

    // Horizontal 3-slice: the plate textures are a 128x40 rounded rect with a 10px corner radius.
    // Plate width varies per node (shrink-to-fit text), so a plain whole-texture stretch would
    // squash the rounded corners into ellipses - slice out the two corner caps at a fixed source
    // width and only stretch the flat middle strip, same idea as RT's own StyleBoxTexture 9-slice.
    // texW/texH/capPx are parameterized (not just for plate_bg/plate_ring's 128x40/13) so the same
    // slicing logic also works for plate_glow.png, which is a wider canvas (extra blur margin baked
    // in around the same core shape) with a correspondingly wider cap.
    private void DrawHSlicedRect(DrawingHandleScreen handle, Texture texture, UIBox2 destBox, Color modulate,
        float texW = 128f, float texH = 40f, float capPx = 13f)
    {
        var destCap = Math.Min(capPx * UIScale * _zoom, destBox.Width / 2f);

        handle.DrawTextureRectRegion(texture,
            new UIBox2(destBox.Left, destBox.Top, destBox.Left + destCap, destBox.Bottom),
            new UIBox2(0, 0, capPx, texH), modulate);

        handle.DrawTextureRectRegion(texture,
            new UIBox2(destBox.Right - destCap, destBox.Top, destBox.Right, destBox.Bottom),
            new UIBox2(texW - capPx, 0, texW, texH), modulate);

        if (destBox.Width > destCap * 2)
        {
            handle.DrawTextureRectRegion(texture,
                new UIBox2(destBox.Left + destCap, destBox.Top, destBox.Right - destCap, destBox.Bottom),
                new UIBox2(texW / 2f - 1, 0, texW / 2f + 1, texH), modulate);
        }
    }

    // Single line only - a plate tall enough for 2 lines but usually showing 1 looked lopsided
    // (that was the real "boxes look uneven" issue, not padding). Long names get ellipsis-truncated
    // instead of wrapping; the full name is always available in the detail panel on click.
    // Character-count truncation (like HOI4's focus names), not pixel-width - a fixed budget in
    // characters reads consistently across names instead of cutting some names much shorter than
    // others just because their glyphs happen to be a bit wider on average.
    private static string TruncateForPlate(string text)
    {
        if (text.Length <= PlateMaxChars)
            return text;

        return text[..(PlateMaxChars - 1)] + "…";
    }
}
