using System;
using System.Collections.Generic;
using System.Linq;
using Content.Client._FinalStand.Research;
using Content.Client._FinalStand.Stylesheets;
using Content.Client.Research;
using Content.Client.UserInterface.Controls;
using Content.Shared._FinalStand.Research.Components;
using Content.Shared._FinalStand.Research.Prototypes;
using Content.Shared.Materials;
using Content.Shared.Research.Components;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._FinalStand.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FSResearchTreeMenu : FancyWindow
{
    public Action<string>? OnTechnologyCardPressed;
    public Action<string>? OnFsNodeSelected;
    public Action? OnServerButtonPressed;
    public Action? OnClearPersonalPick;

    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    private readonly ResearchSystem _research;
    private readonly FSResearchClientSystem _fsResearch;
    private readonly SharedMaterialStorageSystem _materialStorage;

    private const int ProgressSegments = 12;

    // decorative only - a tier's dot color here is not the same signal as a node's state color
    private static readonly Color[] TierLegendColors =
    {
        FSUiPalette.TextMuted,
        FSUiPalette.StatePositive,
        Color.FromHex("#38BDF8"),
        FSUiPalette.AccentBrand,
        FSUiPalette.StatePending,
    };

    public EntityUid Entity;

    private FSResearchNodeView? _selectedNode;
    private ResearchConsoleBoundInterfaceState? _state;
    private readonly List<(Button Button, string? GroupId, Color? Accent)> _disciplineButtons = new();

    public FSResearchTreeMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _research = _entity.System<ResearchSystem>();
        _fsResearch = _entity.System<FSResearchClientSystem>();
        _materialStorage = _entity.System<SharedMaterialStorageSystem>();

        // FancyWindow shadows Control.Stylesheet with a `new string?` (registered-name lookup)
        // property, so `this.Stylesheet = ...` won't accept a Stylesheet object here the way it
        // does on WeaponShopWindow (a plain DefaultWindow) - cast to the base Control type to
        // reach the real object-typed property and actually apply the shared menu stylesheet.
        ((Control)this).Stylesheet = new FSMenuStylesheet(
            IoCManager.Resolve<IUserInterfaceManager>(), _resourceCache).Stylesheet;

        var panelBox = new StyleBoxTexture
        {
            Texture = _resourceCache.GetResource<TextureResource>("/Textures/_FinalStand/Interface/Research/panel_bg.png").Texture,
            Modulate = FSUiPalette.BgSurface,
        };
        panelBox.SetPatchMargin(StyleBox.Margin.All, FSUiPalette.PanelCornerRadius);
        GraphPanelContainer.PanelOverride = panelBox;
        DetailPanelContainer.PanelOverride = panelBox;

        StatsHeaderLabel.FontColorOverride = FSUiPalette.AccentBrand;
        RequirementsHeaderLabel.FontColorOverride = FSUiPalette.AccentBrand;
        AuthorityWarningLabel.FontColorOverride = FSUiPalette.StateNegative;

        HeaderResearchIcon.Texture = _resourceCache
            .GetResource<TextureResource>("/Textures/_FinalStand/Interface/Research/research_icon_purple.png").Texture;

        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();

        SearchBox.OnTextChanged += args => GraphControl.SetFilter(args.Text);
        GraphControl.SetScrollContainer(GraphScroll);

        BuildTierLegend();
        BuildEmptyState();

        StartResearchButton.OnPressed += _ =>
        {
            if (_selectedNode is not { } selected)
                return;
            if (selected.FsNode != null)
                OnFsNodeSelected?.Invoke(selected.Id);
            else
                OnTechnologyCardPressed?.Invoke(selected.Id);
        };

        CancelButton.OnPressed += _ =>
        {
            _selectedNode = null;
            UpdateDetailPanel();
        };

        ClearPersonalPickButton.OnPressed += _ => OnClearPersonalPick?.Invoke();

        GraphControl.OnNodeSelected += node =>
        {
            _selectedNode = node;
            UpdateDetailPanel();
        };

        UpdateDetailPanel();
    }

    public void SetEntity(EntityUid entity)
    {
        Entity = entity;
        GraphControl.SetConsole(entity);
        RebuildDisciplineRail();
    }

    // Tabs are separate pages, not a dimming filter (see FSResearchNodeGraphControl.Rebuild) - one
    // tab per FS branch, then "ALL" last.
    private void RebuildDisciplineRail()
    {
        DisciplineRailContainer.RemoveAllChildren();
        _disciplineButtons.Clear();

        if (!_entity.TryGetComponent<TechnologyDatabaseComponent>(Entity, out _))
            return;

        string? defaultPage = null;
        foreach (var branch in _prototype.EnumeratePrototypes<FSTechBranchPrototype>().OrderBy(b => b.SortOrder))
        {
            AddDisciplineButton(branch.ID, branch.Name.ToUpperInvariant(), branch.Color);
            defaultPage ??= branch.ID;
        }

        AddDisciplineButton(null, "ALL", null);

        SelectDiscipline(defaultPage);
    }

    private void AddDisciplineButton(string? groupId, string label, Color? accent)
    {
        var button = new Button
        {
            Text = label,
            Margin = new Thickness(0, 0, 6, 0),
        };
        button.OnPressed += _ => SelectDiscipline(groupId);
        DisciplineRailContainer.AddChild(button);
        _disciplineButtons.Add((button, groupId, accent));
    }

    private void SelectDiscipline(string? groupId)
    {
        GraphControl.SetDisciplineFilter(groupId);
        foreach (var (button, id, accent) in _disciplineButtons)
        {
            var selected = id == groupId;
            var accentColor = accent ?? FSUiPalette.AccentBrand;
            button.Label.FontColorOverride = accent != null ? accentColor : selected ? FSUiPalette.AccentBrand : FSUiPalette.TextMuted;
            button.StyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = selected ? accentColor.WithAlpha(0.18f) : Color.Transparent,
                BorderColor = accentColor,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 10,
                ContentMarginRightOverride = 10,
                ContentMarginTopOverride = 5,
                ContentMarginBottomOverride = 5,
            };
        }
    }

    private void BuildTierLegend()
    {
        TierLegendContainer.RemoveAllChildren();

        for (var tier = 0; tier < TierLegendColors.Length; tier++)
        {
            var dot = new PanelContainer
            {
                SetWidth = 10,
                SetHeight = 10,
                Margin = new Thickness(0, 0, 4, 0),
                VerticalAlignment = VAlignment.Center,
            };
            dot.PanelOverride = new StyleBoxFlat { BackgroundColor = TierLegendColors[tier] };
            TierLegendContainer.AddChild(dot);
            TierLegendContainer.AddChild(new Label
            {
                Text = $"Tier {tier + 1}",
                Modulate = FSUiPalette.TextMuted,
                Margin = new Thickness(0, 0, 14, 0),
            });
        }

        TierLegendContainer.AddChild(new Control { HorizontalExpand = true });

        var resetButton = new Button { Text = "Reset View" };
        resetButton.OnPressed += _ => GraphControl.ResetView();
        TierLegendContainer.AddChild(resetButton);
    }

    private void BuildEmptyState()
    {
        EmptyStateContainer.RemoveAllChildren();

        var icon = new TextureRect
        {
            Texture = _resourceCache.GetResource<TextureResource>(
                "/Textures/_FinalStand/Interface/Research/research_icon_white.png").Texture,
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            SetWidth = 72,
            SetHeight = 72,
            HorizontalAlignment = HAlignment.Center,
            Modulate = FSUiPalette.TextMuted.WithAlpha(0.35f),
        };
        EmptyStateContainer.AddChild(icon);
        EmptyStateContainer.AddChild(new Label
        {
            Text = "Select a technology",
            HorizontalAlignment = HAlignment.Center,
            Modulate = FSUiPalette.TextMuted,
            Margin = new Thickness(0, 10, 0, 0),
        });
    }

    public void UpdatePanels(ResearchConsoleBoundInterfaceState state)
    {
        _state = state;
        GraphControl.SetConsole(Entity);
        UpdateDetailPanel();
    }

    public void RefreshLiveState()
    {
        GraphControl.SetConsole(Entity);
        UpdateDetailPanel();
    }

    public void UpdateInformationPanel(ResearchConsoleBoundInterfaceState state)
    {
        _state = state;
        UpdateDetailPanel();
    }

    // Shows FS's own banked RP, not vanilla ResearchServerComponent.Points.
    private void UpdateResearchAmountLabel()
    {
        var points = _entity.TryGetComponent<FSTechDatabaseComponent>(Entity, out var fsDb) ? fsDb.Points : 0;
        var amountMsg = new FormattedMessage();
        amountMsg.AddMarkupOrThrow(Loc.GetString("research-console-menu-research-points-text",
            ("points", points)));
        ResearchAmountLabel.SetMessage(amountMsg);
    }

    public void ShowAuthorityDenied(string reason)
    {
        AuthorityWarningLabel.Text = reason;
        AuthorityWarningLabel.Visible = true;
    }

    private void UpdateDetailPanel()
    {
        UpdateResearchAmountLabel();

        AuthorityWarningLabel.Visible = false;
        AuthorityWarningLabel.Text = "";
        ClearPersonalPickButton.Visible = false;

        EmptyStateContainer.Visible = _selectedNode == null;

        if (_selectedNode == null)
        {
            TechNameLabel.Text = "";
            TechDescLabel.SetMessage(new FormattedMessage());
            TechStatsLabel.SetMessage(new FormattedMessage());
            RequirementsLabel.SetMessage(new FormattedMessage());
            MaterialsLabel.SetMessage(new FormattedMessage());
            RpNeededLabel.Text = "RP Needed: —";
            BuildProgressBar(0f);
            ProgressCounterLabel.Text = "";
            StartResearchButton.Disabled = true;
            StartResearchButton.Text = "Start Research";
            return;
        }

        var node = _selectedNode;
        TechNameLabel.Text = node.Name;

        if (node.Vanilla is { } tech)
            UpdateDetailPanelVanilla(tech);
        else if (node.FsNode is { } fsNode)
            UpdateDetailPanelFsNode(fsNode);

        RequirementsLabel.SetMessage(BuildRequirementsMessage(node));

        MaterialsLabel.SetMessage(new FormattedMessage());
        RpNeededLabel.Text = $"RP Needed: {node.Cost}";

        if (node.FsNode != null)
        {
            MaterialsLabel.SetMessage(BuildMaterialsMessage(node.FsNode, out var hasEnoughMaterials));

            // Shared-pick cost is halved server-side too (see FSResearchSystem.GrantResearchPoints).
            var effectiveCost = node.IsActiveResearch ? Math.Max(1, node.Cost / 2) : node.Cost;
            var fsFill = effectiveCost > 0 ? Math.Min(1f, (float)node.Progress / effectiveCost) : 1f;
            BuildProgressBar(fsFill);
            RpNeededLabel.Text = node.IsActiveResearch ? $"RP Needed: {effectiveCost} (shared, half-cost)" : $"RP Needed: {effectiveCost}";

            var otherContributors = node.PersonalContributorCount - (node.IsMyPersonalPick ? 1 : 0);
            var contributorSuffix = otherContributors switch
            {
                <= 0 => "",
                1 => " · 1 other scientist researching this",
                _ => $" · {otherContributors} other scientists researching this",
            };
            ProgressCounterLabel.Text = node.State == FSResearchNodeState.Unlocked
                ? "Completed"
                : $"{node.Progress}/{effectiveCost}{contributorSuffix}";

            ClearPersonalPickButton.Visible = node.IsMyPersonalPick && node.State != FSResearchNodeState.Unlocked;

            if (node.State == FSResearchNodeState.Unlocked)
            {
                StartResearchButton.Text = "Researched";
                StartResearchButton.Disabled = true;
            }
            else if (node.IsActiveResearch)
            {
                StartResearchButton.Text = "Researching (Shared, Half-Cost)...";
                StartResearchButton.Disabled = true;
            }
            else if (node.IsMyPersonalPick)
            {
                StartResearchButton.Text = "Personally Researching...";
                StartResearchButton.Disabled = true;
            }
            else
            {
                StartResearchButton.Text = otherContributors > 0 ? $"Join Research ({otherContributors} others)" : "Start Research";
                StartResearchButton.Disabled = node.State != FSResearchNodeState.Available;

                if (node.State == FSResearchNodeState.Available && !hasEnoughMaterials)
                {
                    AuthorityWarningLabel.Text = "Not Enough Materials";
                    AuthorityWarningLabel.Visible = true;
                }
            }
            return;
        }

        var points = _state?.Points ?? 0;
        var fill = node.Cost > 0 ? Math.Min(1f, (float)points / node.Cost) : 1f;
        BuildProgressBar(fill);
        ProgressCounterLabel.Text = node.State == FSResearchNodeState.Unlocked
            ? "Completed"
            : $"{Math.Min(points, node.Cost)}/{node.Cost}";

        StartResearchButton.Text = node.State == FSResearchNodeState.Unlocked ? "Researched" : "Start Research";
        StartResearchButton.Disabled = node.State != FSResearchNodeState.Available || points < node.Cost;
    }

    private void UpdateDetailPanelVanilla(TechnologyPrototype tech)
    {
        // GetTechnologyDescription indexes RecipeUnlocks with a throwing Index() call; some techs
        // reference lathe recipes that don't exist in this build's prototype set, which would
        // otherwise crash the whole panel (and leave the graph's click/drag state stuck).
        try
        {
            TechDescLabel.SetMessage(_research.GetTechnologyDescription(tech, includeCost: false, includeTier: false));
        }
        catch (UnknownPrototypeException)
        {
            TechDescLabel.SetMessage(new FormattedMessage());
        }

        // RecipeUnlocks is already listed under "Unlocks:" by GetTechnologyDescription above -
        // repeating "<name> Unlocked" for every recipe here was pure duplication when a tech's
        // only effect is unlocking machines/recipes. Only show something here when there's an
        // actual buff/stat description (GenericUnlocks), otherwise it's just a dash.
        var statLines = new List<string>();
        foreach (var generic in tech.GenericUnlocks)
        {
            if (!string.IsNullOrEmpty(generic.UnlockDescription))
                statLines.Add(Loc.GetString(generic.UnlockDescription));
        }
        var statsMsg = new FormattedMessage();
        statsMsg.AddText(statLines.Count > 0 ? string.Join("\n", statLines) : "—");
        TechStatsLabel.SetMessage(statsMsg);
    }

    private void UpdateDetailPanelFsNode(FSTechNodePrototype fsNode)
    {
        // Wrapper node - defer entirely to the vanilla tech's own unlocks-list rendering.
        if (fsNode.VanillaTechnologyId is { } vanillaId && _prototype.TryIndex(vanillaId, out var vanillaTech))
        {
            UpdateDetailPanelVanilla(vanillaTech);
            return;
        }

        var descMsg = new FormattedMessage();
        if (fsNode.WeaponShopUnlock is { } shopId)
        {
            var shopName = _prototype.TryIndex<EntityPrototype>(shopId, out var shopProto) ? shopProto.Name : shopId.Id;
            descMsg.AddText($"Unlocks purchase access to the {shopName} shop table.");
        }
        if (fsNode.ExclusiveGroup != null)
        {
            if (fsNode.WeaponShopUnlock != null)
                descMsg.PushNewline();
            descMsg.AddText("Mutually exclusive choice - researching this locks out its alternative(s).");
        }
        TechDescLabel.SetMessage(descMsg);

        var statsMsg = new FormattedMessage();
        statsMsg.AddText(fsNode.BonusDescription != string.Empty ? Loc.GetString(fsNode.BonusDescription) : "—");
        TechStatsLabel.SetMessage(statsMsg);
    }

    // Prerequisite ids can point at either an FSTechNodePrototype or a vanilla TechnologyPrototype
    // (cross-branch joins, e.g. Tesla Cannon requiring the Experimental AnomalyCoreHarnessing) -
    // resolve names/unlocked-state across both prototype pools. PrerequisiteGroups (AND-of-OR,
    // e.g. a capstone needing "at least one choice per branch") render as "A OR B" lines, colored
    // by whether any one entry in the group is unlocked rather than all of them.
    private FormattedMessage BuildRequirementsMessage(FSResearchNodeView node)
    {
        var lines = new List<string>();

        foreach (var prereqId in node.Prerequisites)
        {
            var reqColor = IsIdUnlocked(prereqId) ? FSUiPalette.StatePositive : FSUiPalette.StateNegative;
            lines.Add($"[color={reqColor.ToHex()}]{ResolveNodeName(prereqId)}[/color]");
        }

        foreach (var group in node.PrerequisiteGroups)
        {
            var reqColor = group.Any(IsIdUnlocked) ? FSUiPalette.StatePositive : FSUiPalette.StateNegative;
            var names = string.Join(" OR ", group.Select(ResolveNodeName));
            lines.Add($"[color={reqColor.ToHex()}]{names}[/color]");
        }

        var msg = new FormattedMessage();
        if (lines.Count == 0)
        {
            msg.AddText("—");
            return msg;
        }

        for (var i = 0; i < lines.Count; i++)
        {
            msg.AddMarkupOrThrow(lines[i]);
            if (i < lines.Count - 1)
                msg.PushNewline();
        }

        return msg;
    }

    // Display hint only - server re-checks materials for real at selection time.
    private FormattedMessage BuildMaterialsMessage(FSTechNodePrototype fsNode, out bool hasEnough)
    {
        hasEnough = true;
        var msg = new FormattedMessage();

        if (fsNode.MaterialCost.Count == 0)
        {
            msg.AddText("Materials Needed: None");
            return msg;
        }

        var stored = _materialStorage.GetStoredMaterials(Entity);
        msg.AddText("Materials Needed: ");

        var entries = fsNode.MaterialCost.ToList();
        for (var i = 0; i < entries.Count; i++)
        {
            var (matId, amount) = entries[i];
            var name = _prototype.TryIndex(matId, out var mat) ? Loc.GetString(mat.Name) : matId.Id;
            var have = stored.GetValueOrDefault(matId);
            var enough = have >= amount;
            if (!enough)
                hasEnough = false;

            var color = enough ? FSUiPalette.TextPrimary : FSUiPalette.StateNegative;
            msg.AddMarkupOrThrow($"[color={color.ToHex()}]{name} x{amount}[/color]");
            if (i < entries.Count - 1)
                msg.AddText(", ");
        }

        return msg;
    }

    private bool IsIdUnlocked(string id)
    {
        if (_entity.TryGetComponent<TechnologyDatabaseComponent>(Entity, out var db) && db.UnlockedTechnologies.Any(u => u.Id == id))
            return true;
        if (_entity.TryGetComponent<FSTechDatabaseComponent>(Entity, out var fsDb) && fsDb.UnlockedNodes.Any(u => u.Id == id))
            return true;
        return false;
    }

    private string ResolveNodeName(string id)
    {
        if (_prototype.TryIndex<FSTechNodePrototype>(id, out var fsProto))
            return fsProto.Name;
        if (_prototype.TryIndex<TechnologyPrototype>(id, out var techProto))
            return Loc.GetString(techProto.Name);
        return id;
    }

    private void BuildProgressBar(float fill)
    {
        ProgressBarContainer.RemoveAllChildren();
        var filled = (int)Math.Round(Math.Clamp(fill, 0f, 1f) * ProgressSegments);
        for (var i = 0; i < ProgressSegments; i++)
        {
            var seg = new PanelContainer
            {
                HorizontalExpand = true,
                SetHeight = 10,
                Margin = new Thickness(i == 0 ? 0 : 1, 0, 0, 0),
            };
            seg.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = i < filled ? FSUiPalette.StatePositive : FSUiPalette.BgRecess,
            };
            ProgressBarContainer.AddChild(seg);
        }
    }
}
