using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._FinalStand.Augments;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._FinalStand.Augments.UI;

[GenerateTypedNameReferences]
public sealed partial class AugmentShopWindow : FancyWindow
{
    private FSAugmentsStateEvent? _state;
    private string? _selectedId;
    private int? _selectedSlot;
    private AugmentCategory? _filterCategory;
    private string _search = "";

    private int _playerLevel = 1;
    private int _prestigeLevel;

    private readonly IResourceCache _res;

    private static readonly Dictionary<AugmentCategory, Color> CatBg = new()
    {
        [AugmentCategory.Red]    = Color.FromHex("#1A0000"),
        [AugmentCategory.Blue]   = Color.FromHex("#00011A"),
        [AugmentCategory.Green]  = Color.FromHex("#142400"),
        [AugmentCategory.Yellow] = Color.FromHex("#242100"),
        [AugmentCategory.Purple] = Color.FromHex("#160024"),
    };

    private static readonly Dictionary<AugmentCategory, Color> CatAccent = new()
    {
        [AugmentCategory.Red]    = Color.FromHex("#FF5252"),
        [AugmentCategory.Blue]   = Color.FromHex("#4FC3F7"),
        [AugmentCategory.Green]  = Color.FromHex("#69F0AE"),
        [AugmentCategory.Yellow] = Color.FromHex("#FFD740"),
        [AugmentCategory.Purple] = Color.FromHex("#CE93D8"),
    };

    private static readonly Dictionary<AugmentCategory, string> CatLabel = new()
    {
        [AugmentCategory.Red]    = "OFFENSE",
        [AugmentCategory.Blue]   = "DEFENSE",
        [AugmentCategory.Green]  = "UTILITY",
        [AugmentCategory.Yellow] = "ECONOMY",
        [AugmentCategory.Purple] = "HYBRID",
    };

    private static readonly AugmentCategory[] CatOrder =
    [
        AugmentCategory.Red, AugmentCategory.Blue, AugmentCategory.Green,
        AugmentCategory.Yellow, AugmentCategory.Purple,
    ];

    private const int GridColumns = 7;
    private const int CellSize    = 64;

    public event Action<FSBuyAugmentMessage>? OnBuyAugment;
    public event Action<FSEquipAugmentMessage>? OnEquipAugment;
    public event Action<FSUnequipAugmentMessage>? OnUnequipAugment;
    public event Action<FSSaveLoadoutMessage>? OnSaveLoadout;
    public event Action<FSLoadLoadoutMessage>? OnLoadLoadout;
    public event Action? OnPrestigeRequested;

    public AugmentShopWindow()
    {
        RobustXamlLoader.Load(this);
        _res = IoCManager.Resolve<IResourceCache>();

        // Tab titles
        ShopTabs.SetTabTitle(0, "Augments");
        ShopTabs.SetTabTitle(1, "Prestige");

        // Category filter buttons
        FilterAll.OnPressed    += _ => SetFilter(null);
        FilterRed.OnPressed    += _ => SetFilter(AugmentCategory.Red);
        FilterBlue.OnPressed   += _ => SetFilter(AugmentCategory.Blue);
        FilterGreen.OnPressed  += _ => SetFilter(AugmentCategory.Green);
        FilterYellow.OnPressed += _ => SetFilter(AugmentCategory.Yellow);
        FilterPurple.OnPressed += _ => SetFilter(AugmentCategory.Purple);
        FilterAll.Pressed = true;

        SearchBar.OnTextChanged += _ => { _search = SearchBar.Text; RebuildGrid(); };

        UpgradeButton.OnPressed += _ =>
        {
            if (_selectedId != null)
                OnBuyAugment?.Invoke(new FSBuyAugmentMessage { AugmentId = _selectedId });
        };

        EquipButton.OnPressed += _ =>
        {
            if (_selectedId == null || _state == null) return;
            var target = _selectedSlot;
            if (!target.HasValue || !string.IsNullOrEmpty(_state.Slots[target.Value]))
            {
                for (var i = 0; i < FSAugmentDef.SlotCount; i++)
                {
                    if (string.IsNullOrEmpty(_state.Slots[i])) { target = i; break; }
                }
            }
            if (target.HasValue)
                OnEquipAugment?.Invoke(new FSEquipAugmentMessage { AugmentId = _selectedId, SlotIndex = target.Value });
        };

        UnequipButton.OnPressed += _ =>
        {
            if (_selectedId == null || _state == null) return;
            var slotIdx = _selectedSlot;
            if (!slotIdx.HasValue)
            {
                for (var i = 0; i < FSAugmentDef.SlotCount; i++)
                    if (_state.Slots[i] == _selectedId) { slotIdx = i; break; }
            }
            if (slotIdx.HasValue)
                OnUnequipAugment?.Invoke(new FSUnequipAugmentMessage { SlotIndex = slotIdx.Value });
        };

        SaveLoadout0.OnPressed += _ => OnSaveLoadout?.Invoke(new FSSaveLoadoutMessage { LoadoutIndex = 0 });
        LoadLoadout0.OnPressed += _ => OnLoadLoadout?.Invoke(new FSLoadLoadoutMessage { LoadoutIndex = 0 });
        SaveLoadout1.OnPressed += _ => OnSaveLoadout?.Invoke(new FSSaveLoadoutMessage { LoadoutIndex = 1 });
        LoadLoadout1.OnPressed += _ => OnLoadLoadout?.Invoke(new FSLoadLoadoutMessage { LoadoutIndex = 1 });
        SaveLoadout2.OnPressed += _ => OnSaveLoadout?.Invoke(new FSSaveLoadoutMessage { LoadoutIndex = 2 });
        LoadLoadout2.OnPressed += _ => OnLoadLoadout?.Invoke(new FSLoadLoadoutMessage { LoadoutIndex = 2 });

        PrestigeButton.OnPressed += _ => ShowPrestigeConfirmation();
    }

    public void UpdateState(FSAugmentsStateEvent ev)
    {
        _state = ev;
        ApLabel.Text = ev.AugmentPoints.ToString("N0");
        RebuildSlots();
        RebuildGrid();
        RefreshInfo();
    }

    public void UpdateLeveling(int level, int prestige)
    {
        _playerLevel = level;
        _prestigeLevel = prestige;
        RefreshPrestigeTab();
    }

    private void SetFilter(AugmentCategory? cat)
    {
        _filterCategory = cat;
        FilterAll.Pressed    = cat == null;
        FilterRed.Pressed    = cat == AugmentCategory.Red;
        FilterBlue.Pressed   = cat == AugmentCategory.Blue;
        FilterGreen.Pressed  = cat == AugmentCategory.Green;
        FilterYellow.Pressed = cat == AugmentCategory.Yellow;
        FilterPurple.Pressed = cat == AugmentCategory.Purple;
        RebuildGrid();
    }

    private Texture? GetAugmentIcon(string augmentId, int level)
    {
        var name = augmentId.ToLowerInvariant();

        if (TryLoadTexture($"/Textures/_FinalStand/Interface/Augments/{name}level{level}.png", out var tex))
            return tex;
        if (TryLoadTexture($"/Textures/_FinalStand/Interface/Augments/{name}level0.png", out tex))
            return tex;
        if (TryLoadTexture("/Textures/_FinalStand/Interface/Augments/stoppingpowerlevel0.png", out tex))
            return tex;

        Logger.Warning($"[AugmentShop] No icon found for augment '{augmentId}' level {level}.");
        return null;
    }

    private bool TryLoadTexture(string path, out Texture? texture)
    {
        if (_res.TryGetResource<TextureResource>(new ResPath(path), out var res))
        {
            texture = res!.Texture;
            return true;
        }
        texture = null;
        return false;
    }

    private Texture? GetSlotIcon(string augmentId)
    {
        if (string.IsNullOrEmpty(augmentId)) return null;
        var level = _state?.Levels.TryGetValue(augmentId, out var l) == true ? l : 0;
        return GetAugmentIcon(augmentId, level);
    }

    private void RebuildSlots()
    {
        SlotsRow.RemoveAllChildren();
        if (_state == null) return;

        for (var i = 0; i < FSAugmentDef.SlotCount; i++)
        {
            var idx      = i;
            var slotId   = _state.Slots[i];
            var isEmpty  = string.IsNullOrEmpty(slotId);
            var isSelected = _selectedSlot == idx;

            Color borderColor;
            if (isEmpty)
                borderColor = Color.FromHex("#444444");
            else if (FSAugmentDef.All.TryGetValue(slotId!, out var slotDef))
                borderColor = CatAccent[slotDef.Category];
            else
                borderColor = Color.FromHex("#666666");

            if (isSelected)
                borderColor = Color.White;

            var btn = new ContainerButton
            {
                SetWidth  = 40,
                SetHeight = 40,
                Margin    = new Thickness(0, 0, 3, 0),
                ToolTip   = isEmpty
                    ? "Empty Slot"
                    : (FSAugmentDef.All.TryGetValue(slotId!, out var ttDef) ? ttDef.Name : slotId),
                StyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.Transparent },
            };

            var layers = new LayoutContainer { HorizontalExpand = true, VerticalExpand = true };

            // Layer 0: background
            var bgPanel = new PanelContainer
            {
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = isEmpty ? Color.Transparent : Color.FromHex("#1A1A1A"),
                },
            };
            LayoutContainer.SetAnchorPreset(bgPanel, LayoutContainer.LayoutPreset.Wide);
            layers.AddChild(bgPanel);

            // Layer 1: icon fills the full slot
            if (!isEmpty)
            {
                var icon = GetSlotIcon(slotId!);
                if (icon != null)
                {
                    var tex = new TextureRect
                    {
                        Texture = icon,
                        Stretch = TextureRect.StretchMode.Scale,
                    };
                    LayoutContainer.SetAnchorPreset(tex, LayoutContainer.LayoutPreset.Wide);
                    layers.AddChild(tex);
                }
            }

            // Layer 2: border drawn on top of the icon
            var borderPanel = new PanelContainer
            {
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = Color.Transparent,
                    BorderColor = borderColor,
                    BorderThickness = new Thickness(isSelected ? 2 : 1),
                },
            };
            LayoutContainer.SetAnchorPreset(borderPanel, LayoutContainer.LayoutPreset.Wide);
            layers.AddChild(borderPanel);

            btn.AddChild(layers);

            btn.OnPressed += _ =>
            {
                if (!isEmpty)
                {
                    _selectedSlot = idx;
                    _selectedId   = slotId;
                    RefreshInfo();
                    RebuildSlots();
                    RebuildGrid();
                }
                else if (_selectedId != null && _state != null && !_state.Slots.Contains(_selectedId))
                {
                    OnEquipAugment?.Invoke(new FSEquipAugmentMessage { AugmentId = _selectedId, SlotIndex = idx });
                }
                else
                {
                    _selectedSlot = null;
                    RefreshInfo();
                    RebuildSlots();
                }
            };

            SlotsRow.AddChild(btn);
        }
    }

    private void RebuildGrid()
    {
        AugmentGrid.RemoveAllChildren();
        if (_state == null) return;

        var search = _search.ToLowerInvariant();

        var first = true;
        foreach (var cat in CatOrder)
        {
            if (_filterCategory.HasValue && cat != _filterCategory.Value) continue;

            // Gather matching augments for this category
            var defs = FSAugmentDef.All.Values
                .Where(d => d.Category == cat)
                .Where(d => search.Length == 0 ||
                            d.Name.ToLowerInvariant().Contains(search) ||
                            d.Description.ToLowerInvariant().Contains(search))
                .ToList();

            if (defs.Count == 0) continue;

            if (!first)
            {
                var sep = new PanelContainer { HorizontalExpand = true, SetHeight = 1, Margin = new Thickness(0, 2, 0, 2) };
                sep.PanelOverride = new StyleBoxFlat { BackgroundColor = CatBg[cat].WithAlpha(0.6f) };
                AugmentGrid.AddChild(sep);
            }
            first = false;

            var sectionBg = new PanelContainer { HorizontalExpand = true };
            sectionBg.PanelOverride = new StyleBoxFlat { BackgroundColor = CatBg[cat] };

            var sectionVBox = new BoxContainer
            {
                Orientation     = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin           = new Thickness(6, 4, 6, 6),
            };

            var catLbl = new Label
            {
                Text     = CatLabel[cat],
                Modulate = CatAccent[cat],
                Margin   = new Thickness(0, 0, 0, 4),
            };
            sectionVBox.AddChild(catLbl);

            var grid = new GridContainer
            {
                Columns          = GridColumns,
                HorizontalExpand = true,
            };

            foreach (var def in defs)
            {
                var level = _state.Levels.TryGetValue(def.Id, out var lvl) ? lvl : 0;
                grid.AddChild(BuildCell(def, level));
            }

            sectionVBox.AddChild(grid);
            sectionBg.AddChild(sectionVBox);
            AugmentGrid.AddChild(sectionBg);
        }
    }

    private Control BuildCell(FSAugmentDef def, int level)
    {
        var accent     = CatAccent[def.Category];
        var bg         = CatBg[def.Category];
        var isSelected = _selectedId == def.Id;
        var isMax      = level == FSAugmentDef.MaxLevel;

        // Background opacity by level
        var bgAlpha = level switch
        {
            0 => 0f,
            1 => 0.4f,
            2 => 0.6f,
            3 => 0.8f,
            _ => 1.0f,
        };

        // Border brightness by level
        var borderAlpha = level switch
        {
            0 => 0f,
            1 => 0.5f,
            2 => 0.65f,
            3 => 0.82f,
            _ => 1.0f,
        };

        var outer = new ContainerButton
        {
            SetWidth  = CellSize + 6,
            SetHeight = CellSize + 6,
            Margin    = new Thickness(2),
            ToolTip   = def.Name,
            StyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.Transparent },
        };

        // Layer stack: bg → icon → border → badge.
        // Border is a sibling of the icon (not its parent) so the icon fills the full cell.
        var layers = new LayoutContainer
        {
            HorizontalExpand = true,
            VerticalExpand   = true,
        };

        // Layer 0: category background tint
        var bgPanel = new PanelContainer();
        LayoutContainer.SetAnchorPreset(bgPanel, LayoutContainer.LayoutPreset.Wide);
        layers.AddChild(bgPanel);

        // Layer 1: icon (fills the full cell, behind the border)
        var icon = GetAugmentIcon(def.Id, level);
        if (icon != null)
        {
            var tex = new TextureRect
            {
                Texture = icon,
                Stretch = TextureRect.StretchMode.Scale,
            };
            LayoutContainer.SetAnchorPreset(tex, LayoutContainer.LayoutPreset.Wide);
            layers.AddChild(tex);
        }
        else
        {
            var q = new Label
            {
                Text = "?",
                Modulate = accent,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                HorizontalExpand = true,
                VerticalExpand = true,
            };
            LayoutContainer.SetAnchorPreset(q, LayoutContainer.LayoutPreset.Wide);
            layers.AddChild(q);
        }

        // Layer 2: border overlay drawn on top of the icon
        var borderPanel = new PanelContainer();
        LayoutContainer.SetAnchorPreset(borderPanel, LayoutContainer.LayoutPreset.Wide);
        layers.AddChild(borderPanel);

        void ApplyBg(bool hovering)
        {
            var currentBg = level > 0 ? bg.WithAlpha(bgAlpha + (hovering ? 0.15f : 0f)) : Color.Transparent;
            bgPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = currentBg };

            var border = new StyleBoxFlat { BackgroundColor = Color.Transparent };
            if (isSelected)
            {
                border.BorderColor = Color.White;
                border.BorderThickness = new Thickness(2);
            }
            else if (level > 0)
            {
                border.BorderColor = accent.WithAlpha(borderAlpha);
                border.BorderThickness = new Thickness(1);
            }
            borderPanel.PanelOverride = border;
        }
        ApplyBg(false);

        // Layer 3: MAX badge on top
        if (isMax)
        {
            var badge = new Label
            {
                Text = "MAX",
                Modulate = Color.FromHex("#FFD700"),
                Margin = new Thickness(0, 0, 2, 1),
            };
            LayoutContainer.SetAnchorPreset(badge, LayoutContainer.LayoutPreset.BottomRight);
            LayoutContainer.SetGrowHorizontal(badge, LayoutContainer.GrowDirection.Begin);
            LayoutContainer.SetGrowVertical(badge, LayoutContainer.GrowDirection.Begin);
            layers.AddChild(badge);
        }

        outer.AddChild(layers);

        outer.OnMouseEntered += _ => ApplyBg(true);
        outer.OnMouseExited  += _ => ApplyBg(false);

        outer.OnPressed += _ =>
        {
            _selectedId   = def.Id;
            _selectedSlot = null;
            RefreshInfo();
            RebuildGrid();
            RebuildSlots();
        };

        return outer;
    }

    private void RefreshInfo()
    {
        if (_selectedId == null || !FSAugmentDef.All.TryGetValue(_selectedId, out var def))
        {
            SelectedAugmentIcon.Texture    = null;
            SelectedNameLabel.Text         = "—";
            SelectedLevelLabel.Text        = "";
            SelectedCategoryLabel.Text     = "";
            SelectedDescLabel.SetMessage("");
            SelectedEffectLabel.Text       = "";
            SelectedNextEffectLabel.Text   = "";
            SelectedCostLabel.Text         = "";
            UpgradeButton.Text             = "Unlock / Upgrade";
            UpgradeButton.Disabled         = true;
            EquipButton.Disabled           = true;
            UnequipButton.Disabled         = true;
            return;
        }

        var level      = _state?.Levels.TryGetValue(def.Id, out var lvl) == true ? lvl : 0;
        var accent     = CatAccent[def.Category];

        SelectedAugmentIcon.Texture = GetAugmentIcon(def.Id, level);
        SelectedAugmentIcon.Stretch = TextureRect.StretchMode.KeepAspectCentered;

        SelectedNameLabel.Text         = def.Name;
        SelectedLevelLabel.Text        = $"Level {level} / {FSAugmentDef.MaxLevel}";
        SelectedCategoryLabel.Text     = CatLabel[def.Category];
        SelectedCategoryLabel.Modulate = accent;
        SelectedDescLabel.SetMessage(def.Description);

        SelectedEffectLabel.Text = level > 0
            ? $"Current: {def.LevelEffects[level - 1]}"
            : "Not yet unlocked.";

        SelectedNextEffectLabel.Text = level < FSAugmentDef.MaxLevel
            ? $"Next: {def.LevelEffects[level]}"
            : "";

        if (level < FSAugmentDef.MaxLevel)
        {
            var cost = FSAugmentDef.CostForUpgrade(level);
            UpgradeButton.Text     = level == 0 ? "Unlock" : $"Upgrade → Lv {level + 1}";
            SelectedCostLabel.Text = $"Cost: {cost} AP";
            UpgradeButton.Disabled = _state == null || _state.AugmentPoints < cost;
        }
        else
        {
            UpgradeButton.Text     = "Max Level";
            SelectedCostLabel.Text = "MAX LEVEL";
            UpgradeButton.Disabled = true;
        }

        var isEquipped = _state?.Slots.Contains(_selectedId) == true;
        var hasEmpty   = _state?.Slots.Any(string.IsNullOrEmpty) == true;

        EquipButton.Disabled   = level <= 0 || isEquipped || !hasEmpty;
        UnequipButton.Disabled = !isEquipped;
    }

    private void RefreshPrestigeTab()
    {
        var eligible = _playerLevel >= 50;

        PrestigeLevelLabel.Text = _prestigeLevel > 0
            ? $"Prestige {_prestigeLevel} — Level {_playerLevel}"
            : $"Prestige 0 — Level {_playerLevel}";

        var bonus = _prestigeLevel * 20;
        PrestigeXpBonusLabel.Text = $"Current XP Bonus: +{bonus}%";

        PrestigeRequirementLabel.Text    = "Reach Level 50 to Prestige";
        PrestigeRequirementLabel.Modulate = eligible
            ? CatAccent[AugmentCategory.Yellow]
            : Color.FromHex("#777777");

        PrestigeButton.Disabled = !eligible;
        PrestigeButton.Modulate = eligible
            ? CatAccent[AugmentCategory.Yellow]
            : Color.FromHex("#555555");
    }

    private void ShowPrestigeConfirmation()
    {
        var dialog = new FancyWindow
        {
            Title     = "Confirm Prestige",
            Resizable = false,
            SetSize   = new Vector2(400, 200),
        };

        var vbox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin      = new Thickness(12),
        };

        vbox.AddChild(new Label
        {
            Text     = "Prestige? Your level resets to 1.",
            Margin   = new Thickness(0, 0, 0, 4),
        });
        vbox.AddChild(new Label
        {
            Text     = "Augments and points are kept.",
            Margin   = new Thickness(0, 0, 0, 4),
        });
        vbox.AddChild(new Label
        {
            Text     = "You gain +20% permanent XP bonus.",
            Modulate = CatAccent[AugmentCategory.Yellow],
            Margin   = new Thickness(0, 0, 0, 16),
        });

        var btnRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };

        var confirm = new Button
        {
            Text             = "Confirm",
            HorizontalExpand = true,
            Margin           = new Thickness(0, 0, 6, 0),
        };
        confirm.Modulate = CatAccent[AugmentCategory.Yellow];

        var cancel = new Button
        {
            Text             = "Cancel",
            HorizontalExpand = true,
        };

        confirm.OnPressed += _ =>
        {
            OnPrestigeRequested?.Invoke();
            dialog.Close();
        };
        cancel.OnPressed += _ => dialog.Close();

        btnRow.AddChild(confirm);
        btnRow.AddChild(cancel);
        vbox.AddChild(btnRow);
        dialog.AddChild(vbox);
        dialog.OpenCentered();
    }
}
