using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._FinalStand.Augments;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics;
using Robust.Shared.Utility;

namespace Content.Client._FinalStand.Augments.UI;

[GenerateTypedNameReferences]
public sealed partial class AugmentShopWindow : FancyWindow
{
    private FSAugmentsStateEvent? _state;
    private string? _selectedId;
    private int? _selectedSlot;
    private AugmentCategory? _filterCategory;
    private string _search = "";

    private int _playerLevel = 1;
    private int _prestigeLevel;

    private readonly IResourceCache _res;
    private readonly IClyde _clyde;

    private static readonly TextureLoadParameters LinearParams = new()
    {
        SampleParameters = new TextureSampleParameters { Filter = true, Mipmap = true },
    };
    private readonly Dictionary<string, OwnedTexture> _iconCache = new();

    private static readonly Dictionary<AugmentCategory, Color> CatBg = new()
    {
        [AugmentCategory.Red]    = Color.FromHex("#1A0000"),
        [AugmentCategory.Blue]   = Color.FromHex("#00011A"),
        [AugmentCategory.Green]  = Color.FromHex("#142400"),
        [AugmentCategory.Yellow] = Color.FromHex("#242100"),
        [AugmentCategory.Purple] = Color.FromHex("#160024"),
    };

    private static readonly Dictionary<AugmentCategory, Color> CatAccent = new()
    {
        [AugmentCategory.Red]    = Color.FromHex("#FF5252"),
        [AugmentCategory.Blue]   = Color.FromHex("#4FC3F7"),
        [AugmentCategory.Green]  = Color.FromHex("#69F0AE"),
        [AugmentCategory.Yellow] = Color.FromHex("#FFD740"),
        [AugmentCategory.Purple] = Color.FromHex("#CE93D8"),
    };

    private static readonly Dictionary<AugmentCategory, string> CatLabel = new()
    {
        [AugmentCategory.Red]    = "OFFENSE",
        [AugmentCategory.Blue]   = "DEFENSE",
        [AugmentCategory.Green]  = "UTILITY",
        [AugmentCategory.Yellow] = "ECONOMY",
        [AugmentCategory.Purple] = "HYBRID",
    };

    private static readonly AugmentCategory[] CatOrder =
    [
        AugmentCategory.Red, AugmentCategory.Blue, AugmentCategory.Green,
        AugmentCategory.Yellow, AugmentCategory.Purple,
    ];

    // Level BG colours: index 0 = locked (transparent), 1–4 = progressively more saturated
    private static readonly Dictionary<AugmentCategory, Color[]> LevelBg = new()
    {
        [AugmentCategory.Red]    = [Color.Transparent, Color.FromHex("#590000"), Color.FromHex("#8F0303"), Color.FromHex("#A50101"), Color.FromHex("#C40000")],
        [AugmentCategory.Blue]   = [Color.Transparent, Color.FromHex("#000159"), Color.FromHex("#030A8F"), Color.FromHex("#0212BD"), Color.FromHex("#0426E1")],
        [AugmentCategory.Green]  = [Color.Transparent, Color.FromHex("#005903"), Color.FromHex("#038F07"), Color.FromHex("#01A501"), Color.FromHex("#00C414")],
        [AugmentCategory.Yellow] = [Color.Transparent, Color.FromHex("#575900"), Color.FromHex("#878F03"), Color.FromHex("#96A501"), Color.FromHex("#D7D303")],
        [AugmentCategory.Purple] = [Color.Transparent, Color.FromHex("#330052"), Color.FromHex("#58028C"), Color.FromHex("#7302B8"), Color.FromHex("#9D02FC")],
    };

    private const int GridColumns = 7;
    private const int CellSize    = 64;

    public event Action<FSBuyAugmentMessage>? OnBuyAugment;
    public event Action<FSEquipAugmentMessage>? OnEquipAugment;
    public event Action<FSUnequipAugmentMessage>? OnUnequipAugment;
    public event Action<FSSaveLoadoutMessage>? OnSaveLoadout;
    public event Action<FSLoadLoadoutMessage>? OnLoadLoadout;
    public event Action? OnPrestigeRequested;

    public AugmentShopWindow()
    {
        RobustXamlLoader.Load(this);
        _res   = IoCManager.Resolve<IResourceCache>();
        _clyde = IoCManager.Resolve<IClyde>();

        // Anchor all three layers in the selected-icon stack to fill the LayoutContainer
        LayoutContainer.SetAnchorPreset(SelectedIconCatBg,   LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(SelectedIconLevelBg, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(SelectedAugmentIcon, LayoutContainer.LayoutPreset.Wide);

        ShopTabs.SetTabTitle(0, "Perks");
        ShopTabs.SetTabTitle(1, "Prestige");

        FilterAll.OnPressed    += _ => SetFilter(null);
        FilterRed.OnPressed    += _ => SetFilter(AugmentCategory.Red);
        FilterBlue.OnPressed   += _ => SetFilter(AugmentCategory.Blue);
        FilterGreen.OnPressed  += _ => SetFilter(AugmentCategory.Green);
        FilterYellow.OnPressed += _ => SetFilter(AugmentCategory.Yellow);
        FilterPurple.OnPressed += _ => SetFilter(AugmentCategory.Purple);
        FilterAll.Pressed = true;

        SearchBar.OnTextChanged += _ => { _search = SearchBar.Text; RebuildGrid(); };

        UpgradeButton.OnPressed += _ =>
        {
            if (_selectedId != null)
                OnBuyAugment?.Invoke(new FSBuyAugmentMessage { AugmentId = _selectedId });
        };

        EquipButton.OnPressed += _ =>
        {
            if (_selectedId == null || _state == null) return;
            var target = _selectedSlot;
            if (!target.HasValue || !string.IsNullOrEmpty(_state.Slots[target.Value]))
            {
                for (var i = 0; i < FSAugmentDef.SlotCount; i++)
                {
                    if (string.IsNullOrEmpty(_state.Slots[i])) { target = i; break; }
                }
            }
            if (target.HasValue)
                OnEquipAugment?.Invoke(new FSEquipAugmentMessage { AugmentId = _selectedId, SlotIndex = target.Value });
        };

        UnequipButton.OnPressed += _ =>
        {
            if (_selectedId == null || _state == null) return;
            var slotIdx = _selectedSlot;
            if (!slotIdx.HasValue)
            {
                for (var i = 0; i < FSAugmentDef.SlotCount; i++)
                    if (_state.Slots[i] == _selectedId) { slotIdx = i; break; }
            }
            if (slotIdx.HasValue)
                OnUnequipAugment?.Invoke(new FSUnequipAugmentMessage { SlotIndex = slotIdx.Value });
        };

        SaveLoadout0.OnPressed += _ => OnSaveLoadout?.Invoke(new FSSaveLoadoutMessage { LoadoutIndex = 0 });
        LoadLoadout0.OnPressed += _ => OnLoadLoadout?.Invoke(new FSLoadLoadoutMessage { LoadoutIndex = 0 });
        SaveLoadout1.OnPressed += _ => OnSaveLoadout?.Invoke(new FSSaveLoadoutMessage { LoadoutIndex = 1 });
        LoadLoadout1.OnPressed += _ => OnLoadLoadout?.Invoke(new FSLoadLoadoutMessage { LoadoutIndex = 1 });
        SaveLoadout2.OnPressed += _ => OnSaveLoadout?.Invoke(new FSSaveLoadoutMessage { LoadoutIndex = 2 });
        LoadLoadout2.OnPressed += _ => OnLoadLoadout?.Invoke(new FSLoadLoadoutMessage { LoadoutIndex = 2 });

        PrestigeButton.OnPressed += _ => ShowPrestigeConfirmation();
    }

    public void UpdateState(FSAugmentsStateEvent ev)
    {
        _state = ev;
        ApLabel.Text = ev.AugmentPoints.ToString("N0");
        RebuildSlots();
        RebuildGrid();
        RefreshInfo();
    }

    public void UpdateLeveling(int level, int prestige)
    {
        _playerLevel = level;
        _prestigeLevel = prestige;
        RefreshPrestigeTab();
    }

    private void SetFilter(AugmentCategory? cat)
    {
        _filterCategory = cat;
        FilterAll.Pressed    = cat == null;
        FilterRed.Pressed    = cat == AugmentCategory.Red;
        FilterBlue.Pressed   = cat == AugmentCategory.Blue;
        FilterGreen.Pressed  = cat == AugmentCategory.Green;
        FilterYellow.Pressed = cat == AugmentCategory.Yellow;
        FilterPurple.Pressed = cat == AugmentCategory.Purple;
        RebuildGrid();
    }

    private Texture? GetAugmentIcon(string augmentId)
    {
        if (!FSAugmentDef.All.TryGetValue(augmentId, out var def))
            return null;

        var file = def.IconFile ?? def.Id.ToLowerInvariant();
        var path = $"/Textures/_FinalStand/Interface/Augments/Icons/{file}.png";

        if (_iconCache.TryGetValue(path, out var cached))
            return cached;

        if (_res.TryContentFileRead(path, out var stream))
        {
            using (stream)
            {
                var tex = _clyde.LoadTextureFromPNGStream(stream, path, LinearParams);
                _iconCache[path] = tex;
                return tex;
            }
        }

        Logger.Warning($"[AugmentShop] No icon found for augment '{augmentId}' (looked for {file}.png).");
        return null;
    }

    private Texture? GetSlotIcon(string augmentId)
    {
        if (string.IsNullOrEmpty(augmentId)) return null;
        return GetAugmentIcon(augmentId);
    }

    private void RebuildSlots()
    {
        SlotsRow.RemoveAllChildren();
        var state = _state;
        if (state == null) return;

        for (var i = 0; i < FSAugmentDef.SlotCount; i++)
        {
            var idx      = i;
            var slotId   = state.Slots[i];
            var isEmpty  = string.IsNullOrEmpty(slotId);
            var isSelected = _selectedSlot == idx;

            Color borderColor;
            if (isEmpty)
                borderColor = Color.FromHex("#444444");
            else if (FSAugmentDef.All.TryGetValue(slotId!, out var slotDef))
                borderColor = CatAccent[slotDef.Category];
            else
                borderColor = Color.FromHex("#666666");

            if (isSelected)
                borderColor = Color.White;

            var btn = new ContainerButton
            {
                SetWidth  = 40,
                SetHeight = 40,
                Margin    = new Thickness(0, 0, 3, 0),
                ToolTip   = isEmpty
                    ? "Empty Slot"
                    : (FSAugmentDef.All.TryGetValue(slotId!, out var ttDef) ? ttDef.Name : slotId),
                StyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.Transparent },
            };

            var layers = new LayoutContainer { HorizontalExpand = true, VerticalExpand = true };

            // Layer 1: category bg
            var slotCatPanel = new PanelContainer();
            if (!isEmpty && FSAugmentDef.All.TryGetValue(slotId!, out var slotCatDef))
                slotCatPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = CatBg[slotCatDef.Category] };
            LayoutContainer.SetAnchorPreset(slotCatPanel, LayoutContainer.LayoutPreset.Wide);
            layers.AddChild(slotCatPanel);

            // Layer 2: level bg
            var slotLevelPanel = new PanelContainer();
            if (!isEmpty && FSAugmentDef.All.TryGetValue(slotId!, out var slotLvlDef))
            {
                var slotLevel = state.Levels.TryGetValue(slotId!, out var sl) ? sl : 0;
                slotLevelPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = LevelBg[slotLvlDef.Category][slotLevel] };
            }
            LayoutContainer.SetAnchorPreset(slotLevelPanel, LayoutContainer.LayoutPreset.Wide);
            layers.AddChild(slotLevelPanel);

            // Layer 3: icon texture
            if (!isEmpty)
            {
                var icon = GetSlotIcon(slotId!);
                if (icon != null)
                {
                    var tex = new TextureRect
                    {
                        Texture = icon,
                        Stretch = TextureRect.StretchMode.Scale,
                    };
                    LayoutContainer.SetAnchorPreset(tex, LayoutContainer.LayoutPreset.Wide);
                    layers.AddChild(tex);
                }
            }

            var borderPanel = new PanelContainer
            {
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = Color.Transparent,
                    BorderColor = borderColor,
                    BorderThickness = new Thickness(isSelected ? 2 : 1),
                },
            };
            LayoutContainer.SetAnchorPreset(borderPanel, LayoutContainer.LayoutPreset.Wide);
            layers.AddChild(borderPanel);

            btn.AddChild(layers);

            btn.OnPressed += _ =>
            {
                if (!isEmpty)
                {
                    _selectedSlot = idx;
                    _selectedId   = slotId;
                    RefreshInfo();
                    RebuildSlots();
                    RebuildGrid();
                }
                else if (_selectedId != null && _state != null && !_state.Slots.Contains(_selectedId))
                {
                    OnEquipAugment?.Invoke(new FSEquipAugmentMessage { AugmentId = _selectedId, SlotIndex = idx });
                }
                else
                {
                    _selectedSlot = null;
                    RefreshInfo();
                    RebuildSlots();
                }
            };

            SlotsRow.AddChild(btn);
        }
    }

    private void RebuildGrid()
    {
        AugmentGrid.RemoveAllChildren();
        if (_state == null) return;

        var search = _search.ToLowerInvariant();

        var first = true;
        foreach (var cat in CatOrder)
        {
            if (_filterCategory.HasValue && cat != _filterCategory.Value) continue;

            // Gather matching augments for this category
            var defs = FSAugmentDef.All.Values
                .Where(d => d.Category == cat)
                .Where(d => search.Length == 0 ||
                            d.Name.ToLowerInvariant().Contains(search) ||
                            d.Description.ToLowerInvariant().Contains(search))
                .ToList();

            if (defs.Count == 0) continue;

            if (!first)
            {
                var sep = new PanelContainer { HorizontalExpand = true, SetHeight = 1, Margin = new Thickness(0, 2, 0, 2) };
                sep.PanelOverride = new StyleBoxFlat { BackgroundColor = CatBg[cat].WithAlpha(0.6f) };
                AugmentGrid.AddChild(sep);
            }
            first = false;

            var sectionBg = new PanelContainer { HorizontalExpand = true };
            sectionBg.PanelOverride = new StyleBoxFlat { BackgroundColor = CatBg[cat] };

            var sectionVBox = new BoxContainer
            {
                Orientation     = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin           = new Thickness(6, 4, 6, 6),
            };

            var catLbl = new Label
            {
                Text     = CatLabel[cat],
                Modulate = CatAccent[cat],
                Margin   = new Thickness(0, 0, 0, 4),
            };
            sectionVBox.AddChild(catLbl);

            var grid = new GridContainer
            {
                Columns          = GridColumns,
                HorizontalExpand = true,
            };

            foreach (var def in defs)
            {
                var level = _state.Levels.TryGetValue(def.Id, out var lvl) ? lvl : 0;
                grid.AddChild(BuildCell(def, level));
            }

            sectionVBox.AddChild(grid);
            sectionBg.AddChild(sectionVBox);
            AugmentGrid.AddChild(sectionBg);
        }
    }

    private Control BuildCell(FSAugmentDef def, int level)
    {
        var accent     = CatAccent[def.Category];
        var isSelected = _selectedId == def.Id;
        var isMax      = level == FSAugmentDef.MaxLevel;

        var outer = new ContainerButton
        {
            SetWidth  = CellSize + 6,
            SetHeight = CellSize + 6,
            Margin    = new Thickness(2),
            ToolTip   = def.Name,
            StyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.Transparent },
        };

        var layers = new LayoutContainer
        {
            HorizontalExpand = true,
            VerticalExpand   = true,
        };

        // Layer 1: dark category background (always shown)
        var catPanel = new PanelContainer();
        LayoutContainer.SetAnchorPreset(catPanel, LayoutContainer.LayoutPreset.Wide);
        layers.AddChild(catPanel);

        // Layer 2: level saturation colour (transparent when locked)
        var levelPanel = new PanelContainer();
        LayoutContainer.SetAnchorPreset(levelPanel, LayoutContainer.LayoutPreset.Wide);
        layers.AddChild(levelPanel);

        // Layer 3: icon texture
        var icon = GetAugmentIcon(def.Id);
        if (icon != null)
        {
            var tex = new TextureRect
            {
                Texture = icon,
                Stretch = TextureRect.StretchMode.Scale,
            };
            LayoutContainer.SetAnchorPreset(tex, LayoutContainer.LayoutPreset.Wide);
            layers.AddChild(tex);
        }
        else
        {
            var q = new Label
            {
                Text = "?",
                Modulate = accent,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                HorizontalExpand = true,
                VerticalExpand = true,
            };
            LayoutContainer.SetAnchorPreset(q, LayoutContainer.LayoutPreset.Wide);
            layers.AddChild(q);
        }

        // Layer 4: border overlay
        var borderPanel = new PanelContainer();
        LayoutContainer.SetAnchorPreset(borderPanel, LayoutContainer.LayoutPreset.Wide);
        layers.AddChild(borderPanel);

        void ApplyBg(bool hovering)
        {
            var catColor = hovering ? CatBg[def.Category].WithAlpha(0.85f) : CatBg[def.Category];
            catPanel.PanelOverride   = new StyleBoxFlat { BackgroundColor = catColor };
            levelPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = LevelBg[def.Category][level] };

            var border = new StyleBoxFlat { BackgroundColor = Color.Transparent };
            if (isSelected)
            {
                border.BorderColor     = Color.White;
                border.BorderThickness = new Thickness(2);
            }
            else if (level > 0)
            {
                border.BorderColor     = accent;
                border.BorderThickness = new Thickness(1);
            }
            borderPanel.PanelOverride = border;
        }
        ApplyBg(false);

        if (isMax)
        {
            var badge = new Label
            {
                Text = "MAX",
                Modulate = Color.FromHex("#FFD700"),
                Margin = new Thickness(0, 0, 2, 1),
            };
            LayoutContainer.SetAnchorPreset(badge, LayoutContainer.LayoutPreset.BottomRight);
            LayoutContainer.SetGrowHorizontal(badge, LayoutContainer.GrowDirection.Begin);
            LayoutContainer.SetGrowVertical(badge, LayoutContainer.GrowDirection.Begin);
            layers.AddChild(badge);
        }

        outer.AddChild(layers);

        outer.OnMouseEntered += _ => ApplyBg(true);
        outer.OnMouseExited  += _ => ApplyBg(false);

        outer.OnPressed += _ =>
        {
            _selectedId   = def.Id;
            _selectedSlot = null;
            RefreshInfo();
            RebuildGrid();
            RebuildSlots();
        };

        return outer;
    }

    private void RefreshInfo()
    {
        if (_selectedId == null || !FSAugmentDef.All.TryGetValue(_selectedId, out var def))
        {
            SelectedAugmentIcon.Texture    = null;
            SelectedIconCatBg.PanelOverride   = null;
            SelectedIconLevelBg.PanelOverride = null;
            SelectedNameLabel.Text         = "—";
            SelectedLevelLabel.Text        = "";
            SelectedCategoryLabel.Text     = "";
            SelectedDescLabel.SetMessage("");
            SelectedEffectLabel.Text       = "";
            SelectedNextEffectLabel.Text   = "";
            SelectedCostLabel.Text         = "";
            UpgradeButton.Text             = "Unlock / Upgrade";
            UpgradeButton.Disabled         = true;
            EquipButton.Disabled           = true;
            UnequipButton.Disabled         = true;
            return;
        }

        var level      = _state?.Levels.TryGetValue(def.Id, out var lvl) == true ? lvl : 0;
        var accent     = CatAccent[def.Category];

        SelectedAugmentIcon.Texture = GetAugmentIcon(def.Id);
        SelectedAugmentIcon.Stretch = TextureRect.StretchMode.KeepAspectCentered;
        SelectedIconCatBg.PanelOverride   = new StyleBoxFlat { BackgroundColor = CatBg[def.Category] };
        SelectedIconLevelBg.PanelOverride = new StyleBoxFlat { BackgroundColor = LevelBg[def.Category][level] };

        SelectedNameLabel.Text         = def.Name;
        SelectedLevelLabel.Text        = $"Level {level} / {FSAugmentDef.MaxLevel}";
        SelectedCategoryLabel.Text     = CatLabel[def.Category];
        SelectedCategoryLabel.Modulate = accent;
        SelectedDescLabel.SetMessage(def.Description);

        SelectedEffectLabel.Text = level > 0
            ? $"Current: {def.LevelEffects[level - 1]}"
            : "Not yet unlocked.";

        SelectedNextEffectLabel.Text = level < FSAugmentDef.MaxLevel
            ? $"Next: {def.LevelEffects[level]}"
            : "";

        if (level < FSAugmentDef.MaxLevel)
        {
            var cost = FSAugmentDef.CostForUpgrade(level);
            UpgradeButton.Text     = level == 0 ? "Unlock" : $"Upgrade → Lv {level + 1}";
            SelectedCostLabel.Text = $"Cost: {cost} AP";
            UpgradeButton.Disabled = _state == null || _state.AugmentPoints < cost;
        }
        else
        {
            UpgradeButton.Text     = "Max Level";
            SelectedCostLabel.Text = "MAX LEVEL";
            UpgradeButton.Disabled = true;
        }

        var isEquipped = _state?.Slots.Contains(_selectedId) == true;
        var hasEmpty   = _state?.Slots.Any(string.IsNullOrEmpty) == true;

        EquipButton.Disabled   = level <= 0 || isEquipped || !hasEmpty;
        UnequipButton.Disabled = !isEquipped;
    }

    private void RefreshPrestigeTab()
    {
        var eligible = _playerLevel >= 50;

        PrestigeLevelLabel.Text = _prestigeLevel > 0
            ? $"Prestige {_prestigeLevel} — Level {_playerLevel}"
            : $"Prestige 0 — Level {_playerLevel}";

        var bonus = _prestigeLevel * 20;
        PrestigeXpBonusLabel.Text = $"Current XP Bonus: +{bonus}%";

        PrestigeRequirementLabel.Text    = "Reach Level 50 to Prestige";
        PrestigeRequirementLabel.Modulate = eligible
            ? CatAccent[AugmentCategory.Yellow]
            : Color.FromHex("#777777");

        PrestigeButton.Disabled = !eligible;
        PrestigeButton.Modulate = eligible
            ? CatAccent[AugmentCategory.Yellow]
            : Color.FromHex("#555555");
    }

    private void ShowPrestigeConfirmation()
    {
        var dialog = new FancyWindow
        {
            Title     = "Confirm Prestige",
            Resizable = false,
            SetSize   = new Vector2(400, 200),
        };

        var vbox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin      = new Thickness(12),
        };

        vbox.AddChild(new Label
        {
            Text     = "Prestige? Your level resets to 1.",
            Margin   = new Thickness(0, 0, 0, 4),
        });
        vbox.AddChild(new Label
        {
            Text     = "Perks and points are kept.",
            Margin   = new Thickness(0, 0, 0, 4),
        });
        vbox.AddChild(new Label
        {
            Text     = "You gain +20% permanent XP bonus.",
            Modulate = CatAccent[AugmentCategory.Yellow],
            Margin   = new Thickness(0, 0, 0, 16),
        });

        var btnRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };

        var confirm = new Button
        {
            Text             = "Confirm",
            HorizontalExpand = true,
            Margin           = new Thickness(0, 0, 6, 0),
        };
        confirm.Modulate = CatAccent[AugmentCategory.Yellow];

        var cancel = new Button
        {
            Text             = "Cancel",
            HorizontalExpand = true,
        };

        confirm.OnPressed += _ =>
        {
            OnPrestigeRequested?.Invoke();
            dialog.Close();
        };
        cancel.OnPressed += _ => dialog.Close();

        btnRow.AddChild(confirm);
        btnRow.AddChild(cancel);
        vbox.AddChild(btnRow);
        dialog.AddChild(vbox);
        dialog.OpenCentered();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (!disposing) return;
        foreach (var tex in _iconCache.Values)
            tex.Dispose();
        _iconCache.Clear();
    }
}
