using Content.Shared._FinalStand.Bags;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._FinalStand.Bags.UI;

[GenerateTypedNameReferences]
public sealed partial class BagShopWindow : DefaultWindow
{
    public event Action<string>? OnBuyPressed;

    public BagShopWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(FSBagShopState state)
    {
        CreditsLabel.Text = $"${state.Credits:N0}";
        EntryListContainer.RemoveAllChildren();

        foreach (var entry in state.Entries)
            EntryListContainer.AddChild(BuildRow(entry, state.Credits));
    }

    private Control BuildRow(FSBagShopEntryState entry, int credits)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 0, 0, 6),
        };

        var text = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        };
        text.AddChild(new Label { Text = entry.Name, StyleClasses = { "LabelHeading" } });

        if (!string.IsNullOrWhiteSpace(entry.Description))
            text.AddChild(new Label { Text = entry.Description, StyleClasses = { "FSMuted" } });

        row.AddChild(text);

        var buy = new Button
        {
            Text = $"${entry.Price:N0}",
            MinWidth = 120,
            MinHeight = 34,
            VerticalAlignment = VAlignment.Center,
            Disabled = credits < entry.Price,
        };
        buy.OnPressed += _ => OnBuyPressed?.Invoke(entry.ProtoId);
        row.AddChild(buy);

        return row;
    }
}
