using Content.Client.UserInterface.Controls;
using Content.Shared._FinalStand.CCC;
using Content.Shared._FinalStand.GameTicking;
using Content.Shared._FinalStand.ReadyCheck;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Log;

namespace Content.Client._FinalStand.CCC.UI;

[GenerateTypedNameReferences]
public sealed partial class CCCWindow : FancyWindow
{
    public event Action? OnStartWavePressed;
    public event Action<string>? OnBroadcastPressed;

    // Prototype ID → icon texture path
    private static readonly Dictionary<string, string> ZombieIconPaths = new()
    {
        ["FSZombieArmoured"] = "/Textures/_FinalStand/Mobs/ZombieIcons/armoured-zombie.png",
        ["FSZombieBerserker"] = "/Textures/_FinalStand/Mobs/ZombieIcons/berserker.png",
        ["FSZombieDestroyer"] = "/Textures/_FinalStand/Mobs/ZombieIcons/destroyer.png",
        ["FSZombieGiant"]    = "/Textures/_FinalStand/Mobs/ZombieIcons/giantzombie.png",
        ["FSZombieRunner"]   = "/Textures/_FinalStand/Mobs/ZombieIcons/runner.png",
        // TODO(finalstand): verify zombie type to icon mapping for boomer/flamethrower/tesla/wraith when prototypes are added
    };

    // Prototype ID → human-readable tooltip name
    private static readonly Dictionary<string, string> ZombieDisplayNames = new()
    {
        ["FSZombieArmoured"] = "Armoured Zombie",
        ["FSZombieBerserker"] = "Berserker",
        ["FSZombieDestroyer"] = "Destroyer",
        ["FSZombieGiant"]    = "Giant Zombie",
        ["FSZombieNormal"]   = "Zombie",
        ["FSZombieRunner"]   = "Runner",
    };

    public CCCWindow()
    {
        RobustXamlLoader.Load(this);
        StartWaveButton.OnPressed += _ => OnStartWavePressed?.Invoke();
        BroadcastButton.OnPressed += _ =>
        {
            var text = BroadcastInput.Text.Trim();
            if (!string.IsNullOrEmpty(text))
            {
                OnBroadcastPressed?.Invoke(text);
                BroadcastInput.Clear();
            }
        };

        MapViewButton.OnPressed += _ => { MapPanel.Visible = true; PowerPanel.Visible = false; };
        PowerViewButton.OnPressed += _ => { MapPanel.Visible = false; PowerPanel.Visible = true; };
    }

    public void InitMaps(EntityUid? gridUid, EntityUid? powerOwner)
    {
        CccNavMap.MapUid = gridUid;
        CccNavMap.ForceNavMapUpdate();

        CccPowerMap.Owner = powerOwner;
        CccPowerMap.MapUid = gridUid;
        if (powerOwner.HasValue)
            CccPowerMap.ForceNavMapUpdate();
    }

    public void UpdateState(CCCBoundUserInterfaceState state, bool isCaptain)
    {
        WaveNumberLabel.Text = state.WaveNumber.ToString();
        FactionLabel.Text = state.FactionDisplay;
        ModifierLabel.Text = state.WaveModifier;
        EnemyEstLabel.Text = state.EstimatedEnemyCount.ToString();

        PhaseLabel.Text = state.CurrentPhase == WavePhase.Prep ? "PREP" : "COMBAT";
        PhaseLabel.Modulate = state.CurrentPhase == WavePhase.Prep
            ? Color.FromHex("#AAFFAA")
            : Color.FromHex("#FF8888");

        var mins = (int)state.SecondsToPhaseEnd / 60;
        var secs = (int)state.SecondsToPhaseEnd % 60;
        CountdownLabel.Text = $"{mins}:{secs:D2}";

        AliveLabel.Text = state.AliveEnemyCount.ToString();
        TotalLabel.Text = state.EstimatedEnemyCount.ToString();
        SpawnersLabel.Text = state.ActiveSpawnerCount.ToString();

        var cccHp = Math.Max(0, state.CCCMaxHealth - state.CCCCurrentDamage);
        var cccPct = state.CCCMaxHealth > 0 ? (int)(100f * cccHp / state.CCCMaxHealth) : 0;
        CCCHealthLabel.Text = $"{cccHp} / {state.CCCMaxHealth} ({cccPct}%)";

        var notPrep    = state.CurrentPhase != WavePhase.Prep;
        var notReady   = state.ReadyCount < 1;
        var notCaptain = !isCaptain;
        StartWaveButton.Disabled = notPrep || notReady || notCaptain;
        StartWaveButton.ToolTip =
            (!notPrep && notReady)              ? "Awaiting department readiness" :
            (!notPrep && !notReady && notCaptain) ? "Only the Captain can start the wave" :
            null;

        RebuildDeptGrid(state.DepartmentStatus);
        RebuildZombieIcons(state.NextWaveEnemyTypes);
    }

    private void RebuildZombieIcons(List<string> types)
    {
        ZombieIconsContainer.RemoveAllChildren();

        if (types.Count == 0)
        {
            ZombieIconsContainer.Visible = false;
            return;
        }

        var cache = IoCManager.Resolve<IResourceCache>();
        var anyAdded = false;

        foreach (var protoId in types)
        {
            if (!ZombieIconPaths.TryGetValue(protoId, out var texPath))
                continue;

            if (!cache.TryGetResource<TextureResource>(texPath, out var texRes))
            {
                Logger.WarningS("ccc-window", $"Zombie icon not found: {texPath}");
                continue;
            }

            var displayName = ZombieDisplayNames.TryGetValue(protoId, out var n) ? n : protoId;
            ZombieIconsContainer.AddChild(new TextureRect
            {
                Texture = texRes.Texture,
                SetWidth = 64,
                SetHeight = 64,
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                ToolTip = displayName,
                Margin = new Thickness(0, 0, 4, 0),
            });
            anyAdded = true;
        }

        ZombieIconsContainer.Visible = anyAdded;
    }

    private void RebuildDeptGrid(Dictionary<string, ReadyStatus> statuses)
    {
        DeptContainer.RemoveAllChildren();
        foreach (var (code, status) in statuses)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };

            var codeLabel = new Label
            {
                Text = code,
                SetWidth = 48,
                Modulate = Color.FromHex("#DDDDDD"),
            };

            var (statusText, statusColor) = status switch
            {
                ReadyStatus.Ready => ("READY", "#44FF44"),
                ReadyStatus.NotReady => ("NOT RDY", "#FF4444"),
                _ => ("NO RESP", "#888888"),
            };

            var statusLabel = new Label
            {
                Text = statusText,
                Modulate = Color.FromHex(statusColor),
            };

            row.AddChild(codeLabel);
            row.AddChild(statusLabel);
            DeptContainer.AddChild(row);
        }
    }
}
