using Content.Client._FinalStand.Stylesheets;
using Content.Client.Changelog;
using Content.Client.Credits;
using Content.Client.Info;
using Content.Client.Message;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Content.Client.UserInterface.Systems.Guidebook;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
        [Dependency] private readonly IConfigurationManager _cfg = default!;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            Stylesheet = new FSLobbyStylesheet(UserInterfaceManager, IoCManager.Resolve<IResourceCache>()).Stylesheet;
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();
            CreditsButton.OnPressed += _ => new CreditsWindow().Open();

            // Button only ever tags its internal Label with the base "Button" style class, so these
            // per-button label colors have to be set directly rather than through a StyleClasses selector:
            // active nav tab is gold, and Leave stays light so it reads on the dark-red button.
            NavLobbyButton.Label.FontColorOverride = Robust.Shared.Maths.Color.FromHex("#CFA550");
            LeaveButton.Label.FontColorOverride = Robust.Shared.Maths.Color.FromHex("#D0D0D0");

            NavRulesButton.OnPressed += _ => new RulesAndInfoWindow().Open();
            NavDiscordButton.OnPressed += _ =>
                IoCManager.Resolve<IUriOpener>().OpenUri(_cfg.GetCVar(CCVars.InfoLinksDiscord));
            NavGuidebookButton.OnPressed += _ =>
                UserInterfaceManager.GetUIController<GuidebookUIController>().ToggleGuidebook();
            NavChangelogButton.OnPressed += _ =>
                UserInterfaceManager.GetUIController<ChangelogUIController>().ToggleWindow();

            CollapseButton.OnPressed += _ => TogglePanel(false);
            ExpandButton.OnPressed += _ => TogglePanel(true);
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;

                    var actualWidth = (float) UserInterfaceManager.RootControl.PixelWidth;
                    var setupWidth = (float) LeftSide.PixelWidth;

                    if (1 - (setupWidth / actualWidth) > 0.30)
                    {
                        RightSide.Visible = false;
                    }

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();

                    break;
            }
        }

        private void TogglePanel(bool value)
        {
            RightSide.Visible = value;
            ExpandPanel.Visible = !value;
        }

        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,
            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup
        }
    }
}
