using Content.Client._FinalStand.Perks;
using Content.Client._FinalStand.Shop;
using Content.Client._FinalStand.Stylesheets;
using Content.Shared._FinalStand.Crit;
using Content.Shared._FinalStand.Grenades;
using Content.Shared._FinalStand.Research.Prototypes;
using Content.Shared._FinalStand.Shop;
using Content.Shared.Containers.ItemSlots;
using Content.Shared.Power.Components;
using Content.Shared.Projectiles;
using Content.Shared.Weapons.Hitscan.Components;
using Content.Shared.Weapons.Melee;
using Content.Shared.Weapons.Ranged.Components;
using Content.Shared.Weapons.Ranged.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._FinalStand.Shop.UI;

[GenerateTypedNameReferences]
public sealed partial class WeaponShopWindow : DefaultWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPrototypeManager _proto = default!;

    public event Action? OnBuyPressed;
    public event Action<string>? OnUpgradePressed;
    public event Action? OnSellConfirmed;

    private int _price;
    private EntProtoId? _weaponProtoId;
    private bool _isGrenadePackShop;
    private float _flashBuyRemaining;

    private bool _inConfirmState;
    private float _confirmTimer;
    private int _sellRefund;
    private const float ConfirmTimeout = 4f;
    private const int BarSegments = 12;

    // ── hover-preview ──────────────────────────────────────────────────────────

    private sealed class StatBarRefs
    {
        public required PanelContainer[] Segments;
        public required Label ValueLabel;
        public float BaseFill;
        public string BaseText = "";
        public Color? BaseColor;
    }

    private readonly Dictionary<string, StatBarRefs> _statBarRefs = new();

    private struct RangedStatCache
    {
        public float BaseDmgPerShot;
        public int   BasePellets;
        public int   ExtraPellets;
        public float DamageMultiplier;
        public float AugDmgMult;
        public float UnboostedFireRate; // baseFireRate + frBonus (pre-BulletStorm)
        public float BulletStormMult;
        public int   Capacity;          // -1 = battery / infinite
        public float BaseCritChance;
        public float CritChanceBonus;
        public float CritDamageMult;
        public bool  Valid;
        public bool  IsRanged;
    }

    private RangedStatCache _rangedCache;

    // ── end hover-preview ──────────────────────────────────────────────────────

    public WeaponShopWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        Stylesheet = new FSMenuStylesheet(IoCManager.Resolve<IUserInterfaceManager>(), IoCManager.Resolve<IResourceCache>()).Stylesheet;

        foreach (var child in UpgradesScroll.Children)
        {
            if (child is ScrollBar bar)
            {
                bar.SetWidth = 5;
                bar.Modulate = new Color(0.6f, 0.6f, 0.6f, 0.35f);
            }
        }

        BuyButton.OnPressed += _ =>
        {
            _flashBuyRemaining = 0.3f;
            OnBuyPressed?.Invoke();
        };

        SellButton.OnPressed += _ =>
        {
            if (_inConfirmState)
            {
                OnSellConfirmed?.Invoke();
                ExitConfirmState();
            }
            else
            {
                EnterConfirmState();
            }
        };
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_flashBuyRemaining > 0f)
        {
            _flashBuyRemaining = Math.Max(0f, _flashBuyRemaining - args.DeltaSeconds);
            var t = _flashBuyRemaining / 0.3f;
            var v = 0.55f + 0.45f * (1f - t);
            BuyButton.Modulate = new Color(v, 1f, v);
        }

        if (_confirmTimer > 0f)
        {
            _confirmTimer -= args.DeltaSeconds;
            if (_confirmTimer <= 0f)
                ExitConfirmState();
        }
    }

    public void UpdateSellButton(int refund, bool hasWeapon)
    {
        _sellRefund = refund;
        SellButton.Disabled = !hasWeapon;
        if (!_inConfirmState)
        {
            SellButton.Text = $"Sell  ${refund:N0}";
            SellButton.Modulate = Color.White;
        }
    }

    public void ResetConfirmation()
    {
        if (_inConfirmState)
            ExitConfirmState();
    }

    private void EnterConfirmState()
    {
        _inConfirmState = true;
        _confirmTimer = ConfirmTimeout;
        SellButton.Text = "Confirm?";
        SellButton.Modulate = FSUiPalette.StateNegative;
        SellConfirmLabel.Text = "This cannot be undone.";
        SellConfirmLabel.Visible = true;
        SellConfirmLabel.Modulate = FSUiPalette.StatePending;
    }

    private void ExitConfirmState()
    {
        _inConfirmState = false;
        _confirmTimer = 0f;
        SellConfirmLabel.Visible = false;
        SellButton.Text = $"Sell  ${_sellRefund:N0}";
        SellButton.Modulate = Color.White;
    }

    public void Populate(EntityUid shopEntity, IEntityManager entMan)
    {
        if (!entMan.TryGetComponent<FSShopWeaponComponent>(shopEntity, out var comp))
            return;

        _price = comp.Price;
        _weaponProtoId = comp.WeaponProtoId;
        _isGrenadePackShop = _weaponProtoId is { } pid
            && _proto.TryIndex<EntityPrototype>(pid, out var wEntProto)
            && wEntProto.TryGetComponent<FSGrenadePackComponent>(out _, _entityManager.ComponentFactory);

        Title = "Weapon Shop";
        WeaponNameLabel.Text = Capitalize(entMan.GetComponent<MetaDataComponent>(shopEntity).EntityName);
        WeaponNameLabel.Modulate = Color.FromHex("#F4C430");
        CategoryLabel.Text = comp.Category;
        CategoryLabel.Modulate = FSUiPalette.TextMuted;
        DescLabel.SetMessage(entMan.GetComponent<MetaDataComponent>(shopEntity).EntityDescription);

        BuyButton.Text = $"Buy  ${_price:N0}";

        var shopClient = _entityManager.System<FSShopClientSystem>();
        BuildStatBars(comp, shopClient.FindOwnedWeapon(comp.WeaponProtoId), entMan);
        RefreshUpgrades(comp.Upgrades, shopClient.UpgradeLevels, shopClient.CurrentCredits);
        UpdateBalance(shopClient.CurrentCredits);
    }

    public void UpdateBalance(int credits)
    {
        BalanceLabel.Text = $"${credits:N0}";
        BalanceLabel.Modulate = credits >= _price ? FSUiPalette.StatePositive : FSUiPalette.StateNegative;

        if (_isGrenadePackShop)
        {
            var shopClient = _entityManager.System<FSShopClientSystem>();
            if (shopClient.PlayerHasWeaponInInventory(shopClient.GetLocalPlayer(), _weaponProtoId))
            {
                BuyButton.Disabled = true;
                BuyButton.Text = "OWNED";
                BuyButton.Modulate = new Color(0.5f, 0.5f, 0.5f);
                return;
            }
            BuyButton.Text = $"Buy  ${_price:N0}";
            BuyButton.Modulate = Color.White;
        }

        BuyButton.Disabled = credits < _price;
    }

    public void UpdateWeaponTitle(string title)
    {
        if (title.Length > 0)
            WeaponNameLabel.Text = Capitalize(title);
    }

    public void RefreshStatBars(FSShopWeaponComponent comp, EntityUid? gun, IEntityManager entMan)
    {
        BuildStatBars(comp, gun, entMan);
    }

    public void RefreshUpgrades(List<WeaponUpgradeDef> defs, Dictionary<string, int> levels, int credits)
    {
        UpgradesContainer.RemoveAllChildren();

        if (defs.Count == 0)
        {
            UpgradesContainer.AddChild(new Label { Text = "No upgrades available.", Modulate = FSUiPalette.TextMuted });
            UpgradeCounterLabel.Text = "";
            return;
        }

        foreach (var def in defs)
        {
            if (def.RequiresUpgrade != null
                && levels.GetValueOrDefault(def.RequiresUpgrade, 0) <= 0)
                continue;

            var level = levels.GetValueOrDefault(def.Id, 0);
            var alt = def.AltWhenUpgrade != null
                      && levels.GetValueOrDefault(def.AltWhenUpgrade, 0) > 0;
            var name = alt && def.AltName != null ? def.AltName : def.Name;
            var desc = alt && def.AltDescription != null ? def.AltDescription : def.Description;
            var label = alt ? def.AltLabel : null;
            UpgradesContainer.AddChild(BuildUpgradeRow(def, level, credits, name, desc, label));
        }

        var totalPurchased = 0;
        var totalMax = 0;
        foreach (var d in defs)
        {
            if (d.IsStub) continue;
            if (d.RequiresUpgrade != null && levels.GetValueOrDefault(d.RequiresUpgrade, 0) <= 0) continue;
            totalPurchased += levels.GetValueOrDefault(d.Id, 0);
            totalMax += d.MaxLevel;
        }
        UpgradeCounterLabel.Text = $"{totalPurchased} / {totalMax}";
        UpgradeCounterLabel.Modulate = FSUiPalette.TextMuted;
    }

    // ── stat bar construction ──────────────────────────────────────────────────

}
