using Content.Shared._FinalStand.Crit;
using Content.Shared._FinalStand.Grenades;
using Content.Shared._FinalStand.Perks;
using Content.Shared._FinalStand.Shop;
using Content.Shared.Containers.ItemSlots;
using Content.Shared.Projectiles;
using Content.Shared.Weapons.Melee;
using Content.Shared.Weapons.Ranged.Components;
using Content.Shared.Weapons.Ranged.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._FinalStand.Shop.UI;

[GenerateTypedNameReferences]
public sealed partial class WeaponShopWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;

    public event Action? OnBuyPressed;
    public event Action<string>? OnUpgradePressed;
    public event Action<string>? OnBuyPerkPressed;
    public event Action? OnSellConfirmed;

    private int _price;
    private EntProtoId? _weaponProtoId;
    private bool _isGrenadePackShop;
    private float _flashBuyRemaining;

    private bool _inConfirmState;
    private float _confirmTimer;
    private int _sellRefund;
    private const float ConfirmTimeout = 4f;

    public WeaponShopWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        foreach (var child in UpgradesScroll.Children)
        {
            if (child is ScrollBar bar)
            {
                bar.SetWidth = 5;
                bar.Modulate = new Color(0.6f, 0.6f, 0.6f, 0.35f);
            }
        }

        BuyButton.OnPressed += _ =>
        {
            _flashBuyRemaining = 0.3f;
            OnBuyPressed?.Invoke();
        };

        SellButton.OnPressed += _ =>
        {
            if (_inConfirmState)
            {
                OnSellConfirmed?.Invoke();
                ExitConfirmState();
            }
            else
            {
                EnterConfirmState();
            }
        };
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_flashBuyRemaining > 0f)
        {
            _flashBuyRemaining = Math.Max(0f, _flashBuyRemaining - args.DeltaSeconds);
            var t = _flashBuyRemaining / 0.3f;
            var v = 0.55f + 0.45f * (1f - t);
            BuyButton.Modulate = new Color(v, 1f, v);
        }

        if (_confirmTimer > 0f)
        {
            _confirmTimer -= args.DeltaSeconds;
            if (_confirmTimer <= 0f)
                ExitConfirmState();
        }
    }

    public void UpdateSellButton(int refund, bool hasWeapon)
    {
        _sellRefund = refund;
        SellButton.Disabled = !hasWeapon;
        if (!_inConfirmState)
        {
            SellButton.Text = $"Sell  ${refund:N0}";
            SellButton.Modulate = Color.White;
        }
    }

    public void ResetConfirmation()
    {
        if (_inConfirmState)
            ExitConfirmState();
    }

    private void EnterConfirmState()
    {
        _inConfirmState = true;
        _confirmTimer = ConfirmTimeout;
        SellButton.Text = "Confirm?";
        SellButton.Modulate = Color.FromHex("#BF616A");
        SellConfirmLabel.Text = "This cannot be undone.";
        SellConfirmLabel.Visible = true;
        SellConfirmLabel.Modulate = Color.FromHex("#EBCB8B");
    }

    private void ExitConfirmState()
    {
        _inConfirmState = false;
        _confirmTimer = 0f;
        SellConfirmLabel.Visible = false;
        SellButton.Text = $"Sell  ${_sellRefund:N0}";
        SellButton.Modulate = Color.White;
    }

    public void Populate(EntityUid shopEntity, IEntityManager entMan)
    {
        if (!entMan.TryGetComponent<FSShopWeaponComponent>(shopEntity, out var comp))
            return;

        _price = comp.Price;
        _weaponProtoId = comp.WeaponProtoId;
        _isGrenadePackShop = _weaponProtoId is { } pid
            && _proto.TryIndex<EntityPrototype>(pid, out var wEntProto)
            && wEntProto.TryGetComponent<FSGrenadePackComponent>(out _, _entityManager.ComponentFactory);

        var meta = entMan.GetComponent<MetaDataComponent>(shopEntity);
        Title = "Weapon Shop";

        WeaponNameLabel.Text = Capitalize(meta.EntityName);
        WeaponNameLabel.Modulate = Color.FromHex("#F4C430");
        CategoryLabel.Text = comp.Category;
        CategoryLabel.Modulate = Color.FromHex("#8FA1B3");
        DescLabel.SetMessage(meta.EntityDescription);

        BuyButton.Text = $"Buy  ${_price:N0}";

        var shopClient = _entityManager.System<FSShopClientSystem>();
        BuildStatBars(comp, shopClient.GetActiveGun(), entMan);
        RefreshUpgrades(comp.Upgrades, shopClient.UpgradeLevels, shopClient.CurrentCredits);
        RefreshPerks(shopEntity, entMan, shopClient.CurrentCredits);
        UpdateBalance(shopClient.CurrentCredits);
    }

    public void UpdateBalance(int credits)
    {
        BalanceLabel.Text = $"${credits:N0}";
        var canAfford = credits >= _price;
        BalanceLabel.Modulate = canAfford ? Color.LimeGreen : Color.OrangeRed;

        if (_isGrenadePackShop)
        {
            var shopClient = _entityManager.System<FSShopClientSystem>();
            if (shopClient.PlayerHasWeaponInInventory(shopClient.GetLocalPlayer(), _weaponProtoId))
            {
                BuyButton.Disabled = true;
                BuyButton.Text = "OWNED";
                BuyButton.Modulate = new Color(0.5f, 0.5f, 0.5f);
                return;
            }
            BuyButton.Text = $"Buy  ${_price:N0}";
            BuyButton.Modulate = Color.White;
        }

        BuyButton.Disabled = !canAfford;
    }

    public void UpdateWeaponTitle(string title)
    {
        if (title.Length > 0)
            WeaponNameLabel.Text = Capitalize(title);
    }

    public void RefreshStatBars(FSShopWeaponComponent comp, EntityUid? gun, IEntityManager entMan)
    {
        BuildStatBars(comp, gun, entMan);
    }

    public void RefreshUpgrades(List<WeaponUpgradeDef> defs, Dictionary<string, int> levels, int credits)
    {
        UpgradesContainer.RemoveAllChildren();

        if (defs.Count == 0)
        {
            UpgradesContainer.AddChild(new Label { Text = "No upgrades available.", Modulate = Color.FromHex("#8FA1B3") });
            UpgradeCounterLabel.Text = "";
            return;
        }

        foreach (var def in defs)
        {
                if (def.RequiresUpgrade != null
                && levels.GetValueOrDefault(def.RequiresUpgrade, 0) <= 0)
                continue;

            var level = levels.GetValueOrDefault(def.Id, 0);
            UpgradesContainer.AddChild(BuildUpgradeRow(def, level, credits));
        }

        var totalPurchased = 0;
        var totalMax = 0;
        foreach (var d in defs)
        {
            if (d.IsStub) continue;
            if (d.RequiresUpgrade != null
                && levels.GetValueOrDefault(d.RequiresUpgrade, 0) <= 0)
                continue;
            totalPurchased += levels.GetValueOrDefault(d.Id, 0);
            totalMax += d.MaxLevel;
        }
        UpgradeCounterLabel.Text = $"{totalPurchased} / {totalMax}";
        UpgradeCounterLabel.Modulate = Color.FromHex("#8FA1B3");
    }

    public void RefreshPerks(EntityUid shopEntity, IEntityManager entMan, int credits)
    {
        PerksContainer.RemoveAllChildren();

        if (!entMan.TryGetComponent<FSShopPerksComponent>(shopEntity, out var perksComp)
            || perksComp.Perks.Count == 0)
        {
            PerksSection.Visible = false;
            return;
        }

        PerksSection.Visible = true;

        var localPlayer = IoCManager.Resolve<Robust.Client.Player.IPlayerManager>().LocalSession?.AttachedEntity;
        List<PerkType> activePerks = [];
        if (localPlayer != null && entMan.TryGetComponent<PerkComponent>(localPlayer.Value, out var perkComp))
            activePerks = perkComp.ActivePerks;

        foreach (var protoId in perksComp.Perks)
        {
            if (!_proto.TryIndex<PerkPrototype>(protoId, out var perkDef))
                continue;
            PerksContainer.AddChild(BuildPerkRow(perkDef, activePerks, credits));
        }
    }

    private void BuildStatBars(FSShopWeaponComponent shopComp, EntityUid? weapon, IEntityManager entMan)
    {
        StatBarsContainer.RemoveAllChildren();

        CritComponent? critComp = null;
        FSWeaponUpgradeStateComponent? upgradeState = null;
        GunComponent? gunComp = null;
        MeleeWeaponComponent? meleeComp = null;
        if (weapon.HasValue)
        {
            entMan.TryGetComponent(weapon.Value, out critComp);
            entMan.TryGetComponent(weapon.Value, out upgradeState);
            entMan.TryGetComponent(weapon.Value, out gunComp);
            entMan.TryGetComponent(weapon.Value, out meleeComp);
        }

        EntityPrototype? weaponProto = null;
        GunComponent? gunProto = null;
        MeleeWeaponComponent? meleeProto = null;
        CritComponent? critProto = null;
        if (shopComp.WeaponProtoId is { } weaponProtoId
            && _proto.TryIndex<EntityPrototype>(weaponProtoId, out weaponProto))
        {
            weaponProto.TryGetComponent<GunComponent>(out gunProto, entMan.ComponentFactory);
            weaponProto.TryGetComponent<MeleeWeaponComponent>(out meleeProto, entMan.ComponentFactory);
            weaponProto.TryGetComponent<CritComponent>(out critProto, entMan.ComponentFactory);
        }

        var isRanged = gunComp != null || gunProto != null;
        if (isRanged)
            BuildRangedStats(shopComp, weapon, weaponProto, gunComp, gunProto, upgradeState, entMan);
        else if (meleeComp != null || meleeProto != null)
            BuildMeleeStats(meleeComp, meleeProto, upgradeState);

        AppendCritStats(critComp, critProto, upgradeState);
    }

    private void BuildRangedStats(FSShopWeaponComponent shopComp, EntityUid? weapon,
        EntityPrototype? weaponProto, GunComponent? gunComp, GunComponent? gunProto,
        FSWeaponUpgradeStateComponent? upgradeState, IEntityManager entMan)
    {
        var (damagePerShot, pellets) = ComputeDamage(shopComp, weapon, weaponProto, upgradeState, entMan);
        var damageText = pellets > 1 ? $"{damagePerShot:0.#}×{pellets}" : $"{damagePerShot:0.#}";
        var damageFill = Math.Min(1f, damagePerShot * pellets / 100f);
        StatBarsContainer.AddChild(BuildStatBar("Damage", damageFill, damageText));

        var fireRate = gunComp?.FireRateModified ?? gunProto?.FireRate ?? 2f;
        var secPerShot = fireRate > 0f ? 1f / fireRate : 0f;
        StatBarsContainer.AddChild(BuildStatBar("Fire Rate",
            Math.Min(1f, fireRate / 10f),
            $"{secPerShot:F1}s"));

        var angleDeg = gunComp != null
            ? (float)gunComp.MaxAngleModified.Degrees
            : gunProto != null
                ? (float)gunProto.MaxAngle.Degrees
                : 15f;
        StatBarsContainer.AddChild(BuildStatBar("Accuracy",
            Math.Max(0f, 1f - angleDeg / 30f),
            $"{angleDeg:F1}°"));

        var (capFill, capText) = GetCapacityDisplay(shopComp, weapon, weaponProto, entMan);
        StatBarsContainer.AddChild(BuildStatBar("Capacity", capFill, capText));
    }

    private void BuildMeleeStats(MeleeWeaponComponent? meleeComp, MeleeWeaponComponent? meleeProto,
        FSWeaponUpgradeStateComponent? upgradeState)
    {
        var baseDamage = (float)(meleeComp?.Damage ?? meleeProto?.Damage)!.GetTotal();
        if (upgradeState != null && upgradeState.DamageMultiplier > 1f)
            baseDamage *= upgradeState.DamageMultiplier;
        StatBarsContainer.AddChild(BuildStatBar("Damage",
            Math.Min(1f, baseDamage / 50f),
            $"{baseDamage:0.#}"));

        var attackRate = meleeComp?.AttackRate ?? meleeProto?.AttackRate ?? 1f;
        if (upgradeState != null && upgradeState.AttackSpeedMultiplier > 1f)
            attackRate *= upgradeState.AttackSpeedMultiplier;
        var secPerSwing = attackRate > 0f ? 1f / attackRate : 0f;
        StatBarsContainer.AddChild(BuildStatBar("Attack Rate",
            Math.Min(1f, attackRate / 4f),
            $"{secPerSwing:F1}s"));

        var range = meleeComp?.Range ?? meleeProto?.Range ?? 1.5f;
        StatBarsContainer.AddChild(BuildStatBar("Range",
            Math.Min(1f, range / 3f),
            $"{range:F1}"));
    }

    private void AppendCritStats(CritComponent? critComp, CritComponent? critProto,
        FSWeaponUpgradeStateComponent? upgradeState)
    {
        var critChance = (critComp?.BaseCritChance ?? critProto?.BaseCritChance ?? 0f)
                         + (upgradeState?.CritChance ?? 0f);
        StatBarsContainer.AddChild(BuildStatBar("Crit Chance",
            Math.Min(1f, critChance),
            $"{critChance * 100f:F1}%"));

        var critMult = upgradeState?.CritDamageMultiplier
                       ?? critComp?.CritMultiplier
                       ?? critProto?.CritMultiplier
                       ?? 1f;
        StatBarsContainer.AddChild(BuildStatBar("Crit Damage",
            Math.Min(1f, (critMult - 1f) / 2f),
            $"{critMult:F1}x"));
    }

    private (float damage, int pellets) ComputeDamage(FSShopWeaponComponent shopComp, EntityUid? gun,
        EntityPrototype? weaponProto, FSWeaponUpgradeStateComponent? upgradeState, IEntityManager entMan)
    {
        var damage = 0f;
        var pellets = 1;

        if (TryResolveProjectileProto(shopComp, gun, weaponProto, entMan, out var projProto))
        {
            if (projProto.TryGetComponent<ProjectileComponent>(out var proj, entMan.ComponentFactory))
                damage = (float)proj.Damage.GetTotal();
            if (projProto.TryGetComponent<ProjectileSpreadComponent>(out var spread, entMan.ComponentFactory))
                pellets = spread.Count;
        }

        if (upgradeState != null)
        {
            damage *= upgradeState.DamageMultiplier;
            pellets += upgradeState.ExtraPellets;
        }

        return (damage, pellets);
    }

    // Walk the ammo chain to find the projectile prototype for damage/pellet sampling.
    // Order: live gun's ammo provider → weapon prototype's ammo provider → starter ammo.
    // Cartridges are followed to their fired projectile.
    private bool TryResolveProjectileProto(FSShopWeaponComponent shopComp, EntityUid? gun,
        EntityPrototype? weaponProto, IEntityManager entMan, out EntityPrototype projProto)
    {
        projProto = default!;
        EntProtoId? ammoProto = null;

        if (gun.HasValue)
        {
            if (entMan.TryGetComponent<BatteryAmmoProviderComponent>(gun.Value, out var battery))
                ammoProto = battery.Prototype;
            else if (entMan.TryGetComponent<BallisticAmmoProviderComponent>(gun.Value, out var ballistic))
                ammoProto = ballistic.Proto;
            else if (entMan.TryGetComponent<RevolverAmmoProviderComponent>(gun.Value, out var revolver))
                ammoProto = revolver.FillPrototype;
            else if (entMan.System<ItemSlotsSystem>().TryGetSlot(gun.Value, SharedGunSystem.MagazineSlot, out var magSlot)
                     && magSlot.Item.HasValue
                     && entMan.TryGetComponent<BallisticAmmoProviderComponent>(magSlot.Item.Value, out var magBal))
            {
                ammoProto = magBal.Proto;
            }
        }

        if (ammoProto == null && weaponProto != null)
        {
            if (weaponProto.TryGetComponent<BatteryAmmoProviderComponent>(out var batteryProto, entMan.ComponentFactory))
                ammoProto = batteryProto.Prototype;
            else if (weaponProto.TryGetComponent<BallisticAmmoProviderComponent>(out var ballProto, entMan.ComponentFactory))
                ammoProto = ballProto.Proto;
            else if (weaponProto.TryGetComponent<RevolverAmmoProviderComponent>(out var revProto, entMan.ComponentFactory))
                ammoProto = revProto.FillPrototype;
        }

        if (ammoProto == null && shopComp.StarterAmmoProtoId is { } starterId
            && _proto.TryIndex<EntityPrototype>(starterId, out var starterProto)
            && starterProto.TryGetComponent<BallisticAmmoProviderComponent>(out var starterBal, entMan.ComponentFactory))
        {
            ammoProto = starterBal.Proto;
        }

        if (ammoProto == null || !_proto.TryIndex<EntityPrototype>(ammoProto, out var ammoEntProto))
            return false;

        if (ammoEntProto.TryGetComponent<CartridgeAmmoComponent>(out var cartridge, entMan.ComponentFactory)
            && _proto.TryIndex<EntityPrototype>(cartridge.Prototype, out var bulletProto))
        {
            projProto = bulletProto;
            return true;
        }

        projProto = ammoEntProto;
        return true;
    }

    private (float fill, string text) GetCapacityDisplay(FSShopWeaponComponent shopComp, EntityUid? gun,
        EntityPrototype? weaponProto, IEntityManager entMan)
    {
        if (gun.HasValue)
        {
            if (entMan.TryGetComponent<BallisticAmmoProviderComponent>(gun.Value, out var bal))
                return (Math.Min(1f, bal.Capacity / 30f), $"{bal.Capacity}");
            if (entMan.TryGetComponent<RevolverAmmoProviderComponent>(gun.Value, out var rev))
                return (Math.Min(1f, rev.Capacity / 30f), $"{rev.Capacity}");
            if (entMan.TryGetComponent<BatteryAmmoProviderComponent>(gun.Value, out _))
                return (1f, "∞");
            if (entMan.System<ItemSlotsSystem>().TryGetSlot(gun.Value, SharedGunSystem.MagazineSlot, out var magSlot)
                && magSlot.Item.HasValue
                && entMan.TryGetComponent<BallisticAmmoProviderComponent>(magSlot.Item.Value, out var magBal))
                return (Math.Min(1f, magBal.Capacity / 30f), $"{magBal.Capacity}");
        }

        if (weaponProto != null)
        {
            if (weaponProto.TryGetComponent<BallisticAmmoProviderComponent>(out var ballProto, entMan.ComponentFactory))
                return (Math.Min(1f, ballProto.Capacity / 30f), $"{ballProto.Capacity}");
            if (weaponProto.TryGetComponent<RevolverAmmoProviderComponent>(out var revProto, entMan.ComponentFactory))
                return (Math.Min(1f, revProto.Capacity / 30f), $"{revProto.Capacity}");
            if (weaponProto.TryGetComponent<BatteryAmmoProviderComponent>(out _, entMan.ComponentFactory))
                return (1f, "∞");
        }

        if (shopComp.StarterAmmoProtoId is { } starterId
            && _proto.TryIndex<EntityPrototype>(starterId, out var starterProto)
            && starterProto.TryGetComponent<BallisticAmmoProviderComponent>(out var starterBal, entMan.ComponentFactory))
        {
            return (Math.Min(1f, starterBal.Capacity / 30f), $"{starterBal.Capacity}");
        }

        var approx = (int)(shopComp.StatCapacity * 0.2f);
        return (Math.Min(1f, approx / 30f), $"{approx}");
    }

    private static BoxContainer BuildStatBar(string label, float fill, string numericText)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 0, 0, 6),
            VerticalAlignment = VAlignment.Center,
        };

        row.AddChild(new Label
        {
            Text = label,
            SetWidth = 100,
            Modulate = Color.FromHex("#8FA1B3"),
        });

        const int segments = 10;
        var filled = (int)Math.Round(fill * segments);
        var barColor = StatBarColor((int)(fill * 100f));

        var segBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        };
        for (var i = 0; i < segments; i++)
        {
            var seg = new PanelContainer
            {
                HorizontalExpand = true,
                SetHeight = 8,
                Margin = new Thickness(i == 0 ? 0 : 1, 0, 0, 0),
            };
            seg.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = i < filled ? barColor : Color.FromHex("#2E3440"),
            };
            segBox.AddChild(seg);
        }
        row.AddChild(segBox);

        row.AddChild(new Label
        {
            Text = numericText,
            SetWidth = 42,
            Margin = new Thickness(7, 0, 0, 0),
            HorizontalAlignment = HAlignment.Right,
            Modulate = Color.FromHex("#8FA1B3"),
        });

        return row;
    }

    private static Color StatBarColor(int value) => value switch
    {
        <= 25 => Color.FromHex("#BF616A"),
        <= 50 => Color.FromHex("#EBCB8B"),
        <= 75 => Color.FromHex("#A3BE8C"),
        _ => Color.FromHex("#88C0D0"),
    };

    private BoxContainer BuildUpgradeRow(WeaponUpgradeDef def, int currentLevel, int credits)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 4, 0, 4),
        };

        var atMax = currentLevel >= def.MaxLevel;
        var nextCost = def.BaseCost * (currentLevel + 1);
        var canAffordNext = atMax || credits >= nextCost;

        if (!atMax && !canAffordNext)
            row.Modulate = new Color(1f, 1f, 1f, 0.5f);

        var btn = new Button
        {
            Text = def.Name,
            MinWidth = 150,
            MaxWidth = 180,
            ClipText = true,
            Disabled = atMax || !canAffordNext,
            ToolTip = string.IsNullOrEmpty(def.Description) ? def.Name : def.Description,
        };
        btn.OnPressed += _ => OnUpgradePressed?.Invoke(def.Id);
        row.AddChild(btn);

        if (def.IsStub)
        {
            btn.Disabled = true;
            btn.ToolTip = "Not yet implemented.";
            row.AddChild(new Label
            {
                Text = "WIP",
                Modulate = Color.FromHex("#BF616A"),
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Right,
            });
            return row;
        }

        var pips = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(6, 0, 6, 0),
        };
        for (var i = 0; i < def.MaxLevel; i++)
        {
            pips.AddChild(new Label
            {
                Text = "■",
                Modulate = i < currentLevel ? Color.FromHex("#A3BE8C") : Color.FromHex("#434C5E"),
            });
        }
        row.AddChild(pips);

        row.AddChild(new Label
        {
            Text = UpgradeTypeToStatLabel(def.Type),
            Modulate = Color.FromHex("#8FA1B3"),
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Left,
        });

        row.AddChild(new Label
        {
            Text = atMax ? "MAX" : $"${nextCost:N0}",
            Modulate = atMax
                ? Color.FromHex("#FFD700")
                : canAffordNext
                    ? Color.FromHex("#A3BE8C")
                    : Color.FromHex("#BF616A"),
            HorizontalAlignment = HAlignment.Right,
            Margin = new Thickness(0, 0, 7, 0),
        });

        return row;
    }

    private BoxContainer BuildPerkRow(PerkPrototype perkDef, List<PerkType> activePerks, int credits)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 0, 0, 6),
        };

        var isActive = activePerks.Contains(perkDef.PerkType);
        var canAfford = credits >= perkDef.Cost;

        var btn = new Button
        {
            Text = perkDef.Name,
            MinWidth = 130,
            Disabled = perkDef.IsLocked || isActive || !canAfford,
            ToolTip = perkDef.Description,
        };
        btn.Modulate = Color.FromHex("#C5E1A5");
        btn.OnPressed += _ => OnBuyPerkPressed?.Invoke(perkDef.ID);
        row.AddChild(btn);

        if (perkDef.IsLocked)
        {
            btn.Disabled = true;
            row.AddChild(new Label
            {
                Text = "SOON",
                Modulate = Color.FromHex("#888888"),
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Right,
            });
            return row;
        }

        var statusLabel = new Label
        {
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Right,
        };

        if (isActive)
        {
            statusLabel.Text = "ACTIVE";
            statusLabel.Modulate = Color.FromHex("#69F0AE");
        }
        else
        {
            statusLabel.Text = $"${perkDef.Cost:N0}";
            statusLabel.Modulate = canAfford ? Color.FromHex("#EBCB8B") : Color.FromHex("#BF616A");
        }

        row.AddChild(statusLabel);
        return row;
    }

    private static string UpgradeTypeToStatLabel(WeaponUpgradeType type) => type switch
    {
        WeaponUpgradeType.FireRate => "Fire Rate",
        WeaponUpgradeType.Accuracy => "Accuracy",
        WeaponUpgradeType.AngleMax => "Spread",
        WeaponUpgradeType.MagazineSize => "Mag Size",
        WeaponUpgradeType.ReloadSpeed => "Reload Speed",
        WeaponUpgradeType.Range => "Range",
        WeaponUpgradeType.FullAuto => "Auto",
        WeaponUpgradeType.CritChance => "Crit %",
        WeaponUpgradeType.CritDamage => "Crit DMG",
        WeaponUpgradeType.Pierce => "Pierce",
        WeaponUpgradeType.Radius => "Radius",
        WeaponUpgradeType.Akimbo => "Dual Wield",
        WeaponUpgradeType.ExplosiveShot => "Explosive",
        WeaponUpgradeType.MoneyGainBonus => "Money",
        WeaponUpgradeType.MoneyPerHit => "$/Hit",
        WeaponUpgradeType.Slowing => "Slow",
        WeaponUpgradeType.BeamChaining => "Chain",
        WeaponUpgradeType.Knockback => "Knockback",
        WeaponUpgradeType.SelfChargeSpeed => "Charge Speed",
        WeaponUpgradeType.SetOnFire => "Ignite",
        WeaponUpgradeType.APRounds => "AP",
        WeaponUpgradeType.ArmorShred => "Armor Shred",
        WeaponUpgradeType.SpawnItem => "Additional Ammo",
        WeaponUpgradeType.Recoil => "Recoil",
        WeaponUpgradeType.LifeSteal => "Life Steal",
        WeaponUpgradeType.StaminaSteal => "Stamina Steal",
        WeaponUpgradeType.MovementSpeed => "Move Speed",
        WeaponUpgradeType.AttackSpeed => "Attack Speed",
        WeaponUpgradeType.Damage => "Damage",
        WeaponUpgradeType.PelletCount => "Pellets",
        WeaponUpgradeType.Scrapshot => "Scrapshot",
        WeaponUpgradeType.Bleed => "Bleed",
        WeaponUpgradeType.SlamFire => "Slam Fire",
        WeaponUpgradeType.FlechetteRounds => "Flechette",
        WeaponUpgradeType.SplinterImpact => "Splinter",
        WeaponUpgradeType.OverchargeShot => "Overcharge",
        WeaponUpgradeType.Overkill => "Overkill",
        WeaponUpgradeType.Execution => "Execution",
        WeaponUpgradeType.WarTorn => "Battle Trance",
        WeaponUpgradeType.Suppression => "Suppress",
        WeaponUpgradeType.Resonance => "Resonance",
        WeaponUpgradeType.Prismatic => "Prismatic",
        WeaponUpgradeType.MagEfficiency => "Mag Eff.",
        WeaponUpgradeType.PulseCascade => "Cascade",
        WeaponUpgradeType.Aftershock => "Aftershock",
        WeaponUpgradeType.SpeedLoader => "Speed Loader",
        WeaponUpgradeType.ConcussionClub => "Stun (Heavy)",
        WeaponUpgradeType.CritVsStunned => "Stun Crit",
        WeaponUpgradeType.StunOnHit => "Stun",
        WeaponUpgradeType.FlintlockCritSynergy => "Pirate Crit",
        WeaponUpgradeType.CritVsBurning => "Fire Crit",
        WeaponUpgradeType.FireResist => "Fire Resist",
        WeaponUpgradeType.WhileBurningBuff => "Pyromaniac",
        WeaponUpgradeType.FuelEfficiency => "Fuel Eff.",
        WeaponUpgradeType.FuelCapacity => "Fuel Cap.",
        WeaponUpgradeType.WielderResistance => "Resist",
        WeaponUpgradeType.DualWieldEnergySword => "Dual Wield",
        _ => "",
    };

    private static string Capitalize(string text)
    {
        if (text.Length == 0) return text;
        return text.Substring(0, 1).ToUpper() + text.Substring(1);
    }
}
