using Content.Client._FinalStand.Perks;
using Content.Client._FinalStand.Shop;
using Content.Client._FinalStand.Stylesheets;
using Content.Shared._FinalStand.Crit;
using Content.Shared._FinalStand.Grenades;
using Content.Shared._FinalStand.Research.Prototypes;
using Content.Shared._FinalStand.Shop;
using Content.Shared.Containers.ItemSlots;
using Content.Shared.Power.Components;
using Content.Shared.Projectiles;
using Content.Shared.Weapons.Hitscan.Components;
using Content.Shared.Weapons.Melee;
using Content.Shared.Weapons.Ranged.Components;
using Content.Shared.Weapons.Ranged.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._FinalStand.Shop.UI;

public sealed partial class WeaponShopWindow
{
    private void SetHoveredUpgrade(WeaponUpgradeDef def)
    {
        // Restore all bars to base.
        foreach (var refs in _statBarRefs.Values)
            ApplyStatBar(refs, refs.BaseFill, refs.BaseText, refs.BaseColor, false);

        if (!_rangedCache.Valid) return;

        var shopLevels = _entityManager.System<FSShopClientSystem>().UpgradeLevels;
        var currentLevel = shopLevels.GetValueOrDefault(def.Id, 0);
        if (currentLevel >= def.MaxLevel) return;

        switch (def.Type)
        {
            case WeaponUpgradeType.Damage when _rangedCache.IsRanged:
            {
                var newMult  = _rangedCache.DamageMultiplier + def.ValuePerLevel;
                var newDmg   = _rangedCache.BaseDmgPerShot * newMult * _rangedCache.AugDmgMult;
                var pellets  = _rangedCache.BasePellets + _rangedCache.ExtraPellets;
                var newFill  = Math.Min(1f, newDmg * pellets / 100f);
                var text     = pellets > 1 ? $"↑ {newDmg:0.#}×{pellets}" : $"↑ {newDmg:0.#}";
                if (_statBarRefs.TryGetValue("Damage", out var refs))
                    ApplyStatBar(refs, newFill, text, FSUiPalette.StatePositive, true);
                break;
            }
            case WeaponUpgradeType.FireRate when _rangedCache.IsRanged:
            {
                var newFR   = (_rangedCache.UnboostedFireRate + def.ValuePerLevel) * _rangedCache.BulletStormMult;
                var newRpm  = (int)Math.Round(newFR * 60f);
                var newFill = Math.Min(1f, newFR / 10f);
                if (_statBarRefs.TryGetValue("Fire Rate", out var refs))
                    ApplyStatBar(refs, newFill, $"↑ {newRpm} RPM", FSUiPalette.StatePositive, true);
                break;
            }
            case WeaponUpgradeType.Accuracy when _rangedCache.IsRanged:
            case WeaponUpgradeType.AngleMax  when _rangedCache.IsRanged:
            {
                // The server replays one level through the same clamps the upgrade uses, so this
                // is the value the bar will hold after buying.
                if (!_entityManager.System<FSShopClientSystem>().NextLevelAccuracy.TryGetValue(def.Id, out var newStat))
                    break;
                if (_statBarRefs.TryGetValue("Accuracy", out var refs))
                    ApplyStatBar(refs, newStat / 100f, $"↑ {newStat}", FSUiPalette.StatePositive, true);
                break;
            }
            case WeaponUpgradeType.MagazineSize when _rangedCache.IsRanged && _rangedCache.Capacity >= 0:
            {
                var newCap  = _rangedCache.Capacity + (int)Math.Round(def.ValuePerLevel);
                var newFill = Math.Min(1f, newCap / 30f);
                if (_statBarRefs.TryGetValue("Capacity", out var refs))
                    ApplyStatBar(refs, newFill, $"↑ {newCap}", FSUiPalette.StatePositive, true);
                break;
            }
            case WeaponUpgradeType.CritChance:
            {
                var newChance = Math.Min(1f,
                    _rangedCache.BaseCritChance + _rangedCache.CritChanceBonus + def.ValuePerLevel);
                if (_statBarRefs.TryGetValue("Crit %", out var refs))
                    ApplyStatBar(refs, newChance, $"↑ {newChance * 100f:F1}%", FSUiPalette.StatePositive, true);
                break;
            }
            case WeaponUpgradeType.CritDamage:
            {
                var newMult = _rangedCache.CritDamageMult + def.ValuePerLevel;
                var newFill = Math.Min(1f, (newMult - 1f) / 2f);
                if (_statBarRefs.TryGetValue("Crit DMG", out var refs))
                    ApplyStatBar(refs, newFill, $"↑ {newMult:F1}x", FSUiPalette.StatePositive, true);
                break;
            }
        }
    }

    private void ClearPreview()
    {
        foreach (var refs in _statBarRefs.Values)
            ApplyStatBar(refs, refs.BaseFill, refs.BaseText, refs.BaseColor, false);
    }

    private static void ApplyStatBar(StatBarRefs refs, float fill, string text, Color? valueColor, bool boosted)
    {
        var clamped = Math.Max(0f, Math.Min(1f, fill));
        var filled  = (int)Math.Round(clamped * BarSegments);
        var barColor = boosted ? FSUiPalette.StatePositive : StatBarColor((int)(clamped * 100f));

        for (var i = 0; i < refs.Segments.Length; i++)
        {
            refs.Segments[i].PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = i < filled ? barColor : Color.FromHex("#2E3440"),
            };
        }

        refs.ValueLabel.Text = text;
        refs.ValueLabel.Modulate = valueColor ?? FSUiPalette.TextMuted;
    }

    // ── research indicator ─────────────────────────────────────────────────────
}
