using Content.Shared._FinalStand.Crit;
using Content.Shared._FinalStand.Perks;
using Content.Shared._FinalStand.Shop;
using Content.Shared.Weapons.Ranged.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._FinalStand.Shop.UI;

[GenerateTypedNameReferences]
public sealed partial class WeaponShopWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;

    public event Action? OnBuyPressed;
    public event Action<string>? OnUpgradePressed;
    public event Action<string>? OnBuyPerkPressed;

    private int _price;
    private float _flashBuyRemaining;

    public WeaponShopWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        // Tone down the upgrade list scrollbar: narrower and more translucent.
        foreach (var child in UpgradesScroll.Children)
        {
            if (child is ScrollBar bar)
            {
                bar.SetWidth = 5;
                bar.Modulate = new Color(0.6f, 0.6f, 0.6f, 0.35f);
            }
        }

        BuyButton.OnPressed += _ =>
        {
            _flashBuyRemaining = 0.3f;
            OnBuyPressed?.Invoke();
        };
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (_flashBuyRemaining <= 0f)
            return;
        _flashBuyRemaining = Math.Max(0f, _flashBuyRemaining - args.DeltaSeconds);
        var t = _flashBuyRemaining / 0.3f;
        var v = 0.55f + 0.45f * (1f - t);
        BuyButton.Modulate = new Color(v, 1f, v);
    }

    public void Populate(EntityUid shopEntity, IEntityManager entMan)
    {
        if (!entMan.TryGetComponent<FSShopWeaponComponent>(shopEntity, out var comp))
            return;

        _price = comp.Price;

        var meta = entMan.GetComponent<MetaDataComponent>(shopEntity);
        Title = "Weapon Shop";

        WeaponNameLabel.Text = Capitalize(meta.EntityName);
        WeaponNameLabel.Modulate = Color.FromHex("#F4C430");
        CategoryLabel.Text = comp.Category;
        CategoryLabel.Modulate = Color.FromHex("#8FA1B3");
        DescLabel.SetMessage(meta.EntityDescription);

        BuyButton.Text = $"Buy  ${_price:N0}";

        var shopClient = _entityManager.System<FSShopClientSystem>();
        BuildStatBars(comp, shopClient.GetActiveGun(), entMan);
        RefreshUpgrades(comp.Upgrades, shopClient.UpgradeLevels, shopClient.CurrentCredits);
        RefreshPerks(shopEntity, entMan, shopClient.CurrentCredits);
        UpdateBalance(shopClient.CurrentCredits);
    }

    public void UpdateBalance(int credits)
    {
        BalanceLabel.Text = $"${credits:N0}";
        var canAfford = credits >= _price;
        BuyButton.Disabled = !canAfford;
        BalanceLabel.Modulate = canAfford ? Color.LimeGreen : Color.OrangeRed;
    }

    public void UpdateWeaponTitle(string title)
    {
        if (title.Length > 0)
            WeaponNameLabel.Text = Capitalize(title);
    }

    public void RefreshStatBars(FSShopWeaponComponent comp, EntityUid? gun, IEntityManager entMan)
    {
        BuildStatBars(comp, gun, entMan);
    }

    public void RefreshUpgrades(List<WeaponUpgradeDef> defs, Dictionary<string, int> levels, int credits)
    {
        UpgradesContainer.RemoveAllChildren();

        if (defs.Count == 0)
        {
            UpgradesContainer.AddChild(new Label { Text = "No upgrades available.", Modulate = Color.FromHex("#8FA1B3") });
            UpgradeCounterLabel.Text = "";
            return;
        }

        foreach (var def in defs)
        {
            var level = levels.GetValueOrDefault(def.Id, 0);
            UpgradesContainer.AddChild(BuildUpgradeRow(def, level, credits));
        }

        var totalPurchased = 0;
        var totalMax = 0;
        foreach (var d in defs)
        {
            if (d.IsStub) continue;
            totalPurchased += levels.GetValueOrDefault(d.Id, 0);
            totalMax += d.MaxLevel;
        }
        UpgradeCounterLabel.Text = $"{totalPurchased} / {totalMax}";
        UpgradeCounterLabel.Modulate = Color.FromHex("#8FA1B3");
    }

    public void RefreshPerks(EntityUid shopEntity, IEntityManager entMan, int credits)
    {
        PerksContainer.RemoveAllChildren();

        if (!entMan.TryGetComponent<FSShopPerksComponent>(shopEntity, out var perksComp)
            || perksComp.Perks.Count == 0)
        {
            PerksSection.Visible = false;
            return;
        }

        PerksSection.Visible = true;

        var localPlayer = IoCManager.Resolve<Robust.Client.Player.IPlayerManager>().LocalSession?.AttachedEntity;
        List<PerkType> activePerks = [];
        if (localPlayer != null && entMan.TryGetComponent<PerkComponent>(localPlayer.Value, out var perkComp))
            activePerks = perkComp.ActivePerks;

        foreach (var protoId in perksComp.Perks)
        {
            if (!_proto.TryIndex<PerkPrototype>(protoId, out var perkDef))
                continue;
            PerksContainer.AddChild(BuildPerkRow(perkDef, activePerks, credits));
        }
    }

    // ── Stat bars ─────────────────────────────────────────────────────────────

    private void BuildStatBars(FSShopWeaponComponent shopComp, EntityUid? gun, IEntityManager entMan)
    {
        StatBarsContainer.RemoveAllChildren();

        GunComponent? gunComp = null;
        CritComponent? critComp = null;
        if (gun.HasValue)
        {
            entMan.TryGetComponent(gun.Value, out gunComp);
            entMan.TryGetComponent(gun.Value, out critComp);
        }

        // Damage — no damage upgrades; static designer value.
        StatBarsContainer.AddChild(BuildStatBar("Damage",
            shopComp.StatDamage / 100f,
            $"{shopComp.StatDamage}"));

        // Fire Rate — live from GunComponent.
        var fireRate = gunComp?.FireRateModified ?? 2f;
        var secPerShot = fireRate > 0f ? 1f / fireRate : 0f;
        StatBarsContainer.AddChild(BuildStatBar("Fire Rate",
            Math.Min(1f, fireRate / 10f),
            $"{secPerShot:F1}s"));

        // Accuracy — lower angle → higher bar fill.
        var angleDeg = gunComp != null ? (float)gunComp.MaxAngleModified.Degrees : 15f;
        StatBarsContainer.AddChild(BuildStatBar("Accuracy",
            Math.Max(0f, 1f - angleDeg / 30f),
            $"{angleDeg:F1}°"));

        // Capacity — check each ammo provider type.
        var (capFill, capText) = GetCapacityDisplay(shopComp, gun, entMan);
        StatBarsContainer.AddChild(BuildStatBar("Capacity", capFill, capText));

        // Crit Chance — live from CritComponent.
        var critChance = critComp?.BaseCritChance ?? 0f;
        StatBarsContainer.AddChild(BuildStatBar("Crit Chance",
            Math.Min(1f, critChance),
            $"{critChance * 100f:F1}%"));

        // Crit Damage — live from CritComponent.
        // TODO(finalstand): tune crit damage bar max (currently 3.0x = 100%)
        var critMult = critComp?.CritMultiplier ?? 1f;
        StatBarsContainer.AddChild(BuildStatBar("Crit Damage",
            Math.Min(1f, (critMult - 1f) / 2f),
            $"{critMult:F1}x"));
    }

    private static (float fill, string text) GetCapacityDisplay(FSShopWeaponComponent shopComp, EntityUid? gun, IEntityManager entMan)
    {
        if (gun.HasValue)
        {
            if (entMan.TryGetComponent<BallisticAmmoProviderComponent>(gun.Value, out var bal))
                return (Math.Min(1f, bal.Capacity / 30f), $"{bal.Capacity}");
            if (entMan.TryGetComponent<RevolverAmmoProviderComponent>(gun.Value, out var rev))
            {
                var chambers = rev.AmmoSlots.Count;
                return (Math.Min(1f, chambers / 30f), $"{chambers}");
            }
            if (entMan.TryGetComponent<BatteryAmmoProviderComponent>(gun.Value, out _))
                return (1f, "∞");
        }
        // Magazine guns: approximate from StatCapacity (capacity doesn't change via upgrades here).
        var approx = (int)(shopComp.StatCapacity * 0.2f);
        return (Math.Min(1f, approx / 30f), $"{approx}");
    }

    private static BoxContainer BuildStatBar(string label, float fill, string numericText)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 0, 0, 6),
            VerticalAlignment = VAlignment.Center,
        };

        row.AddChild(new Label
        {
            Text = label,
            SetWidth = 100,
            Modulate = Color.FromHex("#8FA1B3"),
        });

        const int segments = 10;
        var filled = (int)Math.Round(fill * segments);
        var barColor = StatBarColor((int)(fill * 100f));

        var segBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        };
        for (var i = 0; i < segments; i++)
        {
            var seg = new PanelContainer
            {
                HorizontalExpand = true,
                SetHeight = 8,
                Margin = new Thickness(i == 0 ? 0 : 1, 0, 0, 0),
            };
            seg.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = i < filled ? barColor : Color.FromHex("#2E3440"),
            };
            segBox.AddChild(seg);
        }
        row.AddChild(segBox);

        row.AddChild(new Label
        {
            Text = numericText,
            SetWidth = 42,
            Margin = new Thickness(7, 0, 0, 0),
            HorizontalAlignment = HAlignment.Right,
            Modulate = Color.FromHex("#8FA1B3"),
        });

        return row;
    }

    private static Color StatBarColor(int value) => value switch
    {
        <= 25 => Color.FromHex("#BF616A"),
        <= 50 => Color.FromHex("#EBCB8B"),
        <= 75 => Color.FromHex("#A3BE8C"),
        _ => Color.FromHex("#88C0D0"),
    };

    // ── Upgrade rows ──────────────────────────────────────────────────────────

    private BoxContainer BuildUpgradeRow(WeaponUpgradeDef def, int currentLevel, int credits)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 4, 0, 4),
        };

        var atMax = currentLevel >= def.MaxLevel;
        var nextCost = def.BaseCost * (currentLevel + 1);
        var canAffordNext = atMax || credits >= nextCost;

        if (!atMax && !canAffordNext)
            row.Modulate = new Color(1f, 1f, 1f, 0.5f);

        var btn = new Button
        {
            Text = def.Name,
            MinWidth = 130,
            Disabled = atMax || !canAffordNext,
            ToolTip = def.Description,
        };
        btn.OnPressed += _ => OnUpgradePressed?.Invoke(def.Id);
        row.AddChild(btn);

        if (def.IsStub)
        {
            btn.Disabled = true;
            btn.ToolTip = "Not yet implemented.";
            row.AddChild(new Label
            {
                Text = "WIP",
                Modulate = Color.FromHex("#BF616A"),
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Right,
            });
            return row;
        }

        var pips = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(6, 0, 6, 0),
        };
        for (var i = 0; i < def.MaxLevel; i++)
        {
            pips.AddChild(new Label
            {
                Text = "■",
                Modulate = i < currentLevel ? Color.FromHex("#A3BE8C") : Color.FromHex("#434C5E"),
            });
        }
        row.AddChild(pips);

        row.AddChild(new Label
        {
            Text = UpgradeTypeToStatLabel(def.Type),
            Modulate = Color.FromHex("#8FA1B3"),
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Left,
        });

        row.AddChild(new Label
        {
            Text = atMax ? "MAX" : $"${nextCost:N0}",
            Modulate = atMax
                ? Color.FromHex("#FFD700")
                : canAffordNext
                    ? Color.FromHex("#A3BE8C")
                    : Color.FromHex("#BF616A"),
            HorizontalAlignment = HAlignment.Right,
            Margin = new Thickness(0, 0, 7, 0),
        });

        return row;
    }

    private BoxContainer BuildPerkRow(PerkPrototype perkDef, List<PerkType> activePerks, int credits)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 0, 0, 6),
        };

        var isActive = activePerks.Contains(perkDef.PerkType);
        var canAfford = credits >= perkDef.Cost;

        var btn = new Button
        {
            Text = perkDef.Name,
            MinWidth = 130,
            Disabled = perkDef.IsLocked || isActive || !canAfford,
            ToolTip = perkDef.Description,
        };
        btn.Modulate = Color.FromHex("#C5E1A5");
        btn.OnPressed += _ => OnBuyPerkPressed?.Invoke(perkDef.ID);
        row.AddChild(btn);

        if (perkDef.IsLocked)
        {
            btn.Disabled = true;
            row.AddChild(new Label
            {
                Text = "SOON",
                Modulate = Color.FromHex("#888888"),
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Right,
            });
            return row;
        }

        var statusLabel = new Label
        {
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Right,
        };

        if (isActive)
        {
            statusLabel.Text = "ACTIVE";
            statusLabel.Modulate = Color.FromHex("#69F0AE");
        }
        else
        {
            statusLabel.Text = $"${perkDef.Cost:N0}";
            statusLabel.Modulate = canAfford ? Color.FromHex("#EBCB8B") : Color.FromHex("#BF616A");
        }

        row.AddChild(statusLabel);
        return row;
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private static string UpgradeTypeToStatLabel(WeaponUpgradeType type) => type switch
    {
        WeaponUpgradeType.FireRate => "Fire Rate",
        WeaponUpgradeType.Accuracy => "Accuracy",
        WeaponUpgradeType.AngleMax => "Spread",
        WeaponUpgradeType.MagazineSize => "Mag Size",
        WeaponUpgradeType.ReloadSpeed => "Reload Speed",
        WeaponUpgradeType.Range => "Range",
        WeaponUpgradeType.FullAuto => "Auto",
        WeaponUpgradeType.CritChance => "Crit %",
        WeaponUpgradeType.CritDamage => "Crit DMG",
        WeaponUpgradeType.Pierce => "Pierce",
        WeaponUpgradeType.Radius => "Radius",
        WeaponUpgradeType.Akimbo => "Dual Wield",
        WeaponUpgradeType.ExplosiveShot => "Explosive",
        WeaponUpgradeType.MoneyGainBonus => "Money",
        WeaponUpgradeType.Slowing => "Slow",
        WeaponUpgradeType.BeamChaining => "Chain",
        WeaponUpgradeType.Knockback => "Knockback",
        WeaponUpgradeType.SelfChargeSpeed => "Charge Speed",
        WeaponUpgradeType.SetOnFire => "Ignite",
        WeaponUpgradeType.APRounds => "AP",
        WeaponUpgradeType.ArmorShred => "Armor Shred",
        WeaponUpgradeType.SpawnItem => "Additional Ammo",
        WeaponUpgradeType.Recoil => "Recoil",
        WeaponUpgradeType.LifeSteal => "Life Steal",
        WeaponUpgradeType.StaminaSteal => "Stamina Steal",
        WeaponUpgradeType.MovementSpeed => "Move Speed",
        WeaponUpgradeType.AttackSpeed => "Attack Speed",
        WeaponUpgradeType.Damage => "Damage",
        WeaponUpgradeType.PelletCount => "Pellets",
        WeaponUpgradeType.Scrapshot => "Scrapshot",
        WeaponUpgradeType.Bleed => "Bleed",
        WeaponUpgradeType.SlamFire => "Slam Fire",
        WeaponUpgradeType.FlechetteRounds => "Flechette",
        WeaponUpgradeType.SplinterImpact => "Splinter",
        WeaponUpgradeType.OverchargeShot => "Overcharge",
        WeaponUpgradeType.Overkill => "Overkill",
        WeaponUpgradeType.Execution => "Execution",
        WeaponUpgradeType.WarTorn => "Battle Trance",
        WeaponUpgradeType.Suppression => "Suppress",
        WeaponUpgradeType.Resonance => "Resonance",
        WeaponUpgradeType.Prismatic => "Prismatic",
        WeaponUpgradeType.MagEfficiency => "Mag Eff.",
        WeaponUpgradeType.PulseCascade => "Cascade",
        WeaponUpgradeType.Aftershock => "Aftershock",
        _ => "",
    };

    private static string Capitalize(string text)
    {
        if (text.Length == 0) return text;
        return text.Substring(0, 1).ToUpper() + text.Substring(1);
    }
}
