using Content.Client._FinalStand.Perks;
using Content.Client._FinalStand.Shop;
using Content.Client._FinalStand.Stylesheets;
using Content.Shared._FinalStand.Crit;
using Content.Shared._FinalStand.Grenades;
using Content.Shared._FinalStand.Research.Prototypes;
using Content.Shared._FinalStand.Shop;
using Content.Shared.Containers.ItemSlots;
using Content.Shared.Power.Components;
using Content.Shared.Projectiles;
using Content.Shared.Weapons.Hitscan.Components;
using Content.Shared.Weapons.Melee;
using Content.Shared.Weapons.Ranged.Components;
using Content.Shared.Weapons.Ranged.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._FinalStand.Shop.UI;

public sealed partial class WeaponShopWindow
{
    private BoxContainer BuildStatBar(string label, float fill, string numericText,
        Color? valueColor = null, string? valueTooltip = null)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 0, 0, 6),
            VerticalAlignment = VAlignment.Center,
        };

        row.AddChild(new Label
        {
            Text = label,
            SetWidth = 98,
            Modulate = FSUiPalette.TextMuted,
        });

        var clamped = Math.Max(0f, Math.Min(1f, fill));
        var filled  = (int)Math.Round(clamped * BarSegments);
        var barColor = StatBarColor((int)(clamped * 100f));

        var segBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        };

        var segments = new PanelContainer[BarSegments];
        for (var i = 0; i < BarSegments; i++)
        {
            var seg = new PanelContainer
            {
                HorizontalExpand = true,
                SetHeight = 10,
                Margin = new Thickness(i == 0 ? 0 : 1, 0, 0, 0),
            };
            seg.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = i < filled ? barColor : Color.FromHex("#2E3440"),
            };
            segments[i] = seg;
            segBox.AddChild(seg);
        }
        row.AddChild(segBox);

        var valueLabel = new Label
        {
            Text = numericText,
            SetWidth = 72,
            Margin = new Thickness(7, 0, 0, 0),
            HorizontalAlignment = HAlignment.Right,
            Modulate = valueColor ?? FSUiPalette.TextMuted,
            MouseFilter = string.IsNullOrEmpty(valueTooltip) ? MouseFilterMode.Ignore : MouseFilterMode.Stop,
        };
        if (!string.IsNullOrEmpty(valueTooltip))
            valueLabel.ToolTip = valueTooltip;
        row.AddChild(valueLabel);

        _statBarRefs[label] = new StatBarRefs
        {
            Segments  = segments,
            ValueLabel = valueLabel,
            BaseFill  = fill,
            BaseText  = numericText,
            BaseColor = valueColor,
        };

        return row;
    }

    // ── upgrade rows ───────────────────────────────────────────────────────────

    private Control BuildUpgradeRow(WeaponUpgradeDef def, int currentLevel, int credits)
    {
        var atMax     = currentLevel >= def.MaxLevel;
        var nextCost  = def.BaseCost * (currentLevel + 1);
        var canAfford = !def.IsStub && !atMax && credits >= nextCost;
        var hasAny    = currentLevel > 0;

        // Card colors by state - Disabled/AtMax/Selected(hasAny)/Default per the shared state engine
        Color bgColor, borderColor;
        if (def.IsStub || (!canAfford && !atMax))
        {
            bgColor = Color.FromHex("#0F0F13"); borderColor = FSUiPalette.BorderNeutral;
        }
        else if (atMax)
        {
            bgColor = Color.FromHex("#0C1A0C"); borderColor = FSUiPalette.StatePositive;
        }
        else if (hasAny)
        {
            bgColor = Color.FromHex("#151A2E"); borderColor = FSUiPalette.AccentBrand;
        }
        else
        {
            bgColor = FSUiPalette.BgSurface; borderColor = FSUiPalette.BorderNeutral;
        }

        // Card visual wrapper
        var card = new PanelContainer { Margin = new Thickness(0, 2, 0, 2) };
        card.PanelOverride = MakeCardStyle(bgColor, borderColor);
        // Card-level hover covers category label, pips, price label (Ignore areas)
        card.MouseFilter = MouseFilterMode.Pass;

        // Inner horizontal layout
        var inner = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(6, 4, 6, 4),
            VerticalAlignment = VAlignment.Center,
        };

        // Purchase button — natural sizing capped at 185px; left-aligned ClipText from stylesheet
        var btn = new Button
        {
            Text = def.Name,
            MinWidth = 140,
            MaxWidth = 185,
            ClipText = true,
            Disabled = def.IsStub || atMax || !canAfford,
            ToolTip = string.IsNullOrEmpty(def.Description) ? def.Name : def.Description,
        };
        btn.OnPressed += _ => OnUpgradePressed?.Invoke(def.Id);
        inner.AddChild(btn);

        if (def.IsStub)
        {
            btn.Disabled = true;
            btn.ToolTip = "Not yet implemented.";
            inner.AddChild(new Label
            {
                Text = "WIP",
                Modulate = FSUiPalette.StateNegative,
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Right,
            });
            card.AddChild(inner);
            card.Modulate = new Color(1f, 1f, 1f, FSUiPalette.DisabledOpacity);
            return card;
        }

        // Hover wiring — button area (btn.OnMouseEntered) + card area (card.OnMouseEntered)
        // cover the whole row regardless of which element is the deepest mouse focus.
        // Both events can fire in the same frame when cursor moves between elements;
        // the UI renders once after both, so there is no visible flicker.
        if (!atMax)
        {
            btn.OnMouseEntered  += _ => SetHoveredUpgrade(def);
            btn.OnMouseExited   += _ => ClearPreview();
            card.OnMouseEntered += _ => SetHoveredUpgrade(def);
            card.OnMouseExited  += _ => ClearPreview();
        }

        // Category label — takes remaining space between button and right section
        var catText = UpgradeTypeToStatLabel(def.Type);
        if (!string.IsNullOrEmpty(catText))
        {
            var catLabel = new Label
            {
                Text = catText,
                Modulate = FSUiPalette.TextMuted,
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Left,
                Margin = new Thickness(4, 0, 0, 0),
                MouseFilter = MouseFilterMode.Pass,
            };
            if (!atMax)
            {
                catLabel.OnMouseEntered += _ => SetHoveredUpgrade(def);
                catLabel.OnMouseExited  += _ => ClearPreview();
            }
            inner.AddChild(catLabel);
        }
        else
        {
            inner.AddChild(new Control { HorizontalExpand = true });
        }

        // Level display — pips for low MaxLevel, compact text for high
        if (def.MaxLevel <= 5)
        {
            var pips = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(4, 0, 4, 0),
                VerticalAlignment = VAlignment.Center,
            };
            for (var i = 0; i < def.MaxLevel; i++)
            {
                var pip = new Label
                {
                    Text = "■",
                    Modulate = i < currentLevel
                        ? (atMax ? FSUiPalette.StatePositive : FSUiPalette.AccentBrand)
                        : Color.FromHex("#2A3040"),
                    MouseFilter = MouseFilterMode.Pass,
                };
                if (!atMax)
                {
                    pip.OnMouseEntered += _ => SetHoveredUpgrade(def);
                    pip.OnMouseExited  += _ => ClearPreview();
                }
                pips.AddChild(pip);
            }
            inner.AddChild(pips);
        }
        else
        {
            var levelColor = atMax ? FSUiPalette.StatePositive
                : currentLevel > 0 ? FSUiPalette.AccentBrand
                : Color.FromHex("#555E7A");
            var levelText = new Label
            {
                Text = $"{currentLevel}/{def.MaxLevel}",
                Modulate = levelColor,
                MinWidth = 40,
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(4, 0, 4, 0),
                MouseFilter = MouseFilterMode.Pass,
            };
            if (!atMax)
            {
                levelText.OnMouseEntered += _ => SetHoveredUpgrade(def);
                levelText.OnMouseExited  += _ => ClearPreview();
            }
            inner.AddChild(levelText);
        }

        var priceLabel = new Label
        {
            Text = atMax ? "MAX" : $"${nextCost:N0}",
            Modulate = atMax
                ? FSUiPalette.StatePending
                : canAfford ? FSUiPalette.StatePositive : FSUiPalette.StateNegative,
            MinWidth = 72,
            HorizontalAlignment = HAlignment.Right,
            Margin = new Thickness(0, 0, 4, 0),
            MouseFilter = MouseFilterMode.Pass,
        };
        if (!atMax)
        {
            priceLabel.OnMouseEntered += _ => SetHoveredUpgrade(def);
            priceLabel.OnMouseExited  += _ => ClearPreview();
        }
        inner.AddChild(priceLabel);

        card.AddChild(inner);

        if (!canAfford && !atMax)
            card.Modulate = new Color(1f, 1f, 1f, FSUiPalette.DisabledOpacity);

        return card;
    }

    private static StyleBoxFlat MakeCardStyle(Color bg, Color border) => new()
    {
        BackgroundColor = bg,
        BorderColor = border,
        BorderThickness = new Thickness(1),
    };

    // ── helpers ────────────────────────────────────────────────────────────────

    private static string UpgradeTypeToStatLabel(WeaponUpgradeType type) => type switch
    {
        WeaponUpgradeType.FireRate           => "Fire Rate",
        WeaponUpgradeType.Accuracy           => "Accuracy",
        WeaponUpgradeType.AngleMax           => "Spread",
        WeaponUpgradeType.MagazineSize       => "Mag Size",
        WeaponUpgradeType.ReloadSpeed        => "Reload Speed",
        WeaponUpgradeType.Range              => "Range",
        WeaponUpgradeType.FullAuto           => "Auto",
        WeaponUpgradeType.CritChance         => "Crit %",
        WeaponUpgradeType.CritDamage         => "Crit DMG",
        WeaponUpgradeType.Pierce             => "Pierce",
        WeaponUpgradeType.Radius             => "Radius",
        WeaponUpgradeType.ExplosiveShot      => "Explosive",
        WeaponUpgradeType.MoneyGainBonus     => "Money",
        WeaponUpgradeType.MoneyPerHit        => "$/Hit",
        WeaponUpgradeType.Slowing            => "Slow",
        WeaponUpgradeType.BeamChaining       => "Chain",
        WeaponUpgradeType.Knockback          => "Knockback",
        WeaponUpgradeType.SelfChargeSpeed    => "Charge Speed",
        WeaponUpgradeType.SetOnFire          => "Ignite",
        WeaponUpgradeType.APRounds           => "AP",
        WeaponUpgradeType.ArmorShred         => "Armor Shred",
        WeaponUpgradeType.SpawnItem          => "Additional Ammo",
        WeaponUpgradeType.LifeSteal          => "Life Steal",
        WeaponUpgradeType.StaminaSteal       => "Stamina Steal",
        WeaponUpgradeType.MovementSpeed      => "Move Speed",
        WeaponUpgradeType.AttackSpeed        => "Attack Speed",
        WeaponUpgradeType.Damage             => "Damage",
        WeaponUpgradeType.PelletCount        => "Pellets",
        WeaponUpgradeType.Scrapshot          => "Scrapshot",
        WeaponUpgradeType.Bleed              => "Bleed",
        WeaponUpgradeType.SlamFire           => "Slam Fire",
        WeaponUpgradeType.FlechetteRounds    => "Flechette",
        WeaponUpgradeType.SplinterImpact     => "Splinter",
        WeaponUpgradeType.OverchargeShot     => "Overcharge",
        WeaponUpgradeType.Overkill           => "Overkill",
        WeaponUpgradeType.Execution          => "Execution",
        WeaponUpgradeType.WarTorn            => "Battle Trance",
        WeaponUpgradeType.Suppression        => "Suppress",
        WeaponUpgradeType.Resonance          => "Resonance",
        WeaponUpgradeType.Prismatic          => "Prismatic",
        WeaponUpgradeType.MagEfficiency      => "Mag Eff.",
        WeaponUpgradeType.PulseCascade       => "Cascade",
        WeaponUpgradeType.Aftershock         => "Aftershock",
        WeaponUpgradeType.SpeedLoader        => "Speed Loader",
        WeaponUpgradeType.Overclocked        => "Spool",
        WeaponUpgradeType.IronBeast          => "Damage Resist",
        WeaponUpgradeType.ConcussionClub     => "Stun (Heavy)",
        WeaponUpgradeType.CritVsStunned      => "Stun Crit",
        WeaponUpgradeType.StunOnHit          => "Stun",
        WeaponUpgradeType.FlintlockCritSynergy => "Pirate Crit",
        WeaponUpgradeType.CritVsBurning      => "Fire Crit",
        WeaponUpgradeType.FireResist         => "Fire Resist",
        WeaponUpgradeType.WhileBurningBuff   => "Pyromaniac",
        WeaponUpgradeType.FuelEfficiency     => "Fuel Eff.",
        WeaponUpgradeType.FuelCapacity       => "Fuel Cap.",
        WeaponUpgradeType.WielderResistance  => "Resist",
        WeaponUpgradeType.DualWieldEnergySword => "Dual Wield",
        WeaponUpgradeType.VaporiseWeakMob    => "Vaporise",
        WeaponUpgradeType.PointBlankCrit     => "Point Blank",
        WeaponUpgradeType.ExecutionShot      => "First Strike",
        WeaponUpgradeType.MarksmansRhythm    => "Rhythm",
        WeaponUpgradeType.Barrage            => "Spool+Blast",
        WeaponUpgradeType.ShapedCharge       => "Shaped",
        WeaponUpgradeType.RadiationCoating   => "Radiation",
        WeaponUpgradeType.GravitonCore       => "Gravity Pull",
        WeaponUpgradeType.TeslaArcRange      => "Arc Range",
        WeaponUpgradeType.OverloadRound      => "Overload",
        WeaponUpgradeType.HomingBolts        => "Homing",
        WeaponUpgradeType.Multishot          => "Multishot",
        _                                    => "",
    };

    private static string Capitalize(string text)
        => text.Length == 0 ? text : text.Substring(0, 1).ToUpper() + text.Substring(1);
}
