using Content.Shared._FinalStand.ReadyCheck;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._FinalStand.ReadyCheck;

[GenerateTypedNameReferences]
public sealed partial class ReadyCheckPDAFragment : BoxContainer
{
    public event Action<ReadyStatus>? OnStatusPressed;

    public ReadyCheckPDAFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        ReadyButton.OnPressed += _ => OnStatusPressed?.Invoke(ReadyStatus.Ready);
        NotReadyButton.OnPressed += _ => OnStatusPressed?.Invoke(ReadyStatus.NotReady);
    }

    public void UpdateState(ReadyCheckPDAUiState state)
    {
        AccessDeniedLabel.Visible = !state.IsCommandRole;
        DeptStatusContainer.Visible = state.IsCommandRole;
        ButtonDivider.Visible = state.IsCommandRole && !state.IsCaptain;
        ButtonContainer.Visible = state.IsCommandRole && !state.IsCaptain;

        if (!state.IsCommandRole)
            return;

        RebuildDeptGrid(state.AllStatuses);

        if (!state.IsCaptain)
        {
            var buttonsEnabled = !state.IsCombatPhase;
            ReadyButton.Disabled = !buttonsEnabled;
            NotReadyButton.Disabled = !buttonsEnabled;

            ReadyButton.Modulate = state.MyStatus == ReadyStatus.Ready
                ? Color.FromHex("#44FF44")
                : Color.White;
            NotReadyButton.Modulate = state.MyStatus == ReadyStatus.NotReady
                ? Color.FromHex("#FF4444")
                : Color.White;
        }
    }

    private void RebuildDeptGrid(Dictionary<string, ReadyStatus> statuses)
    {
        DeptStatusContainer.RemoveAllChildren();
        foreach (var (code, status) in statuses)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };

            var codeLabel = new Label
            {
                Text = code,
                SetWidth = 40,
                Modulate = Color.FromHex("#DDDDDD"),
            };

            var (text, color) = status switch
            {
                ReadyStatus.Ready    => ("RDY",  "#44FF44"),
                ReadyStatus.NotReady => ("NO",   "#FF4444"),
                _                   => ("---",  "#888888"),
            };

            var statusLabel = new Label
            {
                Text = text,
                Modulate = Color.FromHex(color),
            };

            row.AddChild(codeLabel);
            row.AddChild(statusLabel);
            DeptStatusContainer.AddChild(row);
        }
    }
}
