using System.Linq;
using Content.Shared._FinalStand.CashTransfer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._FinalStand.CashTransfer.UI;

[GenerateTypedNameReferences]
public sealed partial class CashTransferWindow : DefaultWindow
{
    public event Action<int>? OnTransferConfirmed;

    public CashTransferWindow()
    {
        RobustXamlLoader.Load(this);

        AmountInput.OnTextChanged += OnAmountTextChanged;

        ConfirmButton.OnPressed += _ =>
        {
            if (!int.TryParse(AmountInput.Text, out var amount) || amount <= 0)
                return;

            ConfirmButton.Disabled = true;
            OnTransferConfirmed?.Invoke(amount);
        };

        CancelButton.OnPressed += _ => Close();
    }

    private void OnAmountTextChanged(LineEdit.LineEditEventArgs args)
    {
        var cleaned = new string(args.Text.Where(char.IsDigit).ToArray());
        if (cleaned != args.Text)
            AmountInput.Text = cleaned;
    }

    public void UpdateState(FSCashTransferBuiState state)
    {
        ToLabel.Text = $"To: {state.TargetName}";
        BalanceLabel.Text = $"Balance: {state.SenderBalance} credits";
        ConfirmButton.Disabled = false;
    }
}
