using System.Linq;
using System.Numerics;
using Content.Client._FinalStand.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._FinalStand.Perks;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics;
using Robust.Shared.Utility;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;
using ISImage = SixLabors.ImageSharp.Image;

namespace Content.Client._FinalStand.Perks.UI;

public sealed partial class PerkShopWindow
{
    private void RefreshInfo()
    {
        if (_selectedId == null || !FSPerkDef.All.TryGetValue(_selectedId, out var def))
        {
            SelectedPerkIcon.Texture    = null;
            SelectedIconCatBg.PanelOverride   = null;
            SelectedIconLevelBg.PanelOverride = null;
            SelectedNameLabel.Text         = "—";
            SelectedLevelLabel.Text        = "";
            SelectedCategoryLabel.Text     = "";
            SelectedDescLabel.SetMessage("");
            LevelEffectsBox.RemoveAllChildren();
            SelectedCostLabel.Text         = "";
            UpgradeButton.Text             = "Unlock / Upgrade";
            UpgradeButton.Disabled         = true;
            EquipButton.Disabled           = true;
            UnequipButton.Disabled         = true;
            return;
        }

        var level      = _state?.Levels.TryGetValue(def.Id, out var lvl) == true ? lvl : 0;
        var accent     = FSPerkPalette.Accent[def.Category];

        SelectedPerkIcon.Texture = GetPerkIcon(def.Id);
        SelectedPerkIcon.Stretch = TextureRect.StretchMode.KeepAspectCentered;
        SelectedIconCatBg.PanelOverride   = new StyleBoxFlat { BackgroundColor = FSPerkPalette.Background[def.Category] };
        SelectedIconLevelBg.PanelOverride = new StyleBoxFlat { BackgroundColor = FSPerkPalette.LevelRamp[def.Category][level] };

        SelectedNameLabel.Text         = def.Name;
        SelectedLevelLabel.Text        = $"Level {level} / {FSPerkDef.MaxLevel}";
        SelectedCategoryLabel.Text     = CatLabel[def.Category];
        SelectedCategoryLabel.Modulate = accent;
        SelectedDescLabel.SetMessage(def.Description);

        LevelEffectsBox.RemoveAllChildren();
        for (var i = 0; i < FSPerkDef.MaxLevel; i++)
        {
            Color labelColor;
            if (i < level)
                labelColor = FSUiPalette.StatePositive;
            else if (i == level)
                labelColor = FSUiPalette.AccentBrand;
            else
                labelColor = FSUiPalette.TextMuted;

            LevelEffectsBox.AddChild(new Label
            {
                Text = $"Lv {i + 1}: {def.LevelEffects[i]}",
                Modulate = labelColor,
            });
        }

        if (level < FSPerkDef.MaxLevel)
        {
            var cost = FSPerkDef.CostForUpgrade(level);
            UpgradeButton.Text     = level == 0 ? "Unlock" : $"Upgrade → Lv {level + 1}";
            SelectedCostLabel.Text = $"Cost: {cost} PP";
            UpgradeButton.Disabled = _state == null || _state.PerkPoints < cost;
        }
        else
        {
            UpgradeButton.Text     = "Max Level";
            SelectedCostLabel.Text = "MAX LEVEL";
            UpgradeButton.Disabled = true;
        }

        var isEquipped = _state?.Slots.Contains(_selectedId) == true;
        var hasEmpty   = _state?.Slots.Any(string.IsNullOrEmpty) == true;

        EquipButton.Disabled   = level <= 0 || isEquipped || !hasEmpty;
        UnequipButton.Disabled = !isEquipped;
    }

    private void RefreshPrestigeTab()
    {
        var eligible = _playerLevel >= 50;

        PrestigeLevelLabel.Text = _prestigeLevel > 0
            ? $"Prestige {_prestigeLevel} — Level {_playerLevel}"
            : $"Prestige 0 — Level {_playerLevel}";

        var bonus = _prestigeLevel * 20;
        PrestigeXpBonusLabel.Text = $"Current XP Bonus: +{bonus}%";

        PrestigeRequirementLabel.Text    = "Reach Level 50 to Prestige";
        PrestigeRequirementLabel.Modulate = eligible
            ? FSPerkPalette.Accent[PerkCategory.Yellow]
            : FSUiPalette.TextMuted;

        PrestigeButton.Disabled = !eligible;
        PrestigeButton.Modulate = eligible
            ? FSPerkPalette.Accent[PerkCategory.Yellow]
            : FSUiPalette.TextMuted;
    }

    private void ShowRespecConfirmation()
    {
        var dialog = new FancyWindow
        {
            Title     = "Respec Perks",
            Resizable = false,
            SetSize   = new Vector2(360, 160),
        };

        var vbox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, Margin = new Thickness(12) };
        vbox.AddChild(new Label { Text = "Reset all perks to level 0 and refund your PP?", Margin = new Thickness(0, 0, 0, 16) });

        var btnRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
        var confirm = new Button { Text = "Refund All", HorizontalExpand = true, Margin = new Thickness(0, 0, 6, 0) };
        confirm.Modulate = FSUiPalette.StateNegative;
        var cancel = new Button { Text = "Cancel", HorizontalExpand = true };

        confirm.OnPressed += _ => { OnRespecRequested?.Invoke(); dialog.Close(); };
        cancel.OnPressed  += _ => dialog.Close();

        btnRow.AddChild(confirm);
        btnRow.AddChild(cancel);
        vbox.AddChild(btnRow);
        dialog.AddChild(vbox);
        dialog.OpenCentered();
    }

    private void ShowPrestigeConfirmation()
    {
        var dialog = new FancyWindow
        {
            Title     = "Confirm Prestige",
            Resizable = false,
            SetSize   = new Vector2(400, 200),
        };

        var vbox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin      = new Thickness(12),
        };

        vbox.AddChild(new Label
        {
            Text     = "Prestige? Your level resets to 1.",
            Margin   = new Thickness(0, 0, 0, 4),
        });
        vbox.AddChild(new Label
        {
            Text     = "Perks and points are kept.",
            Margin   = new Thickness(0, 0, 0, 4),
        });
        vbox.AddChild(new Label
        {
            Text     = "You gain +20% permanent XP bonus.",
            Modulate = FSPerkPalette.Accent[PerkCategory.Yellow],
            Margin   = new Thickness(0, 0, 0, 16),
        });

        var btnRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };

        var confirm = new Button
        {
            Text             = "Confirm",
            HorizontalExpand = true,
            Margin           = new Thickness(0, 0, 6, 0),
        };
        confirm.Modulate = FSPerkPalette.Accent[PerkCategory.Yellow];

        var cancel = new Button
        {
            Text             = "Cancel",
            HorizontalExpand = true,
        };

        confirm.OnPressed += _ =>
        {
            OnPrestigeRequested?.Invoke();
            dialog.Close();
        };
        cancel.OnPressed += _ => dialog.Close();

        btnRow.AddChild(confirm);
        btnRow.AddChild(cancel);
        vbox.AddChild(btnRow);
        dialog.AddChild(vbox);
        dialog.OpenCentered();
    }
}
