using System.Numerics;
using Content.Shared._FinalStand.MedicalOps;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._FinalStand.MedicalOps;

public readonly record struct FSCasualtyRow(FSCasualtyEntry Entry, float? Distance, Vector2? Direction);

[GenerateTypedNameReferences]
public sealed partial class FSCasualtyBoardWindow : DefaultWindow
{
    private static readonly Color DeadColor = Color.FromHex("#5A6270");
    private static readonly Color CriticalColor = Color.FromHex("#C0392B");
    private static readonly Color HurtColor = Color.FromHex("#C9A227");
    private static readonly Color MutedColor = Color.FromHex("#7F8891");

    public event Action<NetEntity>? OnRespond;

    private readonly Dictionary<NetEntity, Bearing> _bearings = new();

    public FSCasualtyBoardWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(List<FSCasualtyRow> rows)
    {
        Entries.DisposeAllChildren();
        _bearings.Clear();
        EmptyLabel.Visible = rows.Count == 0;

        foreach (var row in rows)
        {
            var entry = row.Entry;
            var line = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 2),
            };

            line.AddChild(new Label
            {
                Text = StateText(entry.State),
                Modulate = StateColor(entry.State),
                MinWidth = 74,
                VerticalAlignment = VAlignment.Center,
            });

            line.AddChild(new Label
            {
                Text = entry.Name,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
            });

            var arrow = new FSBearingArrow
            {
                MinWidth = 18,
                MinHeight = 18,
                ArrowColor = StateColor(entry.State),
                Direction = row.Direction,
                VerticalAlignment = VAlignment.Center,
            };
            line.AddChild(arrow);

            var distance = new Label
            {
                Text = DistanceText(row.Distance),
                Modulate = MutedColor,
                MinWidth = 46,
                VerticalAlignment = VAlignment.Center,
            };
            line.AddChild(distance);

            _bearings[entry.Patient] = new Bearing(arrow, distance);

            if (entry.Responder is { } responder)
            {
                line.AddChild(new Label
                {
                    Text = Loc.GetString("fs-casualty-board-en-route", ("medic", responder)),
                    Modulate = MutedColor,
                    VerticalAlignment = VAlignment.Center,
                });
            }
            else
            {
                var patient = entry.Patient;
                var button = new Button
                {
                    Text = Loc.GetString("fs-casualty-board-respond"),
                    MinWidth = 90,
                };
                button.OnPressed += _ => OnRespond?.Invoke(patient);
                line.AddChild(button);
            }

            Entries.AddChild(line);
        }
    }

    public void UpdateBearing(NetEntity patient, float? distance, Vector2? direction)
    {
        if (!_bearings.TryGetValue(patient, out var bearing))
            return;

        bearing.Arrow.Direction = direction;
        bearing.Distance.Text = DistanceText(distance);
    }

    private static string DistanceText(float? distance)
    {
        return distance is { } value ? $"{value:0}m" : string.Empty;
    }

    private static string StateText(FSCasualtyState state) => state switch
    {
        FSCasualtyState.Dead => Loc.GetString("fs-casualty-state-dead"),
        FSCasualtyState.Critical => Loc.GetString("fs-casualty-state-critical"),
        _ => Loc.GetString("fs-casualty-state-hurt"),
    };

    private static Color StateColor(FSCasualtyState state) => state switch
    {
        FSCasualtyState.Dead => DeadColor,
        FSCasualtyState.Critical => CriticalColor,
        _ => HurtColor,
    };

    private readonly record struct Bearing(FSBearingArrow Arrow, Label Distance);
}
