using Content.Client._FinalStand.Interface;
using Robust.Client.Graphics;
using Robust.Shared.Utility;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Inventory.Widgets;

[GenerateTypedNameReferences]
public sealed partial class InventoryGui : UIWidget
{
    public InventoryGui()
    {
        RobustXamlLoader.Load(this);

        var inventoryUIController = UserInterfaceManager.GetUIController<InventoryUIController>();
        inventoryUIController.RegisterInventoryBarContainer(InventoryHotbar);

        FSInventoryPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = FSPalette.PanelBack,
            BorderColor = FSPalette.PanelEdge,
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 4,
            ContentMarginRightOverride = 4,
            ContentMarginTopOverride = 4,
            ContentMarginBottomOverride = 4,
        };

        InventoryHotbar.OnVisibilityChanged += _ => FSInventoryPanel.Visible = InventoryHotbar.Visible;
        FSInventoryPanel.Visible = InventoryHotbar.Visible;

        LayoutContainer.SetGrowVertical(this, LayoutContainer.GrowDirection.Begin);
    }
}
