using System.Numerics;
using Content.Client._FinalStand.Interface;
using Content.Client._FinalStand.WaveHud;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Content.Shared.Hands.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.UserInterface.Systems.Hotbar.Widgets;

[GenerateTypedNameReferences]
public sealed partial class HotbarGui : UIWidget
{
    [Dependency] private IClyde _clyde = default!;

    private Vector2i _lastScreenSize;
    private float _lastUIScale = -1f;

    public HotbarGui()
    {
        RobustXamlLoader.Load(this);
        StatusPanelRight.SetSide(HandLocation.Right);
        StatusPanelLeft.SetSide(HandLocation.Left);
        StatusPanelRight.Visible = false;
        StatusPanelLeft.Visible = false;

        HandsPanel.PanelOverride = FSHudStyle.ModulePanel();
        StoragePanel.PanelOverride = FSHudStyle.ModulePanel();

        foreach (var grid in new[] { SecondHotbar, MainHotbar })
        {
            grid.ButtonSize = WaveHudOverlay.HudSlotSize;
            grid.HSeparationOverride = (int) WaveHudOverlay.HudSlotGap;
            grid.VSeparationOverride = (int) WaveHudOverlay.HudSlotGap;
        }

        // FINALSTAND: hands hold the centre; the storage row tracks the right edge so it stays
        // flush under the wave HUD's weapon module.
        Anchor(HandsPanel, HandsFraction);
        ApplyStorageWidth();

        var hotbarController = UserInterfaceManager.GetUIController<HotbarUIController>();
        hotbarController.Setup(HandContainer);
        LayoutContainer.SetGrowVertical(this, LayoutContainer.GrowDirection.Begin);
    }

    private const float HandsFraction = 0.5f;

    public const float BandInset = 5f;

    // The row spans the bag toggle plus the six storage slots, at the shared HUD slot size.
    private const float StoragePanelVerticalMargin = 7f;

    public const float StorageRowHeight = WaveHudOverlay.HudSlotSize + StoragePanelVerticalMargin * 2f + 2f;

    protected override void UIScaleChanged()
    {
        base.UIScaleChanged();
        ApplyStorageWidth();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        // Also polls UIScale directly - a HUD-layout switch builds a new HotbarGui, and UIScaleChanged doesn't reliably fire for that.
        var screenSize = _clyde.ScreenSize;
        if (screenSize != _lastScreenSize || MathF.Abs(UIScale - _lastUIScale) > 0.001f)
        {
            _lastScreenSize = screenSize;
            _lastUIScale = UIScale;
            ApplyStorageWidth();
        }
    }

    // A real Control already scales with UIScale, so only the window-size part needs matching.
    private void ApplyStorageWidth()
    {
        var scale = UIScale <= 0f ? 1f : UIScale;
        var resolutionFactor = WaveHudOverlay.GetResolutionFactor(_clyde.ScreenSize.X);

        StoragePanel.MinSize = new Vector2(WaveHudOverlay.WeaponPanelWidth * resolutionFactor, 0f);
        AnchorRight(RightGroup, WaveHudOverlay.ScreenMargin / scale - BandInset);
    }

    private static void AnchorRight(Control control, float margin)
    {
        LayoutContainer.SetAnchorLeft(control, 1f);
        LayoutContainer.SetAnchorRight(control, 1f);
        LayoutContainer.SetAnchorTop(control, 1f);
        LayoutContainer.SetAnchorBottom(control, 1f);
        LayoutContainer.SetMarginLeft(control, -margin);
        LayoutContainer.SetMarginRight(control, -margin);
        LayoutContainer.SetMarginTop(control, 0f);
        LayoutContainer.SetMarginBottom(control, 0f);
        LayoutContainer.SetGrowHorizontal(control, LayoutContainer.GrowDirection.Begin);
        LayoutContainer.SetGrowVertical(control, LayoutContainer.GrowDirection.Begin);
    }

    private static void Anchor(Control control, float fraction)
    {
        LayoutContainer.SetAnchorLeft(control, fraction);
        LayoutContainer.SetAnchorRight(control, fraction);
        LayoutContainer.SetAnchorTop(control, 1f);
        LayoutContainer.SetAnchorBottom(control, 1f);
        LayoutContainer.SetMarginLeft(control, 0f);
        LayoutContainer.SetMarginRight(control, 0f);
        LayoutContainer.SetMarginTop(control, 0f);
        LayoutContainer.SetMarginBottom(control, 0f);
        LayoutContainer.SetGrowHorizontal(control, LayoutContainer.GrowDirection.Both);
        LayoutContainer.SetGrowVertical(control, LayoutContainer.GrowDirection.Begin);
    }

    public void UpdatePanelEntityLeft(EntityUid? entity, Hand? hand)
    {
        StatusPanelLeft.Update(entity, hand);
    }

    public void UpdatePanelEntityRight(EntityUid? entity, Hand? hand)
    {
        StatusPanelRight.Update(entity, hand);
    }

    public void SetHighlightHand(HandLocation? hand)
    {
        StatusPanelLeft.UpdateHighlight(hand is HandLocation.Left);
        StatusPanelRight.UpdateHighlight(hand is HandLocation.Right);
    }

    // FINALSTAND: the wave HUD draws a single module for the active hand, so vanilla's per-hand panels stay hidden - two of them beside the hands read as a second pair of hands.
    public void UpdateStatusVisibility(bool left, bool right)
    {
        StatusPanelLeft.Visible = false;
        StatusPanelRight.Visible = false;
    }
}
