using Content.Shared.Hands.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Hotbar.Widgets;

[GenerateTypedNameReferences]
public sealed partial class HotbarGui : UIWidget
{
    public HotbarGui()
    {
        RobustXamlLoader.Load(this);
        StatusPanelRight.SetSide(HandLocation.Right);
        StatusPanelLeft.SetSide(HandLocation.Left);
        StatusPanelRight.Visible = false;
        StatusPanelLeft.Visible = false;
        var hotbarController = UserInterfaceManager.GetUIController<HotbarUIController>();

        hotbarController.Setup(HandContainer);
        LayoutContainer.SetGrowVertical(this, LayoutContainer.GrowDirection.Begin);

    }

    public void UpdatePanelEntityLeft(EntityUid? entity, Hand? hand)
    {
        StatusPanelLeft.Update(entity, hand);
    }

    public void UpdatePanelEntityRight(EntityUid? entity, Hand? hand)
    {
        StatusPanelRight.Update(entity, hand);
    }

    public void SetHighlightHand(HandLocation? hand)
    {
        StatusPanelLeft.UpdateHighlight(hand is HandLocation.Left);
        StatusPanelRight.UpdateHighlight(hand is HandLocation.Right);
    }

    // FINALSTAND: the wave HUD draws a single module for the active hand, so vanilla's per-hand
    // panels stay hidden - two of them beside the hands read as a second pair of hands.
    public void UpdateStatusVisibility(bool left, bool right)
    {
        StatusPanelLeft.Visible = false;
        StatusPanelRight.Visible = false;
    }
}
